### ISSUE TITLE
Truck gives off quite some XP

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1145]
```
Object ChinaVehicleSupplyTruck
  ExperienceValue = 50 50 50 50

Object AmericaVehicleChinook
  ExperienceValue = 50 50 50 50

Vees/Quads/Gats:
  ExperienceValue = 50 50 100 150

Object GLAVehicleTechnicalChassisOne
  ExperienceValue = 25 25 50 100
```

1. Truck kill grants 50xp, which is the same amount as many combat units like Vees, Quads, Gats etc. A Technical even gives off 25xp only. The obvious difference here is that it's defenseless and can't easily escape danger. It's vulnerable vs any type of unit.

3. Chinooks give off the same amount, but is obviously a higher tech/value unit. Chinook collection can be interrupted from greater distances, but it can also escape faster and has less enemies than Trucks.

4. Workers on the other hand don't grant any XP at all. They're more vulnerable than Trucks, can't crush infantry, but can escape easier into tunnels.

5. Another thing to keep in mind is that they leave Scraps behind aswell.

6. 25-40xp might be a more balanced number and would buff China a little bit.

**Comment by ReLaX82** [comment]
It is a little dependent on how the scraps willbe handeld I think. If scrapping up keeps nearly the same then I would reduce the XP of trucks for sure.

**Comment by Stubbjax** [comment]
Definitely agree. I used to think even 40 would be controversial but seeing the numbers laid out, 25 seems very reasonable. This is especially true considering the primary element of gameplay that is affected as a result - Technical harassment.

It might also be worth considering altering the (kind of strange) Technical experience requirements in tandem, e.g. [0 50 75 150] → [0 50 100 150], so that each rank requires two truck kills and the effect of Technical Training remains as a consistent 1/3 bonus.

**Comment by xezon** [comment]
I am very skeptical of changing Technical 0 50 75 150 to 0 50 100 150, because this is very important unit in competitive matches and raising its veteran requirement will have significant impact. We would first need to determine if 2 Star Technical indeed should be more rare. I do not know how to do that.

**Comment by Stubbjax** [comment]
It is a fairly subtle change though, and is essentially the equivalent of two infantry. I would not except the impact to be that significant - at least not in a detrimental way. I find it quite ridiculous that in a typical Defcon 6 game, a Technical can simply drive straight to an opponent's oils, kill the two Rangers there and be immediately elite rank, especially when that's not even enough to go from unranked to veteran.

Assuming Technical Training is bought: Against other GLAs such a change might be noticeable, as killing another Technical would no longer be a guaranteed elite rank, though killing any other units such as Quad Cannons would not present any difference. Regardless, it doesn't matter in terms of balance with GLA vs GLA as both factions deal with the same units. Against China it would clearly be a welcome change as it would take some of the weight off of the "super tech" potential and shift some of the critical gameplay away from truck defence. Against USA, killing 2 Humvees would still result in heroic rank, so the only difference would be the extra two infantry kills between veteran and elite rank, if applicable.

Perhaps it could be changed from [0 50 75 150] → [0 50 80 150] so that a single 25xp truck kill doesn't immediately grant elite rank, while retaining the rapid transition from veteran to elite rank that players are used to.

**Comment by ExiLe-ZH** [comment]
Tech Elite Requirement to 100 indeed isn't the biggest change, most vehicle kills (except other techs) grant 50xp, so it still becomes Elite with 1 kill. The only difference is having to kill 3 RPGs/MDs/THs instead of 2 since they grant 20xp.

With this change, anything under 50xp for the Truck would instantly help with Tech harass.

- At 50xp is 1 kill for Elite, 2 for Hero.
- At 40xp is 2 kills for Elite (or 1 + 1 TH), 3 for Hero (or 2 + 1 TH).
- At 30xp is 2 kills for Elite (or 1 + 1 TH), 4 for Hero (or 3 + 1 TH).
- At 25xp is 2 kills for Elite, 4 for Hero.

**Comment by xezon** [comment]
Increasing 2 Star requirement of Technical will make it more difficult for GLA to build up strong groups of Technicals. The ability of self heal is important for the Technical. If this is more difficult to acquire, then promoted Technicals will be less likely. Other than weak Trucks, do we think Technicals are too good vs China, USA and GLA in general?

**Comment by ExiLe-ZH** [comment]
Tech balance vs USA is good, should not be nerfed. The proposed changes however don't affect the balance with USA much, as my comment above states; a Tech has to kill three instead of two MD's. One Vee kill still promotes it to Elite instantly.

Tech balance in GLA mirrors is also good (obviously), but the change will make Techs a little less powerful. To become Elite a Tech now has to take out two enemy Techs instead of one, or three RPG's instead of two. Taking out bigger vehicles like Quads still promotes it to Elite with one kill.

One thing to keep in mind though is that Scrap Denial will probably be no longer a thing in the Patch, this makes their potential much greater, which would be unacceptable vs China'ss without counter nerfs. Super Techs are absolutely OP versus China's; their speed, damage output, combined with the self-healing ability (which is currently too easily obtained by killing trucks), makes it so that GLA can keep coming back to harrass without having to retreat (into a Tunnel). 

So combining the Tech Requirement change with a reduced Truck XP Reward could be a step in the right direction of solving the whole Scrap issue.

The alternative is reducing the Truck XP Reward from 50 to 20, as much as a TH. Then you wouldn't have to touch the Tech Elite Requirement.

**Comment by xezon** [comment]
Yes. My question was hinting towards adjusting Truck instead of Jeep. Touching Jeep has much more consequences. However, touching Truck also affects rewards vs USA. Is this desired?

**Comment by MTKing4** [comment]
I agree about reducing truck xp reward as opposed to increase tech's requirements
Also don't think it affects USA matchups too much so it's fine

**Comment by ExiLe-ZH** [comment]
> Yes. My question was hinting towards adjusting Truck instead of Jeep. Touching Jeep has much more consequences. However, touching Truck also affects rewards vs USA. Is this desired?

Well I described the consequences, where I also took Scraps into account. Depending on how that will be handled ofcourse, but it most likely will still be a huge buff for Techs.

As for USA, it's alot easier to farm XP vs China than vs GLA, trucks are a major factor here. Vetted Vees can be a huge problem for China's, although it takes more than one kill to become Elite, opposed to Techs that spawn in as Veteran (with the promotion). I think a reduction is fair vs USA, however we have to see how it combines with other China Buffs like Doortimes.

**Comment by Stubbjax** [comment]
It's important to note that the power of Technicals vs USAs primarily lies in their numbers, not in their ranks.

I think the benefits of nerfing the Technical's xp requirements significantly outweigh the potential drawbacks. Combined with a 25xp yield reduction for the Supply Truck, such a change would directly target and likely solve the "super tech" issue while having minimal impact on other areas of the game.

Even just a requirement increase from [0 50 75 150] → [0 50 80 150] would be a substantial improvement, if there is too much apprehension with a [0 50 75 150] → [0 50 100 150] increase. Either way, I'd still argue the gap between veteran and elite is still too small.

**Comment by xezon** [comment]
We can try.

**Comment by ExiLe-ZH** [comment]
> It's important to note that the power of Technicals vs USAs primarily lies in their numbers, not in their ranks.

I do not agree with this first part though, veterancy is a greatly deciding factor in these engagements. If you skip the tech vet promotion you're gonna have a bad time. Elite Techs also greatly change engagements.

Also like I mentioned before, the Elite requirement proposal doesn't change that all that much probably. Killing 1 Vee still grants that same like before, but it will change the MD killcount from 2 to 3.

**Comment by fastAiRR** [comment]
Reducing the xp of trucks will help reinforce their scouting ability. I mean, putting trucks around the map for vision after the supply is finished(I do this sometimes, so others may as well). But yea the xp is bad currently making this not a great strat.

**Comment by Stubbjax** [comment]
> > It's important to note that the power of Technicals vs USAs primarily lies in their numbers, not in their ranks.
> 
> I do not agree with this first part though, veterancy is a greatly deciding factor in these engagements. If you skip the tech vet promotion you're gonna have a bad time. Elite Techs also greatly change engagements.

Sure, rank is important, but it is nowhere near as much of a deciding factor as numbers. In terms of raw damage output and survivability, 10 unranked techs are better than 8 veteran techs / 6 elite techs / 5 heroic techs. This is especially true against Humvees, which tend to target one unit at a time with missile volleys that often result in a lot of overkill, which is far more effective against smaller groups / meatier targets. Damage could also be spread across more targets with higher numbers. The ratio is likely even lower.

> Also like I mentioned before, the Elite requirement proposal doesn't change that all that much probably. Killing 1 Vee still grants that same like before, but it will change the MD killcount from 2 to 3.

This would also slightly reduce the punishment / risk of evacuating a Humvee before death.

**Comment by xezon** [comment]
This issue is resolved. With #1680 trucks now give just 25 XP.

| Gatherer                   | Cost  | XP reward | Leaves scrap ? |
|----------------------------|-------|-----------|----------------|
| Original USA Chinook       | 1200  | 50        | No             |
| Patched China Supply Truck | 600   | 25        | Yes            |
| Original GLA Worker        | 200   | 0         | No             |
