### ISSUE TITLE
Should Worker kills grant a few XP?

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1146]
Right now it's 0.

Is this fair vs Trucks and Chinooks? Both grant 50xp.

Here other GLA infantry units:

```
Object GLAInfantryRebel
  ExperienceValue     = 15 15 30 40     ;Experience point value at each level
  ExperienceRequired  = 0 40 60 120     ;Experience points needed to gain each level

Object GLAInfantryTunnelDefender
  ExperienceValue = 20 20 40 60    ;Experience point value at each level
  ExperienceRequired = 0 100 200 400  ;Experience points needed to gain each level

Object GLAInfantryTerrorist
  ExperienceValue     = 20 20 20 20  ; Experience point value at each level
```

Should it be like 5 or 10xp max? Since a Rebel grants 15xp.

**Comment by ReLaX82** [comment]
Isnt fair compared to trucks.
I would say third of a truck is okay.

**Comment by ImTimK** [comment]
Well trucks are a little high in 1.04 (50xp), but since they cost 3x more than workers we can hold on to this ratio (whatever we do with trucks).

**Comment by ExiLe-ZH** [comment]
A third of a Truck is 16.67xp, which is more than a Rebel. Now I also opened another topic that proposes to reduce Trucks, because 50xp is relatively high: https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1145

A 1/3rd Ratio would make sense since a Truck is 3x more expensive. So if we put workers at 10xp for example, 30xp for Trucks does sound fair.

But let's see if there's evidence against such proposals.

**Comment by commy2** [comment]
Dozers also grant no XP.

Also, while units with 0 XP yield don't grant XP to units, they still grant 1 XP to players.

**Comment by xezon** [comment]
It is not clear to me what the reason is that Builders give no XP on kill. A reward of 5 would have sounded ok for starters.

Assuming Early Game, 2 Supplies:

| Object                    | Typical Count  | XP on kill each | XP on kill all |
|---------------------------|----------------|-----------------|----------------|
| Original USA Dozer        | 2              | 0               | 0              |
| Original China Dozer      | 2              | 0               | 0              |
| Original GLA Worker       | 18             | 0               | 0              |
| Original China Truck      | 4              | 50              | 200            |
| Original USA Chinook      | 4              | 50              | 200            |
| Patched USA Dozer         | 2              | 5               | 10             |
| Patched China Dozer       | 2              | 5               | 10             |
| Patched GLA Worker        | 18             | 5               | 90             |

```
GLAVehicleTechnicalChassisOne
  ExperienceRequired = 0 50 75 150

AmericaVehicleHumvee
  ExperienceRequired = 0 100 150 300
```

Reduced Truck XP would help China enormously, because GLA Technical would no longer become 3 Star after just 2 kills.

If GLA Worker would give 5 XP, then 1 Star Technical can become 2 Star after wiping one Supply Stash of 5 Workers.

**Comment by xezon** [comment]
Close?

**Comment by ExiLe-ZH** [comment]
Have we decided not to add xp for workers?

**Comment by xezon** [comment]
Is it a problem that Workers give no kill XP?

**Comment by MTKing4** [comment]
Workers collect money, same as trucks and chinooks, yet only the latter two grant XP, so i think so should the workers

Workers can't be compared to Dozers as they are far superior and have double the purpose, can collect and build compared to just build, so i think it's the right choice for them to grant 10xp

**Comment by xezon** [comment]
It will have quite some impact on GLA vs GLA, where a Technical driving over workers is already a severe punishment, which an additional XP yield would exacerbate.

Is this desired?

**Comment by ExiLe-ZH** [comment]
True point.

By the same token losing techs in enemy base now also gives off scraps which can not be denied. So both more risk and more reward.

Another thing is that workers will be easier to save into tunnels with the new 'force-repair' feature.

**Comment by MTKing4** [comment]
Yes, also we're planning on increasing XP requirements for technical so things should even up

**Comment by ExiLe-ZH** [comment]
> Yes, also we're planning on increasing XP requirements for technical so things should even up

This change might be necesarry indeed to counter-act scrap deny removal and I think there's a good chance all these changes harmonize together pretty well.

**Comment by xezon** [comment]
> Yes, also we're planning on increasing XP requirements for technical so things should even up

If Workers give XP, then Technical can reach Vet3 faster, even with change #1680 applied. Plus anz other units will rank up quicker: Humvee, Quad, Gattling, Dragon, etc.

What is the goal here?

**Comment by ExiLe-ZH** [comment]
Depends how much xp workers give off, at 5xp (and 10 for dozers?) 5 workers kills evens it out with the original requirements, though with the potential to kill more workers ofcourse.

In GLA mirrors it all simply means Techs become more valuable. There shouldn't be balance concerns here, as both sides can utilize Techs.

Versus other armies GLA will experience a pretty huge buff with scrap-denial removed, so adding worker xp might be one of the instruments to restore balance there. Indeed giving units like Vees, Dragons and Gats more opportunity to vet up.

**Comment by MTKing4** [comment]
Agree with Exile here, That being said i don't like dozers giving XP (especially not more than workers), they're already a high priority target and losing them puts the player in a huge disadvantage, letting them give off XP is just making the disadvantage even worse, not to mention that higher incentive to dozer hunt

I see it being Ok to workers because they're hybrid units that can build and collect and are abundant in the game which makes GLA harder to get worker hunted, dozers cannot collect and are more expensive and are easier to hunt

**Comment by xezon** [comment]
If Workers give XP, then it would be nice if Dozers did too. Because otherwise we retain the same inconsistency as right now where Worker (Gatherer) gives no XP but other Gatherers do.

**Comment by ExiLe-ZH** [comment]
Only concern with Techs vetting up faster (after 5 worker kills) is in teamgames though, got to keep that in mind.

**Comment by MTKing4** [comment]
> If Workers give XP, then it would be nice if Dozers did too. Because otherwise we retain the same inconsistency as right now where Worker (Gatherer) gives no XP but other Gatherers do.

True, but I'm a bit worried about the downsides of xp rewards for dozers, we would need to make sure it's not too rewarding for the enemy player

**Comment by xezon** [comment]
Dozer count is severely limited, so a kill reward of 5 or 10 would be more symbolic than practical. We have also added 5 ann 10 XP to other things already:

* #414
* #778

**Comment by ExiLe-ZH** [comment]
> Dozer count is severely limited, so a kill reward of 5 or 10 would be more symbolic than practical. We have also added 5 ann 10 XP to other things already:
> 

Yea I don't think Dozer XP is a concern, depending on the value ofcourse.

Even at 20 it's not gamechanging I don't think if we increase the Tech requirement, it's not much compared to Truck kills (50XP). Also it's usually the RPG's killing the Dozers.

**Comment by xezon** [comment]
So give 5 kill XP to all worker units?

**Comment by ExiLe-ZH** [comment]
I've studied the experience document a bit more, but the reality is most vehicles at a minimum require 100XP to become veteran, Vanilla Gats and Dragons being exceptions at 80XP, which still equals 16 worker kills. This doesn't seem very helpful.

Technicals are probably affected most by this change, even after the requirement change. Again, in mirrors this isn't much of a concern, but in teamgames it could be. 

So I'm not too sure about this change anymore. Neither am I sure about higher XP values, 10XP surely is too much and 8XP probably still is?

**Comment by xezon** [comment]
XP values should be in increments of 5.

**Comment by ExiLe-ZH** [comment]
10XP surely is too much, we can't further increase Tech requirements because it would change Tech vs Vee balance. A Vee kill (50XP) would no longer promote a Veteran Tech to Elite anymore.

**Comment by xezon** [comment]
> which still equals 16 worker kills. This doesn't seem very helpful.

I do not think 5 XP a piece should be seen as the sole XP provider for a technical. It can still kill other things, such as Rebels, RPG's and other vehicles to gain veterancy too.

**Comment by ExiLe-ZH** [comment]
> > which still equals 16 worker kills. This doesn't seem very helpful.
> 
> 
> 
> I do not think 5 XP a piece should be seen as the sole XP provider for a technical. It can still kill other things, such as Rebels, RPG's and other vehicles to gain veterancy too.

You quoted the part where I talked about Vanilla Dragons and Gats. Ofcourse other kills count too, it all adds up. But overall I see this change affect Techs the most, because it's a fast unit that has a much easier time getting into supply lines compared to other units.

**Comment by xezon** [comment]
Close this?

**Comment by ExiLe-ZH** [comment]
Yea for now.

I'm wondering btw, would Trucks and USA dozers vet up by crushing workers with this change? 😄

**Comment by MTKing4** [comment]
> I've studied the experience document a bit more, but the reality is most vehicles at a minimum require 100XP to become veteran, Vanilla Gats and Dragons being exceptions at 80XP, which still equals 16 worker kills. This doesn't seem very helpful.
> 
> Technicals are probably affected most by this change, even after the requirement change. Again, in mirrors this isn't much of a concern, but in teamgames it could be.
> 
> So I'm not too sure about this change anymore. Neither am I sure about higher XP values, 10XP surely is too much and 8XP probably still is?

16 workers is already too much, i don't see the issue here

Most supplies will have around 7 workers or less, techs tend to miss some, or die at the supply, if it killed two full supplies that's 14 wokers it's still not a vet, and it's unlikely to kill this many workers untouched, pretty sure in most Senarios techs don't kill over 10 workers, and if they did i think the reward is deserved

As for other units, they're too slow and will probably die before reaching second supply, if not i still don't see a promotion so bad here

**Comment by xezon** [comment]
With #1680 applied, the fair XP yield just based on Worker cost would be 8.3

Chinook cost 1200, XP yield 50
Truck cost 600, XP yield 25 (#1680)
Worker cost 200 yield 8.3

Rounding XP down to 5 would make sense too, if we consider that Dozers give 0 XP.

With #1680 applied and a Worker XP yield of 5, it would take a Technical 10 Worker kills to 
reach next rank. 30 Worker kills to go from Vet 0 to Vet 3.
