### ISSUE TITLE
Dozer hunt meta

### ISSUE THREAD

**Issue by KrewGR** [TheSuperHackers/GeneralsGamePatch#1188]
This is very controversial I think, and would require a lot of thought, but it seems we have a serious dozer hunting problem in that it's too easy to perform. 

Considering the gla worker, for 200, it's quite good in a very good way, where the only thing it is missing is the ability to crush. The option to keep command center for USA and China is not an there, as that 1000 is very much needed to keep up with the 20 year meta build orders. I propose a few ideas:

### Proposal 1

600 cost for a USA and China dozer so that the potential for 3 dozer strat is possible. This will save 400 for every start. 
Problems: USA dozer crush rush could be abused vs gla.

### Proposal 2

A dozer armor upgrade within the dozer unit. Perhaps the upgrade give double health?
Problem: dozer rush could be overpowered with such upgrade if not priced correctly within the build order. Patriot drop could be abused.

### Proposal 3

Reduce cost of SW/vUSA/Laser Chinook and China supply truck to allow keep cc build order option.
Problem: supply truck rush can be spammed and abused.

### Proposal 4

Reduce overall cost of select structures to allow option for cc keep. (In my opinion, best solution) This can allow you to risk dozer hunt for that extra 1000 if you want, but not be a defeat if you chose to keep cc.

**Comment by MTKing4** [comment]
I think the safest option would be to just give dozers a litte bit more hp, so that it can take a few more rockets before dying, maybe %50 increase

**Comment by xezon** [comment]
If player sells Command Center for 1000, then player accepts the risk of using worker units. It is true that GLA has advantage here because GLA Worker hunt is unlikely to happen. This risk discrepancy gives GLA an advantage.

Proposal 1 is too drastic as it will give China and USA more cash to begin with if they still sell Command Center (which they will).

Proposal 2 may be ok to give Dozer more health to make it more robust against harassment and increase survivability.

Proposal 3 yield same result as Proposal 1.

Proposal 4 yield same result as Proposal 1.

**Comment by ExiLe-ZH** [comment]
Maybe only give china dozer slight more resistance vs rpgs, since it's slower and can't be dropped/sent to harass, deny map control etc.

**Comment by xezon** [comment]
I would be ok with that. USA can still evacuate Dozers with Chinook, so it is typically better off than China.

**Comment by RisingZH** [comment]
Leave it as it is.

The China dozer movement fix will already help a lot.

**Comment by Jundiyy** [comment]
Agreed, China should play out better. 
And USA Dozer is also fine.

Player is willing to take the risk when selling the CC to gain extra income at the start.

**Comment by xezon** [comment]
USA and China Dozer have equal Armor and Health. Closing, as consensus appears everything is fine as is.

**Comment by ExiLe-ZH** [comment]
It can't be denied the China Dozer is inferior in every way though, even with the locomotor change. 

- Slower turnrate. 
- No reverse gear.
- Harder to box in, USA can box using supply dock. Although (half) measures can be taken to park dozer on mines (pretty decent with defensive structures), but requires additional investment which isn't viable with every build order. 
- Can't be dropped/saved with a Chinook in virtually any stage of the game. Helix can technically save Dozer, but is very situational (practically never happens) and certainly not effective offensively.

Does China deserve any pros? When it comes to China Units in general, the price usually tries to make up for inferiority.

**Comment by xezon** [comment]
```
Locomotor AmericaVehicleDozerLocomotor
  Surfaces            = GROUND
  Speed               = 30   ; in dist/sec
  SpeedDamaged        = 25   ; in dist/sec
  TurnRate            = 90   ; in degrees/sec
  TurnRateDamaged     = 60   ; in degrees/sec
  Acceleration        = 30   ; in dist/(sec^2)
  AccelerationDamaged = 8    ; in dist/(sec^2)
  Braking             = 50  ; in dist/(sec^2)
  MinTurnSpeed        = 25   ; in dist/sec
  ZAxisBehavior       = NO_Z_MOTIVE_FORCE
  Appearance          = FOUR_WHEELS

  CanMoveBackwards = Yes
End

Locomotor ChinaVehicleDozerLocomotor
  Surfaces            = GROUND
  Speed               = 30   ; in dist/sec
  SpeedDamaged        = 25   ; in dist/sec
  TurnRate            = 90   ; in degrees/sec
  TurnRateDamaged     = 60   ; in degrees/sec
  Acceleration        = 30   ; in dist/(sec^2)
  AccelerationDamaged = 8    ; in dist/(sec^2)
  Braking             = 50  ; in dist/(sec^2)
  MinTurnSpeed        = 0   ; in dist/sec
  ZAxisBehavior       = NO_Z_MOTIVE_FORCE
  Appearance          = FOUR_WHEELS; TREADS

  CanMoveBackwards = No
End
```

America Dozer advance is MinTurnSpeed = 25, which gives it some speed when turning. China Dozer has none.

**Comment by KrewGR** [comment]
Perhaps more health for both dozers and the ability to back up for China dozer would help greatly?

**Comment by xezon** [comment]
Ah indeed, one major detail I forgot to add, USA Dozer has CanMoveBackwards = Yes, China Dozer does not. Certainly locomotor of USA Dozer is better. And USA has Chinooks for quick evacuation.

I think it is fair to do something for China Dozer, considering GLA and USA have better chances.

**Comment by RisingZH** [comment]
I disagree. There's already been one change to china dozers, let's just wait and see how it plays out as we don't know the full impact. Adding changes on top of changes without them even being played is a bad idea and increases the chances of making things worse rather than better. 

Also I've seen in a few reports the logic of 'other factions have a better equivalent unit/building etc so we need to buff this' which I disagree with. ZH is fun because the factions are diverse, if we just change everything so they are similar the game will become bland. It's fine for China to have shitty dozers if it has other strengths to make up for it.

@Exile China can very easily box their dozer in a triangle with supply, wf and rax if they want to.

**Comment by KrewGR** [comment]
China can't really expand though without losing its dozer. You have to time it perfect to make sure dozer is safe, which is part of the reason China is the worst faction. All it takes is 2 rpgs and a tech to hunt both usa and china dozers. The cost is so little, and the reward is so high.

I think this is one of those things that you got so used to but fail to realize the imbalance of how easy it really is.

**Comment by ExiLe-ZH** [comment]
> @exile China can very easily box their dozer in a triangle with supply, wf and rax if they want to.

I'm aware, but that leaves your trucks fully exposed.

**Comment by ExiLe-ZH** [comment]
> @RisingZH Also I've seen in a few reports the logic of 'other factions have a better equivalent unit/building etc so we need to buff this' which I disagree with. ZH is fun because the factions are diverse, if we just change everything so they are similar the game will become bland. It's fine for China to have shitty dozers if it has other strengths to make up for it.

True, the direct comparison is only valid when there are no alternatives. In case of denying (early) map control China arguably has the advantage since it doesn't need to risk a Dozer at all, it can use Trucks instead (which has the downside of granting XP and Scraps, but we're looking into this aswell).

> @KrewGR China can't really expand though without losing its dozer. You have to time it perfect to make sure dozer is safe, which is part of the reason China is the worst faction. All it takes is 2 rpgs and a tech to hunt both usa and china dozers. The cost is so little, and the reward is so high.
> 
> I think this is one of those things that you got so used to but fail to realize the imbalance of how easy it really is.

Well this statement isn't entirely true, China just needs it's main army or atleast a couple of units with the Dozer when he's pushing forward.

**Comment by xezon** [comment]
> ZH is fun because the factions are diverse, if we just change everything so they are similar the game will become bland.

This is misleading statement to make, as it implies misconfiguration is ok in the name of faction diversity, even if misconfiguration can be proven to be detrimental to fair setup. This statement could be made about Airforce vs China, they are different factions and diverse, thus fine as is. On this basis we cannot discover better setups, as one can simply drop this sentence anywhere whenever he likes to.

On top of that the statement is also wrong, because one of the suggestions was to give China Dozer more Armor against Infantry Missile, in which case it would be different from USA Dozer. As instead, USA and China Dozer have exact same Armor and Health, and thus would fit your statement of game being bland.

**Comment by RisingZH** [comment]
I'm not sure what you mean by misconfiguration and my following sentence clarified the point. The issue with air is that as an overall army it basically has all pro's and no con's whereas vchina has all con's and very few pro's.

A better example is tank vs stealth. One of the most fun matchups and about as balanced as you could hope for, but the armies strengths and weaknesses are basically complete opposite of each other.

**Comment by xezon** [comment]
Ok so I gather 4 people think nothing needs touching and 3 people think something could be done. So I am closing again :P

**Comment by Jundiyy** [comment]
I'd also leave it as is, the Dozer has been given something quite beneficial. I know this doesn't exactly fit here but with the earlier door times, it's possible it helps China get something out earlier which will deny the early aggression and then snowball. This would need games to prove though.

If we went with something, I wouldn't do a 50% armour boost, rather 2 extra standard rockets.

For now, I'd rather not.

**Comment by MTKing4** [comment]
I think 50% isn't that many rockets is it? Since it already have so little hp, could be like 4 rockets max, maybe less

**Comment by KrewGR** [comment]
Out of the 3 main factions, by far the China dozer is the worst.

Even with an army around it, is so weak and so immobile that it's highly likely you will get the dozer hunt on first try when looking for it. 

China dozer should get the backwards movement at least.

EA had zero intention of the sell CC meta.

**Comment by commy2** [comment]
> Out of the 3 main factions, by far the China dozer is the worst.

And there is no problem with that. Factions have their strengths and weaknesses.

**Comment by xezon** [comment]
China weaknesses mostly :P
