### ISSUE TITLE
Enable USA Comanche to shoot on air targets

### ISSUE THREAD

**Issue by KrewGR** [TheSuperHackers/GeneralsGamePatch#1209]
Hear me out on this one. 

USAs vs Air becomes dramatically better with this one change.  Air vs Air becomes more diverse. 

Now USAs can do the usual 3-4 MD drop PLUS the attack helicopter, and be able to do some eco damage to the Air Gen. 

**Attack Heli vs Lix**: Bunker lix still dominates, so I doubt it would make anything change on that front.

**Attack Heli vs Migs and Jets**: attack Helis are too slow, but there is a cool strategy where you can predict where the jets will go, especially vs those crazy alpha arouras, and set them up in the predicted flight patch to maybe get a kill.

**Attack Heli vs Attack Heli**: This is just cool to think about.

**Vs GLA**: Not affected.

**Comment by xezon** [comment]
Duplicate of 
* #463

**Comment by KrewGR** [comment]
It's not a dupe. This isn't about the china lix, it's about the USA attack helicopter to balance out SW/laser/USA vs air

**Comment by ExiLe-ZH** [comment]
Bit hard to predict how it would affect different matchups. 

Like AFG can use his superior Commies to harass other USAs aswell now (which could be a big thing in team games). Don't underestimate the power of the MachineGuns when used in mass. 

Commie vs Commie battles becomes a thing, which totally changes AFG mirror. Commies probably become a better overall choice in AFG mirror, maybe even better than Raps right at gamestart?

Before (Gat)lixes were used to guard bases against Commies in teamgames, 1 or 2 were enough provided China could keep Raps out of his base, cause that was only way for AFG to deal with Lixes. Now mass Commie can easily own them themselves.

**Comment by xezon** [comment]
Changing this seems very risky, as it makes USA Airforce General even better.

**Comment by ExiLe-ZH** [comment]
I see more pros for AFG than other USA's with this change. Since it's such standard unit, while for USA they aren't.

**Comment by xezon** [comment]
Close this?

**Comment by ExiLe-ZH** [comment]
Yea, don't think it will improve army balance in any way.

**Comment by KrewGR** [comment]
Then just increase price for air commancees. At the moment, Air is grossly powerful vs all other usas, especially SW. There are not many options to balance it other than much slow PDL.

**Comment by xezon** [comment]
Tweaking prices is something we can do very late. No need to do now.

**Comment by KrewGR** [comment]
then we should test the commancee changes to see if it might be needed first before we just write this off and close it. If we keep calling every balance change "too controversial" this thing will never get done, and if it does, the changes will only be bug fixes and nothing else.

**Comment by ExiLe-ZH** [comment]
Looking at core mechanics first is best approach indeed, after that we can determine what the value is of the unit.

Unless there are discrepancies, like VRaptor being more expensive than KRaptors, in such case it's fair and safe to match prices with the superior counterparts, imo.

**Comment by Jundiyy** [comment]
> If we keep calling every balance change "too controversial" this thing will never get done, and if it does, the changes will only be bug fixes and nothing else.

This is the aim of the patch, by fixing all bugs and see what changes this brings. And other small changes (might not be noticeable) which could help, at the same time, trying to keep the game as original as possible. Then after this, if we can't get good balance, we can look at bigger/controversial things. Something which is closed for now doesn't mean it will be closed after, it can be brought back up.

A bug fix, for example, Helix repairing at 100% rather than 50%. This should help already, how much? No idea, but it's a start and it will mean in them cases where a Helix is trying to get away on low health but doesn't, it might actually make it.

A small change (might not be obvious), as an example, could be the CC and WF door times for China, they were very long in comparison to USA. This means the 2nd Dozer will be built faster, 2nd Supp and Truck will be faster, 2nd WF (or Airfield) will be faster and also the first unit from the 2nd WF or AF. And also, every unit that comes out of the WFs will be a bit faster overall since WF door time has also been reduced.

**Comment by xezon** [comment]
We do not intend to change USA Comanche attack behavior at this point. There are more subtle ways to tweak them:

* #1530
* Decrease cost

We do however have an experimental Pull for allowing Helix Gatling to shoot on air units:

* #1093
