### ISSUE TITLE
Neutron Mines are underused; Normal Mines can help better against early GLA agression

### ISSUE THREAD

**Issue by ReLaX82** [TheSuperHackers/GeneralsGamePatch#1250]
Neutron Mines take long and also add another 500 to the usual mines.

Without having the exact times in mind, i think it is 600/30s for normal mines and 500/40s for neutral mines, correct me if I am wrong.

It all comes down to what is beeing buffed for China vs GLA in the end.
Still reducing the price and build time can be a good option against early GLA harassment.

Currently, thinking about all the other changes up to today, I would vote for:
--> Normal mines for $500/-30% and neutron mines $400/-40%

**Comment by commy2** [comment]
$600/20sec, $500/25sec are the actual numbers.

**Comment by ExiLe-ZH** [comment]
I agree the total investment to get Neutron Mines is way too high. I rarely see them, let alone pay off in games. 400 on top of the standard mines (a total of 1000) sounds a little better to me. 

600 for standard mines is fine though, stopping a TT pays off big time, you're saving your building and the TT investment is more than 600.

The buildtimes are more problematic, it delays production quite a bit and putting Mines on Supply Centers messes up Truck collection (which hopefully can be fixed with this patch). Shaving this down to 16 seconds would be better, this is the same as  Tank/Nuke BMs. Gats for example build a little faster at 14 seconds in 1.04.

**Comment by xezon** [comment]
Luckily they are not used much.

**Comment by ExiLe-ZH** [comment]
Because it's too expensive and takes too long to build. $1100/45s per building. 

Wouldn't be so bad if you saw Neutron mines used a little more. Maybe it should cost 300 and even shorter BT, something like 10-12s. That'd still be a total of $900/26-28s if normal mines are $600/16s.

**Comment by commy2** [comment]
They are also one shot kills. Don't buff them in any way.

**Comment by Stubbjax** [comment]
Definitely agree with reducing the research time of mines by 4 or 5 seconds. It would help shift the balance from predictive play to reactionary play. Summoning mines on top of Humvees / super Techs is incredibly rewarding / exciting, but is far too difficult to pull off and often comes down to luck rather than skill.

**Comment by ExiLe-ZH** [comment]
It's perfectly avoidable for the opponent to step on your mines. Yes, it happens frequently, even sometimes on higher levels, but those are mistakes nevertheless.

It's currently just not worth to invest $1100 and lose 45s on production buildings. 

Even when you're hunted and want to protect your production against TTs, getting normal mines can be detrimental at the same time, because it delays your production and all you can do is spam to win while being on a timer, every second you lose decreases the chances of winning.

**Comment by xezon** [comment]
If a Neutron Mine clears a valuable unit however, then it could be pretty good. It is not something that happens often in regular matches.

**Comment by Stubbjax** [comment]
How many units is an opponent likely to drive over neutron mines anyway? Typically once one or two units have made that mistake, not too many others follow suit, so its value is limited.

**Comment by Jundiyy** [comment]
Mines could do a with time decrease and Neutrons with a price and time. Most of the times it's a one-off benefit, unless the opponent forgets. Quite expensive for that reason and also quite time consuming.

The other benefit that mines give is that players will not send units past that building, so they are temporarily held back.

**Comment by ExiLe-ZH** [comment]
Honestly would make the game more fun and dynamic to see cases like China 'stealing' a Super Tech due to GLA's mistake.

**Comment by MTKing4** [comment]
The overall investment for Neutron mines is Practically `$1100@45s` Avoiding the misleading `$500@25s`

To Me it's not mines, it's upgrade on current mines, which shouldn't cost as much, and we only need to look at the overall investment not its cost

Therefore i think making it `$200@10s` is reasonable

Making the overall investment to `$800@30s`

So player has a choice between

1. `@600@20s` Normal Mines
2. `$800@30s` Neutron Mines

**Comment by xezon** [comment]
200 looks cheap. 300 maybe?

**Comment by MTKing4** [comment]
If it's proven too cheap then we can increase it yeah

**Comment by Jundiyy** [comment]
I think MTKing has a good point, which I didn't think about. It's an overall price package.

Paying $800 for (usually) a one off investment seems okay, you might get 1 unit or you might get a few. After that, in most cases you won't get any unless the player forgets. Then it becomes a barricade, not allowing units past the building. Helps with boxing in.

**Comment by ExiLe-ZH** [comment]
600@20 and 900@30 sounds good to me.

Or 600@18 and 900@30.

Production delay at 20 seconds still feels like quite a bit, sometimes you rather have an extra Gat or Dragon that only takes 14 seconds to build (13 with patch?) than betting on mines which might not even pay off. Shaving off 2 seconds improves it just a little bit.

**Comment by ReLaX82** [comment]
Thinking twice about it Neutron mines must be easier accessible.

$600/20sec, $500/25sec are the actual numbers as stated and 
$500/15sec, $200/15sec are good numbers to start with. I dont think Neutron mines are too OP that way as usual mines are already there and most likely known.

**Comment by xezon** [comment]
Most of us appear to agree that reduction, especially for Neutron Mines, are ok. Now we just need to determine good setup.

### Overview

| Mines                    | Cost   | Time  |
|--------------------------|--------|-------|
| Original Mines           | 600    | 20    |
| Original Neutron Mines   | 500    | 25    |
| Original Mines + Neutron | 1100   | 45    |

**Comment by ExiLe-ZH** [comment]
This would be my suggestion

| Mines                    | Cost   | Time  |
|--------------------------|--------|-------|
| Original Mines           | 600    | 20    |
| Original Neutron Mines   | 500    | 25    |
| Original Mines + Neutron | 1100   | 45    |
| - | - | - |
| Patched Mines            | 600    | 18    |
| Patched Neutron Mines    | 300    | 12    |
| Patched Mines + Neutron  | 900   | 30    |

**Comment by xezon** [comment]
What is the reason to decrease regular mines by 2 seconds? Do they build too long and if so how was this concluded?

**Comment by ExiLe-ZH** [comment]
It's the pros and cons of choosing between units and mines. With the decreased doortime units become more attractive, the 2 seconds are meant to offset and improve that slightly over 1.04 while staying safe.

Mines pros:
- Pays off well vs enemy mistakes, losing a TT is more costly.
- Cheaper than unit.
- Can protect Dozer with smart building positioning.

Mines cons:
- Kills rely on luck/mistakes.
- Builds much slower than most standard units (Gatt 13.3s, BM 15.3s patched). Player may fall behind in unit production when Mines don't pay off.

Unit pros:
- Mobile and much more versatile, offensively and defensively (Trucks and Dozers). Fighting/scaring away Quads, Techs etc.
- Player controlled, no luck factors.

Unit cons:
- Can be caught out of position and may not be able to stop TT. Could be either good play by opponent or mistake from the player.

Overall I'd say units are the better choice depending on the skill and style of the opponent.

**Comment by Jundiyy** [comment]
I did originally like MTKing's proposal, but I had a sudden thought, Inf Gen Bunker has free Mines, so Neutrons would be too cheap and fast. Although, I do otherwise still like the $800 price, or even $900.

**Comment by ExiLe-ZH** [comment]
Oh that's a good point indeed and quite an oversight. 

That said, why should Inf invest in Neutrons while the enemy is fully aware Inf Bunkers come with Mines? There's no gamble about it like other buildings and there are multiple ways to check whether the mines have expired already after clearing the Bunker.

It should not pay off.

We can make Neutrons $400 to be safe, but the fast Build Time should not matter in the Inf Bunker case, it makes zero difference since the opponent should be well aware of Mines in the first place.

**Comment by xezon** [comment]
I am also in favor of buffing Neutron Mines not as much for now. Cutting 100 cost and 10 seconds build time to effectively 400 cost and 15 seconds is already significant improvement. And we can leave regular Mines as is, because they appear to be ok, with many China players investing into them already.

**Comment by MTKing4** [comment]
> I did originally like MTKing's proposal, but I had a sudden thought, Inf Gen Bunker has free Mines, so Neutrons would be too cheap and fast. Although, I do otherwise still like the $800 price, or even $900.

Fair Point, then i think `$300@15` is better, and not to forget that inf bunker is more expensive so it's kinda already paying for the mines.

**Comment by ExiLe-ZH** [comment]
Alternative proposals for Neutron Mines:

1. Make the expiration time longer when the host building gets destroyed. Getting Neutrons can then be used as tactic to slow down the enemy offense. Could perhaps even make them last forever so that the enemy is forced to clear it and can not wait it out.
2. Make them invincible vs standard splash damage weapons. The enemy is forced to use Workers/Dozers to clear it.

**Comment by xezon** [comment]
> Make them invincible vs standard splash damage weapons. The enemy is forced to use Workers/Dozers to clear it.

I think that is too crass.

> Make the expiration time longer when the host building gets destroyed. Getting Neutrons can then be used as tactic to slow down the enemy offense. Could perhaps even make them last forever so that the enemy is forced to clear it and can not wait it out.

Interesting idea.

**Comment by ExiLe-ZH** [comment]
> > Make them invincible vs standard splash damage weapons. The enemy is forced to use Workers/Dozers to clear it.
> 
> 
> 
> I think that is too crass.

While still expiring ofcourse. Instead of invincible more hp vs splash damage could also work, would then take longer to clear it.

**Comment by MTKing4** [comment]
> Make them invincible vs standard splash damage weapons. The enemy is forced to use Workers/Dozers to clear it

I was going to propose this idea for normal mines a while back as well

**Comment by xezon** [comment]
Making it more difficult to clear mines will likely make it more frustrating for players to deal with them. Force firing ground to kill them is good for gameplay. No one would want to send Dozer to front line to start clearing mines...

**Comment by ExiLe-ZH** [comment]
Well you gotta have a Dozer/Worker nearby already if you want to clear it fast, by the time one arrives from across the map the mines would have expired already.

So you gotta be prepared, else the enemy successfully slowed you down.

But I agree the other idea sounds less "intrusive".

**Comment by ReLaX82** [comment]
Make mines stay longer will drastically improove or boost China. I would rather tweak price and builds.

**Comment by xezon** [comment]
> Make mines stay longer will drastically improove or boost China.

I agree with this sentiment. Changing mines will change too many dynamics and what player expects from mines.

**Comment by commy2** [comment]
Just leave as is. Both Landmines and Neutron Mines work out fine as they are.

**Comment by ExiLe-ZH** [comment]
> Make mines stay longer will drastically improove or boost China. I would rather tweak price and builds.

If it's just for Neutrons there will be more incentive to build them without having to chance price/BT. Currently there's 0 incentive to build them.

Normal mines I wouldn't touch too much, except for maybe reducing BT by 2 seconds, because with the new doortimes it's more attractive to just make units.

**Comment by ReLaX82** [comment]
Neutron mines are very rarely used.
Iirc it really is rare to even see them in game.
You have to spend a massive amount of money and time to get them.

If normal mines are once detected, the enemy is aware, which makes them even less useful.

At a minimum 3s less normal mines reduction and a significant reduction BT and price for Neutron mines.

It also blocks production of a WF.

**Comment by fastAiRR** [comment]
Neutrons should probably be an upgrade at the prop or maybe internet centre. Like 1k
