### ISSUE TITLE
Should Black Napalm Dragons perform better vs Tox Tunnels?

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#1269]
## Dragon Tank vs Normal Tunnel

| Dragon Tank Vet | Black Napalm   | Performance   |
| --------------- | -------------- | ------------- |
| 0 | no | Kill (~20% HP left) |
| 0 | yes | Kill (~30% HP left) |
| 1 | no | Kill (~35% HP left) |
| 1 | yes | Kill (~45% HP left) |

## Dragon Tank vs Tox Tunnel

| Dragon Tank Vet | Black Napalm   | Performance   |
| --------------- | -------------- | ------------- |
| 0 | no | Max ~60% damage |
| 0 | yes | Max ~80% damage |
| 1 | no | Max ~80% damage |
| 1 | yes | Max ~90% damage |

## Notes
1. This is the performance when no other units are shooting at the Dragon, with the perfect flamewall distance, the Tunnel facing the Dragon, the Dragon approaching vertically/horizontally and no Worker to help repair it.
2. Theoretically the performance should be better when approaching diagonally (faster) and from behind (Turret needs to turn) but I wasn't able to measure a difference.
3. When putting the flamewall slightly too far/close the performance easily drops by 20+%. 
4. In real games Tunnels are often covered by other Units/Tunnels. Popping a single unit last moment can still often save a Tunnel.

### Proposal 1

Increase Dragon Tank Armor against Poison.

### Proposal 2

Rotate Toxin Tunnel turret slower.

### Proposal 3

Add minimum attack range to Toxin Tunnel turret.

**Comment by Stubbjax** [comment]
I don't think `FLAME` damage should affect Toxin Tunnel Networks any more than it does regular Tunnel Networks. They all use `StructureArmor`, like most other buildings in the game, and changing this would require its own unique armour set and introduce a counterintuitive inconsistency. A cleaner approach would be to increase Dragon Tank resistance to `POISON` damage. I've tested this in the past and it works quite well.

Currently, Dragons take 25% damage from `POISON`. Reducing this to 20% could be a subtle and effective way to take some of the edge off of Toxin Tunnel Networks for all China factions. A reduction from 25% to 20% (a 20% reduction) could just be enough to get your ~80% and ~90% results over the line with critical health remaining. The resistance from other sources such as Toxin Rebels and Anthrax Bombs would also be a welcome bonus.
```ini
Armor DragonTankArmor
  Armor = POISON 25% ; Poison resistance in 1.04
End
```
Another idea: Have the turret rotate slower so that a skilled player can benefit more when approaching from the side / behind, and put more emphasis on correct rotation during building placement, or manual placement of Tunnel Defenders. If combined with the damage reduction, could maybe even allow an unranked, standard napalm Dragon to take out a Toxin Tunnel Network from behind, if there is no response from the opponent.

And Another idea: Give the toxin gun a minimum attack range, similarly to Toxin Tractors, where units that are too close cannot be fired upon, and some form of action is required from GLA in order to respond to threats. Could benefit terror techs as well. High-risk, high-reward!

**Comment by MTKing4** [comment]
Dragon tank already survives a tox bonb with critical health left in the Flame clearing toxin branch, so any buff to that will be welcomed indeed.

**Comment by Jundiyy** [comment]
Not a fan of it, Tox Tunnels are meant to be stronger.
We already nerfed Tox Stinger Sites by a lot, then gave Helix double health regen. Already 2 major points to China. Can't think of anything else from the top of my head.

**Comment by xezon** [comment]
> then gave Helix double health regen

this is not correct

**Comment by Jundiyy** [comment]
Oh, we haven't committed that yet?
In that case, I am a bit less against it but still stand by my first sentence. Tox Tunnels should be stronger.

**Comment by ExiLe-ZH** [comment]
@Stubbjax Funny, I just logged on  here to write about the poison resistance idea.

It can't hurt if Dragons perform just slightly better vs Tox Tunnels. 

It wouldn't be a Tox Tunnel nerf but a tiny survival buff for one specific China unit.

One of the biggest reasons Chinas struggle so much vs Tox is the fact that the options are so limited to clean up Tox Tunnels.

It would be fair if a BN Vet 1 Dragon was able to survive long enough to JUST take out a Tox Tunnel under **perfect conditions** (read notes in OP). It'd be a minimal change as it currently does 90% damage.

**Comment by ExiLe-ZH** [comment]
Current changes do nothing to improve Chinas vs Tox specifically and something needs to be done, because Tox's winrate is too high. 

Another off-topic improvement would be 750 Quads, same like Demo, that would make Lixes a better option vs Tunnels and Tox in general.

**Comment by Jundiyy** [comment]
Yea a small buff seems okay, vet 1 BN being able to just take out a Tox Tunnels.

Tox Quads are already $750?

**Comment by MTKing4** [comment]
Yes, $750 for tox and demo

**Comment by ExiLe-ZH** [comment]
Ahh yea, the difference was that Demo Quads have longer BT. Equalize this then.

**Comment by xezon** [comment]
Adding a bit more Poison resistance does sound reasonable to tweak this specific matchup.

Related issue:
* #917

**Comment by Stubbjax** [comment]
Here's a demonstration of a 20% `POISON` damage modifier applied to `DragonTankArmor`, rather than 1.04's 25%, following the environment variables listed in the issue description.

https://user-images.githubusercontent.com/11547761/192110854-a8dfc2f1-f5d9-43e5-a4b8-f16937f713a2.mp4

After the change, a Dragon Tank with Black Napalm is able to _just_ manage to kill a Toxin Tunnel Network from directly behind if the flame wall is correctly positioned, no Tunnel Defenders are present or extra damage is sustained, no repairing occurs, and both begin at maximum health.

**Comment by ExiLe-ZH** [comment]
Seems like a fair change. How does a Tank Dragon perform?

**Comment by Stubbjax** [comment]
Standard Napalm can _just_ succeed from the back - though it is a mutual destruction. It took about five attempts to achieve, so it's pretty situational. The reaction time of tunnels likely creates a lot of variance (seems like they might be checking for targets every ~500ms). Black Napalm can reliably _just_ succeed from the front.

https://user-images.githubusercontent.com/11547761/192126021-9573d49c-6170-4dd6-8137-b60215f38e14.mp4

**Comment by xezon** [comment]
From what I can observe the effect of the change is that Toxin General now also needs to react to approaching Dragon Tank on Tunnel like the other GLA Factions. Toxin Tunnel still is significantly better than MG Tunnel, as it kills Infantry instantly and also deals more damage to vehicles. Such change looks logical to me.

**Comment by MTKing4** [comment]
From what i can see now Vet1 Dragon tanks without upgrade are the bare minimum to killing a toxin tunnel somehow, and a vet0 will still die, therefore this is a direct buff to Tank Vs tox Match up, which is a needed one. Agree with the changes.

**Comment by MTKing4** [comment]
Still, would be interesting to see how a vet0 dragon tank fare, with and without upgrade

**Comment by ExiLe-ZH** [comment]
>  The reaction time of tunnels likely creates a lot of variance (seems like they might be checking for targets every ~500ms).

Ahhh, then my test results might not be entirely accurate, I tested by forced firing.

**Comment by ReLaX82** [comment]
> From what i can see now Vet1 Dragon tanks without upgrade are the bare minimum to killing a toxin tunnel somehow, and a vet0 will still die, therefore this is a direct buff to Tank Vs tox Match up, which is a needed one. Agree with the changes.

Agreed!

**Comment by MTKing4** [comment]
> Here's a demonstration of a 20% `POISON` damage modifier applied to `DragonTankArmor`, rather than 1.04's 25%, following the environment variables listed in the issue description.
> 
>  TOXNET.mp4 
> After the change, a Dragon Tank with Black Napalm is able to _just_ manage to kill a Toxin Tunnel Network from directly behind if the flame wall is correctly positioned, no Tunnel Defenders are present or extra damage is sustained, no repairing occurs, and both begin at maximum health.

We need a PR for that
