### ISSUE TITLE
Select next unit with tab

### ISSUE THREAD

**Issue by farkascsanad** [TheSuperHackers/GeneralsGamePatch#1409]
I think its a very good QOL if we have an option to select though selected or control grouped unit with tab.
Eg: 
selected 5 md, tab select 1st one laser lock, tab -> laser lock hotkey ->click etc.
its still need good micro, but i think its really good aoe has it and its awsome.

The other thing to able to move alt click to shift click :$  and able to shift build buildings

**Comment by commy2** [comment]
Can you elaborate on what "select though selected" means? I have a hard time imagining this.

**Comment by farkascsanad** [comment]
https://youtu.be/mK_O_Y9nXm8?t=57
in the video he go though idle units but in my case it cycle though selected units eg:
group of MD-s ctrl group 1 :
ctr1 [MD, MD, MD]
I hit 1 -> selected all 3
I hit tab -> selected one of them [MD]
I hit tab again -> select another md of the 2 reaming md
hit again select the last one
hit again select the first again.


same for buildings eg hotkey for arms dealer and barak:
https://youtu.be/mK_O_Y9nXm8?t=30
and if you hit it you select them 1 by 1 each hotkey hit. So you can spam in late game easly.

something similar improve alt movement, currently we can only give waypoints, but it would be a great QOL if we can add attack seqence eg: i attack this unit then alt click an other. the unit will focus the 2nd unit after the first one destroyed.

idk if the engine let these happens, but if yes those are huge QOL imo

**Comment by xezon** [comment]
TAB key will open Diplomacy Screen.

**Comment by ExiLe-ZH** [comment]
Pretty nice idea, but tab is indeed occupied already by the diplomacy screen, which can be pretty important. Perhaps it could replace the normal ctrl+left/right-arrow functions as these aren't used by anyone I don't think, this is a similar but more useful feature. Basically the only difference is that instead of scrolling through all your individual units, you scroll through the units of a group. Problem is this key combination might not be very accessible. Otherwise CapsLock could be a candidate.

Pretty sure this can only be done through Thyme though.

**Comment by xezon** [comment]
This is a feature request that is not within the (current) scope of this project.
