### ISSUE TITLE
1- GLA scrap 2- Superweapon

### ISSUE THREAD

**Issue by ISKO-1997** [TheSuperHackers/GeneralsGamePatch#1424]
1- in GLA when you  kill your own unit there's no scrap !
2- when you use superweapon no damage to unit above the superweapon !
,,,,,

**Comment by ExiLe-ZH** [comment]
It's totally worth to kill your own stuff to get a Super Tech or Super Marauder, wouldn't be fair.

**Comment by ISKO-1997** [comment]
sorry , what is that mean exactly ,Super Tech or Super Marauder ?

**Comment by xezon** [comment]
I do not understand point 2.

**Comment by ExiLe-ZH** [comment]
> sorry , what is that mean exactly ,Super Tech or Super Marauder ?

Super Tech = Technical with rocket launcher
Super Marauder = Marauder with double barrel 

Those are very powerful game changing units.

**Comment by ISKO-1997** [comment]
![shot_20221104_193300_12](https://user-images.githubusercontent.com/117390423/200028295-3140684e-ee7c-413b-bcb4-29dc88cf4b0f.jpg)

**Comment by xezon** [comment]
1. As Designed. Friendly kills do not give rewards. No Scrap, No Veterancy, No General Promotions.

2. Could be either way indeed. Is not clear if technically possible. Adding damage to first beam could damage the Superweapon structure itself. From Gameplay perspective this would be odd, as USA player would now need to take extra care when launching Superweapon, which could lead to frustrating results otherwise. The same principle would then have to be applied to SCUD Storm and Nuke Silo, which would make it more complicated.

Closing.

**Comment by ISKO-1997** [comment]
Thank U xezon ,,

**Comment by xezon** [comment]
Thanks you for participation.

**Comment by ExiLe-ZH** [comment]
Imagine the Nuclear Missile hitting a Cargo Plane, big USA tactics++++ :joy: :joy:

**Comment by xezon** [comment]
Omg. 100% Uninstall. Disk to Trash.
