### ISSUE TITLE
GLA Stinger Soldier can be killed by Quad Cannon, but not by Gattling, Humvee, Comanche

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1582]
GLA Stinger Soldier cannot be killed by Gattling, Humvee, Comanche, et al. But it can be killed by Quad Cannon.

```
Armor StingerSoldierArmor
  Armor = GATTLING          0%      ;NOT vulenrable to gattling fire.
  Armor = SMALL_ARMS        100%    ;Vulnerable to normal small arms fire.
  Armor = COMANCHE_VULCAN   0%      ;invulnerable to 20mm cannon fire from the Comanche
```

This looks to be intentional setup due the unique comments, but is this optimal setup? Perhaps GATTLING and COMANCHE_VULCAN should deal some damage? Or SMALL_ARMS should deal none as well?

**Comment by MTKing4** [comment]
Maybe remove from quad as well would be better, but we still have more units who can do this, like snipers, burton i think, jarmen and flash bang (which we removed)

**Comment by ExiLe-ZH** [comment]
Commie should absolutely not be able to kill the crew, would be a major unnecessary buff.

Gattling could be considered, would make it easier for china's to push through gla strongholds.

Why was flashbangs removed?

**Comment by xezon** [comment]
> Why was flashbangs removed?

* #636

**Comment by penfriendz** [comment]
Should a gattling *tank* be able to kill stinger soldiers? Imo, absolutely. Should a helix with a gattling be able to? Not sure.

**Comment by ExiLe-ZH** [comment]
About the Gatlix ability to kill Stinger crews,

First of all, I think it makes sense since the Gattling guns (aswell as the Quad Cannon guns) are supposed to be bigger and more powerful than the Comanche or Humvee machine guns.

Secondly, GLA Strongholds are harder to defeat for China than AFG. AFG Commies can attack fast and unannounced and has a variety of units with PDL's to block Stingers (or even more effective Pathfinders in Combat Chinooks). Airforce also has Carpet from level 1 or 2 to help clearing such positions. This new ability could help China in two scenarios as I see it.

The first scenario is early-game, where two common China builds are the Gatlix Dragon drop (2 supply & WF+AF) or all-in Bunker+Gatlix rush. Stingers will a be a lot less effective vs these two builds. 

The second scenario is the mid-game Lix spam strategy. I don't think it will make that much of a difference here though, one extra Gatlix means you have one less Bunkerlix, which overall is more effective vs GLA mid-game. I suppose with some micromanagement you can clear Stinger positions faster if you specifically order the Gatlix to clear the Stingers, while the other Lixes target more important structures.

MTKing's proposal could also be an approach, however it would make GLA mirrors even more campy.

**Comment by xezon** [comment]
It is possible to adjust amount of damages. And while Stinger Soldiers take damage, then structure itself takes no damage.

**Comment by MTKing4** [comment]
I don't really like the idea of balancing the factions by rendering a defensive building useless just to buff chinas, i think there are other better ways to do that, but still, china has ways to kill occupants of stinger, with Dragon tank, Mig Strike, Inferno Cannon and Napalm bomb for helix which will be cheaper than a Gatling gun and serving the same purpose, especially after our recent buff it should get more usage, there's no reason to give it to Gatling guns as well

**Comment by MTKing4** [comment]
This shouldn't be closed, we either remove the ability from quads or add it gatlings, and i favor the former, current state is not desirable
