### ISSUE TITLE
China Tank Battlemaster with Autoloader upgrade deals less damage per shell than without upgrade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#1709]
China Tank Battlemaster with Autoloader upgrade deals less damage per shell than without upgrade.

Raised by Stubbjax here: [#1704](https://github.com/TheSuperHackers/GeneralsGamePatch/pull/1704#issuecomment-1428990773)

`BattleMasterTankGun` deals 1×60 damage per 60 frames and `Tank_BattleMasterTankGun` deals 3×40 (120) damage per 92 (16 + 16 + 60) frames. Note that the 500ms delay between each shot in the clip translates to 533.33ms and thus 16 frames.

| Upgrade     | Damage | Fire Rate | DPS   |
| -           | -      | -         | -     |
| None        | 60     | 2000ms    | 30    |
| Nationalism | 60     | 1600ms    | 37.5  |
| Autoloader  | 120    | 3067ms    | 39.13 |
| Both        | 120    | 2400ms    | 50    |

It would be nice if individual Tank Battlemaster shells would always deal same damage. Because that way damage is way more plausible than if 3 shells deal somehow less damage than expected, even if overall damage output over time is increased compared to the regular 1 shell firing.

**Comment by xezon** [comment]
## Proposal 1

Raise Autoloader damage per shell to 60 and adjust DelayBetweenShots and ClipReloadTime accordingly to preserve original DPS.

| Weapon                           | PrimaryDamage | Delay | ClipSize | ClipReloadTime | DPS   |
|----------------------------------|---------------|------ |----------|----------------|-------|
| Original BattleMasterTankGun     | 60            | 2000  | 0        | 0              | 30    |
| Original Tank_BattleMasterTankGun| 40            | 500   | 3        | 2000           | 39.13 |
| Patched Tank_BattleMasterTankGun | 60            | 650   | 3        | 3250           | 39.27 |

### Original - PrimaryDamage 40


https://user-images.githubusercontent.com/4720891/218844251-f5c5ac68-a629-4370-a483-fbc38fabf9b9.mp4

### Change - PrimaryDamage 60

https://user-images.githubusercontent.com/4720891/218844166-c43fa408-98be-43c1-a9e6-f6b17b091bde.mp4

**Comment by xezon** [comment]
Maybe not a good idea. Not sure. It creates small discrepancies of DPS with various other weapon bonuses, so likely will not be possible to retain identical DPS.

**Comment by MTKing4** [comment]
This was intentional by design, there's no reason to change it

There's data to back this up in reality as well, tanks that behave exactly the same, shooting multiple rounds in a matter of seconds, but those shells tend to be smaller, therefore less damage, so it makes sense, don't change it

Examples:

HSTV-L Experimental US Light Tank:
![Screenshot_20230217-154334_Quora](https://user-images.githubusercontent.com/83613147/219656628-0863285f-f60e-47b2-bf68-0845d7ce630f.jpg)


And Swedish S-tank Stridsvagn 103:
![Screenshot_20230217-154346_Quora](https://user-images.githubusercontent.com/83613147/219656672-3eb54ad7-25eb-4b7c-958e-5227cee34af1.jpg)
