### ISSUE TITLE
Discuss whether or not China Tank Emperor Subliminal Messaging bug should be fixed

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#21]
Discuss whether or not China Tank Emperor Subliminal Messaging bug should be fixed.

**Comment by commy2** [comment]
Here is how the fix could look like: https://github.com/commy2/zerohour/commit/b96fa2201410a5946d7ea5c9448a4644ab929376

I personally vote for fixing this. The Emperor is really underpowered to the point that it's better to just spam Autoloader Battlemasters. And the Emperor does have the same starting health and damage output as a regular v China Overlord.

Fact: a vet 3 Emperor loses in a 1v1 vs a vet 3 Subliminal Messaging Prop Tower Overlord DESPITE THE GATLING GUN, because it shoots and heals slower. It's worse in every way compared to the Nuke version too obviously.

Also consider that Tank has to pay and wait extra long for a Prop Lix to heal the army.

**Comment by xezon** [comment]
Interesting. Always thought the Tank Emperor is stronger than the Overlords.

**Comment by commy2** [comment]
It's perks are a free tower and $100 less (so a total $600 saved) and vet 1, but as far as raw stats go, it's an exact copy paste. (Again, same weapon and health.)

**Comment by ReLaX82** [comment]
Fix it, as its broken. Puts more options to Tank gameplay.

**Comment by RisingZH** [comment]
Fix

**Comment by xezon** [comment]
There was a poll in Discord and it seems consensus is pretty clear on this fix. Let's do it then!

**Comment by Madrageeeeee** [comment]
Only wonder how this will affect lategame tank vs usa(s). Ecm emperor might become very difficult to kill. But perhaps worth a try and will make the emperor more viable i guess. 

Also might help in balancing lategame tank vs nuke a little bit

**Comment by xezon** [comment]
Fixed.

**Comment by ReLaX82** [comment]
I think having an Emperor as a better unit is worth a try as its rarely used in 1on1 anyway as BM/Gat/ecm combo with hord Bonus is better.
