### ISSUE TITLE
Chine Artillery Barrage can be destroyed with a China Nuke missile

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#221]
Chine Artillery Barrage can be destroyed with a China Nuke missile. Reported by Goldfish.

**Comment by Jundiyy** [comment]
It has health, that's why. Never done the flowing but I'd presume Particle Cannon can also. Maybe a perfect Aurora hit, Fuel Air Bomb.
It's just more common with Nuke because you combine both together a lot of the time and players don't time it right.
It's like using Artillery on your Carpet Bomber, damages it.
