### ISSUE TITLE
GLA Structures repair at 75% with Fortified Structure upgrade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#228]
GLA Structures repair at 75% with Fortified Structure upgrade. Is this as designed?

**Comment by commy2** [comment]
Seems like an oversight, because this only happens because the DEFAULT damage type is set to 75%. 

Since healing and repair is a special damage type in engine that does "negative damage", and that damage type is undefined in every armor set, DEFAULT also reduces the healing rate.

On the other hand, this is exactly what would happen if the bonus was a health bonus instead of an armor bonus.

**Comment by xezon** [comment]
How much more armor does upgrade give?

**Comment by commy2** [comment]
These values
https://github.com/xezon/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginal/Data/INI/Armor.ini#L562-L611
are overwritten with these values:
https://github.com/xezon/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginal/Data/INI/Armor.ini#L613-L662

**Comment by Jundiyy** [comment]
As mentioned on Discord, I would say to keep them values the same as it would make change tech based games. GLA would have an even bigger chance to survive.

**Comment by xezon** [comment]
With DEFAULT at 75% would that mean that some weapons deal more damage after the upgrade? If yes, which?

I am skeptical about touching this, because it would help GLA to repair a Palace under fire, or a SCUD Storm that gets bombarded with planes or General Promotions. Faster healing will make it harder to kill this if a worker is nearby ready to swing his precious hammer.

On the other hand, having this undocumented side effect is not satisfying either.
The least we should do is append this side effect to the tool tips (all languages).

**Comment by commy2** [comment]
> With DEFAULT at 75% would that mean that some weapons deal more damage after the upgrade? 

No, less. 25% less. Every damage type that is not listed otherwise. E.g. `MOLOTOV_COCKTAIL`, which is used for the Angry Mob Pistols, Rocks, Mollies and AK47 alike (despite the name).

The repair could be edited by just setting `HEALING` to 100%. That wouldn't touch any other damage type.

**Comment by MTKing4** [comment]
[Fortified Structure slow repair.zip](https://github.com/xezon/GeneralsGamePatch/files/7112127/Fortified.Structure.slow.repair.zip)

here's a real-life example replay of this upgrade issue affecting the outcome of a competitive game, worth analyzing

SPOILER NOTE: Check the palace at the bottom of the map in the end

**Comment by xezon** [comment]
Maybe it could also be tweaked by increasing HEALING to normal level and reducing the ARMOR values a bit.

**Comment by Jundiyy** [comment]
Changing armour values makes a difference so there is a lot to be tested in that case, tooltip would probably be better. A bit like the Crusader armour example I gave in discord.

**Comment by RisingZH** [comment]
I would be careful with changing this, would be quite impactful to gameplay (trying to kill a palace which is being repaired being the main example).

It does seem somewhat logical/realistic that a fortified structure would take longer to repair than an unfortified one.

**Comment by xezon** [comment]
> It does seem somewhat logical/realistic that a fortified structure would take longer to repair than an unfortified one.

Hmm. Which raises the question how does the Armor Healing per Second change? If a Fortified Structure has more health, then it indeed makes sense that it would also take longer to heal it, because it has more Armor.

**Comment by ImTimK** [comment]
2500HP just makes no sense... AT ALL. With hackers it's worth like $8k! 
Not only are you losing this huge investment when it gets destroyed, but in most cases also a big chunk of future income, so the damage is much greater (multiplied a few times probably).

3000HP sounds more reasonable to me as it would be the same as the Strat Center with Hold the Line or a Palace without Fortified Structures.

And that's still relatively weak, like an Arms Dealer already has 2000HP, with Fortification that's 3000HP?

**Comment by ZekeDlyoung** [comment]
Changing armor values are probably not needed, just the HEALING 100% if ever, but yeah this change would probably be down to public vote in the future

Also the title is misleading, repair speed is 25% slower not 75% :P

**Comment by ExiLe-ZH** [comment]
There's no need to change this, it's a 'problem' under the hood that barely anyone knows about anyway. It's good as is because Scudstorms and Palaces are already tough to take down and there's no need to make that any harder/give GLA any such buff.

It might have been a coding mistake but gameplay > code logic.

**Comment by xezon** [comment]
Given the lower healing rate, how much of an improvement is the Fortified Structure upgrade? In INI script we may at least put the HEALING parameter at 75% to make the behavior explicit and documented.

**Comment by commy2** [comment]
Fortified Structures is a really good upgrade for GLA lategame. For example, it protects Markets against genpowers. The lower healing rate does not matter in my opinion, because the buildings also take longer to tear down.

Would not change. Putting in the HEALING 75% into the armor sets would be good though. Just to make the current behaviour explicit.

**Comment by ExiLe-ZH** [comment]
> Given the lower healing rate, how much of an improvement is the Fortified Structure upgrade? In INI script we may at least put the HEALING parameter at 75% to make the behavior explicit and documented.

FS gives buildings very good protection vs everything (+ ~50% HP) and it's pretty much mandatory even if it were twice or triple the price.

Boosting repair rate effectively means buildings will get more hp, because it will take longer to take them down while being repaired. 

The worker is hard to touch without airsupport/artillery when it's behind the building and pro players will _always_ have workers nearby key-buildings or have quick reaction sending substitution.

**Comment by xezon** [comment]
Ok. Let's add the HEALING 75% then and close this report afterwards.

**Comment by ZekeDlyoung** [comment]
No need to add the HEALING 75% unless you plan to remove the DEFAULT 75% from the armor, just leaving it alone is fine

Last suggestion, which is more or less a reverse of what I said earlier, maybe for the sake of just fixing the bug but maintaining the status quo, we can fix the repair speed, and adjust the FS armor values so things more or less stay the same.

Might seem pointless, but could be worth doing it to avoid possible complications in the future :shrug:

**Comment by ZekeDlyoung** [comment]
Yeah perhaps just remove DEFAULT 75%, and all the specific damage types reduced to 75% including HEALING 75%
