### ISSUE TITLE
Add hotkey for Sell.

### ISSUE THREAD

**Issue by Kesanov** [TheSuperHackers/GeneralsGamePatch#240]

**Comment by ExiLe-ZH** [comment]
You can already do that yourself currently

**Comment by Kesanov** [comment]
So every single person should learn to modify big files, in order to set a missing hotkey?

**Comment by xezon** [comment]
This needs a higher level decision first. We are not clear yet if we touch hotkeys at all. Hotkey design currently is very complicated, because we have no good tools and there is a multitude of languages with mismatching Hotkey setups. The best solution would be to give user a good tool to edit hotkeys. And in patch loader we can allow user to download hotkey sets as Addon. I will close this for now.

Thanks for reporting.
