### ISSUE TITLE
Satellite Hack I does not work reliably

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2416]
Satellite Hack I does not work reliably. It turns on and off at random on a new Command Center build after Sat Hack I research - both during construction and after construction of the Command Center.

Somehow we broke it.

* Introduced with #791

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/4720891/2066621f-cb00-4b11-8067-443589b11d12

**Comment by xezon** [comment]
Does not happen vs AI China. Edit: Likely because AI does not rebuild the Command Center after Sat Hack I was researched.

Happened vs GLA Human.

**Comment by Float1ngFree** [comment]
Can confirm that unfortunately the previous fix/change does not work reliability even vs bots. I went further and added FS_SUPPLYCENTER as well (for Cash Hack).

Sometimes it reveals the new scaffolds, but most of the time - not.

I don't think that there was something that broke it - it wasn't working consistently from the start. Better than original for sure, but not reliable. It was easier for me to spot because of the supply centers.

**Comment by xezon** [comment]
Adding FS_SUPPLYCENTER to test is a good idea. Can kill AI Supply Center, then wait for it to rebuild. I wonder if other Mods have attempted to fix this problem too and perhaps have working solutions (NProject, Rise of Reds, Shockwave).

**Comment by Float1ngFree** [comment]
Same thing with capturing bot's supply & selling - in most cases you don't see the new one he rebuilds.

I've tried playing around with `DelayBetweenShots` for SatelliteHackOneDummyWeapon (5s instead as vision remains for a bit), as well as with OCL's lifetime but to no success.
