### ISSUE TITLE
GLA Demo particle effects performance degradation

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#2425]
> I've noticed that there's a continuous effects performance degradation the longer the game goes vs demo. Some visual & transition effects stop displaying the more demo units you kill & the more explosion they produce. I've tried playing with ParticleSystems `Priority` - changing from `CRITICAL` & `WEAPON_EXPLOSION` to `DEATH_EXPLOSION` but that didn't solve the issue. 

> Seems like effects are accumulating and prevent other effects from displaying fully. Similar to when you have too many firestorms simultaneously.

_Originally posted by @Float1ngFree in https://github.com/TheSuperHackers/GeneralsGamePatch/issues/2311#issuecomment-2168126512_

**Comment by Float1ngFree** [comment]
Might be related to Demo_BombTruck explosions as `Demo_BombTruckDefaultExplosionTrail` and `Demo_BombTruckDefaultExplosionTrailSmoke` have `SystemLifetime = 0`.

It degrades the most when you hit a multiple units & structures with something big, like MOAB.  BombTrucks are usually at Demo's base. 

Also, I've noticed that most of the structures have multiple `SmolderingSmoke` & `SmolderingFire` effects which also have `SystemLifetime = 0` and become more flaky as effects accumulate. They should be tied to `ConditionState` changes, but they could be leaking...

Overall, I suspect that there are lots of minor leaks that accumulate and degrade the performance. As the game goes, the number of units/buildings can reduce, but the memory usage of the game only continues to raise with each killed/destroyed object.

**Comment by xezon** [comment]
It is a good lead. Can you download test map https://github.com/TheSuperHackers/GeneralsGameData/tree/main/Maps/Any/!TestAllFactions and build many units, kill them, and confirm the findings? If we narrow it to the specific unit(s), then we can go from there.

Bomb Truck did have a number of particle changes yes.
* #1137

**Comment by Float1ngFree** [comment]
I've run a number of tests and wasn't able to reproduce this on a test map. I guess this was due to overall laggy nature of original Twilight Flame (although I haven't seen it previously eat into effects) and maybe the matchup of Demo vs SW producing lots of effects.

This is what it looks like:

https://github.com/TheSuperHackers/GeneralsGamePatch/assets/17320562/0cbc325f-f4d3-4c97-8745-6883d4f32621

Memory wise both testing and the game above looked the same. Maybe you have any idea what this could be?
I've also uncovered an actual issue with structures' damage effects, I'll create a new issue for that later.

**Comment by MTKing4** [comment]
I've seen this before on large FFA games, tends to happen when there's too many particle effects on the screen, i suspect it gets highlighted with demo due to the fact that all the units of demogen generate extra effects due to the demo upgrade detonation effect

**Comment by xezon** [comment]
The evidence from the video implies that the particle pool is exhausted. It is possible that there are lingering particle instances that are never deleted. We need to isolate which they are and then look at their setup.

**Comment by Float1ngFree** [comment]
I'd say that this probably goes beyond the title of this issue and doesn't relate solely to https://github.com/TheSuperHackers/GeneralsGamePatch/pull/2311 -- the added effects are copies of existing ones and differ in size and colors mostly. Replacing them with original effect produces the same outcome. 

If I understand correctly, the `SystemLifetime` is the minimum number of frames the particleSystem should be executed, so that if it is less then `Lifetime` - it can be stopped & overridden by other effects. While if `Lifetime` < `SystemLifetime` - it is how many times the effect should be repeated (for example - TankFire). Correct?

**Comment by xezon** [comment]
I think `SystemLifetime` means life time of the `ParticleSystem` in frames, with 0=forever or bound to its owner. `Lifetime` means the lifetime of the effect(s) that the `ParticleSystem` creates.

In #1519 I have noted:

> In my understanding, `SystemLifetime = 0` is only ok if the parent object is short lived. If lifetime is uncapped, then particle will spawn every frame and live forever.

> On quick inspection, there are at least 2 suspicious effects:

> JetBurning
> WaterSpraySplash

I do not know if this is relevant for this issue. But my suspicion is that a `ParticleSystem` with `SystemLifetime=0` is at fault.

**Comment by Float1ngFree** [comment]
@xezon I've actually noted another thing I'm suspicious of - `BurstDelay`:

Quite a lot of effects have `99999` with a large number of `BurstCount`. I've played with numbers and it doesn't seem to affect anything. It would imply that it is a delay between firing each burst, but it doesn't seem to. 

Here is the test with two demo rebels, both using only `RedDonuteCloudLite` with `BurstCount = 75.00 75.00`, but one on the right (that is being killed) has `BurstDelay = 0.00 0.00`, while the left one suicides with  `BurstDelay = 99999.00 99999.00`


https://github.com/TheSuperHackers/GeneralsGamePatch/assets/17320562/a0e5cfb0-c23d-4439-9bfa-ee7c41983af9


I can't tell any difference (apart from Suicide hit effect).
I then went to game and played vs Demo and haven't noticed any effect degradation! 

In some of your changes, I think for tanks muzzle effects, you've changed it from 99999 to 0 quoting `BurstDelay = 0.00 0.00 ; Patch104p @tweak from infinite to spawn more than one puff` -- have you observed any actual change?

**Comment by xezon** [comment]
`BurstDelay` is min..max frame delay until next particle burst.
`BurstCount` is min..max number of particle spawns on this frame burst.

`BurstDelay=99999` means that we have an initial particle spawn, and then wait 99999 frames (3333 minutes) until the next spawn - if the particle system remains alive.

**Comment by Float1ngFree** [comment]
> `BurstDelay=99999` means that we have an initial particle spawn, and then wait 99999 frames (3333 minutes) until the next spawn - if the particle system remains alive.

So basically 99999 is meaningless, effectively 0, correct?

**Comment by xezon** [comment]
`BurstDelay = 99999` means that effect will effectively spawn once. I think it is synonymous for `SystemLifetime = 1`

**Comment by Float1ngFree** [comment]
Thanks for explanations.
Well, then that's out of the way... Must be something else.

**Comment by ThePredatorBG** [comment]
I think the game skips particle effects by taking into account all of them on the map no matter if they are in player's view or not. That's what could be causing it, especially if the particle cap is set to a low number.

**Comment by xezon** [comment]
I have now tested Demo General, building very many Bomb Trucks, Scud Launchers, Quads, Scorpions, Bikes, Busses, RPG, Mobs, Terrorist, etc, then shooting, suiciding them. I have observed no performance degradation or particle issues.

@Float1ngFree 
Please upload a replay where the issue occured and note the commit hash you used for it.

**Comment by xezon** [comment]
Any updates on this?

**Comment by Float1ngFree** [comment]
@xezon sorry I was out for a while...

I'd say that from my side this could be closed - I wasn't able to confirm this happening again, probably this was due to small particle cap. It is an old game and despite some effects being exceptionally well done, the less of them happens - the better.

So I'd say it's not related to the new Demo kill effect - it is actually smaller and less resource consuming than suicide explosion. It was probably due to a number of effects overall on my local setup.

**Comment by xezon** [comment]
I think what we can do is review the particle priorities, if they are all setup well. It is a bit odd that the moab core explosion does not show up but smaller particles do. We already have a task for this with #2225
