### ISSUE TITLE
Investigating INI Configuration and Understanding Specific Entries

### ISSUE THREAD

**Issue by DevGeniusCode** [TheSuperHackers/GeneralsGamePatch#2570]
I am working with INI files and trying to understand how various configuration entries work. For example, I encountered a line like:

`INPUTCALLBACK = "GameWinBlockInput"`

I am trying to determine how such entries are processed, where to find the corresponding functions or activations in the code, and what they do. I have searched for these terms in the repository, also in Thyme, but I haven't found any relevant results or references.

Can anyone provide insights on how to trace and understand these configurations or similar entries in the INI files?

**Comment by xezon** [comment]
Code related to that is not yet present in Thyme. You would need to guess the purpose by studying how it is defined in WND.

To me it looks like these INPUTCALLBACK specify where the mouse and key inputs are going to in the UI Window stack, so that inputs do not arrive on the wrong things.

A lot of the Window flow and functionality lives in Code and the WND's 'just' allow to edit parameters and add the simple widgets (texts, buttons, ...).

This is not an issue report, so I will close it. Please reach out to my name in Discord and I will add you to our private Server, where we can discuss about topics like this :)
