### ISSUE TITLE
Investigate GLA Toxin Terrorist issue, where they kill themselves instead of applying the suicide damage

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#30]
When GLA Toxin terrorists suicide in groups, they can potentially kill themselves instead of applying the suicide damage to the area.

Related Terrorist issues:
* TheSuperHackers/GeneralsGamePatch#26
* TheSuperHackers/GeneralsGamePatch#31
* TheSuperHackers/GeneralsGamePatch#30
* TheSuperHackers/GeneralsGameCode#37
* TheSuperHackers/GeneralsGamePatch#502
* TheSuperHackers/GeneralsGamePatch#503
* TheSuperHackers/GeneralsGamePatch#504

**Comment by commy2** [comment]
I investigated this a found the reason for this bug. I described it briefly here: https://github.com/commy2/zerohour/issues/17

Solution could look like this: https://github.com/commy2/zerohour/commit/2da86a653e6987338af625c5a11730799d55df73 (it removes the unintended extra damage that affects friendlies as well as enemies).

There is also a semi-related extremely rare bug with the poison cloud: https://github.com/commy2/zerohour/issues/18
Solution to that is: https://github.com/commy2/zerohour/commit/d49a4faba387a6043ff0b20599c61f9a2cc651f3

**Comment by Jundiyy** [comment]
Hmmm, not sure about this one. I'm on both sides here.

**Comment by RisingZH** [comment]
Don't consider this a bug, seems logical that the toxin they leave can hurt friendly units.

Also tox is strong enough (and tox terrorists being as strong as demo terrorists in the first place makes no sense).

**Comment by commy2** [comment]
> that the toxin they leave can hurt friendly units

That's not the bug. They actually do a fraction of the EXPLOSION type damage to allies due to a bug.

> Also tox is strong enough

If anything, it is a nerf, because the Terrorist would do their intended damage - the same as normal GLA and Stealth General Terrorists.

**Comment by xezon** [comment]
As commy said, the issue is not terrorist dying in the toxin puddle, but the terrorist group somehow exploding and not doing any damage and leaving the building nearby almost undamaged. It looks as if just 1 terrorist applied damage.

**Comment by Stubbjax** [comment]
Below is a video demonstration of the issue, where a second terrorist's damage is not fully applied due to being blown up by the first one.

https://user-images.githubusercontent.com/11547761/132830880-af2cd0c4-d05f-442e-984f-cba143fd57e9.mp4

**Comment by MTKing4** [comment]
So removing this, will make it so that you'll need the same amount of terrorists to kill a building as a vgla ones?

I'm not so sure it's a good change, firstly it's a game change, yes it might be a bug but it also makes sense that tox terrorists are not reliable as the demo ones but still are strong enough if handled correctly

**Comment by xezon** [comment]
> So removing this, will make it so that you'll need the same amount of terrorists to kill a building as a vgla ones?

No.

**Comment by MTKing4** [comment]
Ok, but you'll no longer need to split the terrorist when attacking, correct?

**Comment by ExiLe-ZH** [comment]
I don’t know of any bug where a tox terrorist doesn’t do any damage at all? Except when dying to the toxins.

The usual reason tox terrorists don’t kill buildings with the expected numbers is because of the chainreaction, where the terrorists detonate prematurely and too far off target.

Not sure chainreaction should be removed. I wouldn’t vote for it.

**Comment by xezon** [comment]
The problem is, that this happens seemingly at random. Sometimes they kill the building, and sometimes they don't. This is not satisfying behaviour, because you hope the bug won't happen when you play as Toxin and you hope the bug happens when you play against Toxin.

**Comment by Stubbjax** [comment]
> 
> 
> Not sure chainreaction should be removed. I wouldn’t vote for it.

Why _not_? How is this unreliable behaviour beneficial to the game? Do you enjoy the difference between a key structure's destruction or survival - and potentially a game's outcome - being simply down to chance?

Keep in mind that only needing 3 terrorists to kill a war factory / supply is meant to be a unique bonus of the Demolition General, and that this bug dilutes that distinction. It's not logical or intuitive that the Toxin General gets the same bonus.

**Comment by ExiLe-ZH** [comment]
> > Not sure chainreaction should be removed. I wouldn’t vote for it.
> 
> Why _not_? How is this unreliable behaviour beneficial to the game? Do you enjoy the difference between a key structure's destruction or survival - and potentially a game's outcome - being simply down to chance?
> 
> Keep in mind that only needing 3 terrorists to kill a war factory / supply is meant to be a unique bonus of the Demolition General, and that this bug dilutes that distinction. It's not logical or intuitive that the Toxin General gets the same bonus.

Because it has pros and cons. 

The obvious con is that TT’s on buildings can fail, this can be prevented though through social distancing lol. Failratio is much lower in pro level games.

The pro is that moving armies are easier to hit, because if one explodes, then all will instantly. This is often used vs overlord or attack outpost armies in pro level games. This is fun to do aswell.

Removing chain reaction makes them exactly the same as the demo one’s which is not the desirable effect. If done so, the damage need to match gla/stealth but this takes away some fun and uniqueness.

**Comment by xezon** [comment]
@Stubbjax could you maybe put a second video behind the first that show the same attack but without the bug?

**Comment by ExiLe-ZH** [comment]
That video is an example of incorrect micro. 

Someone who’s aware of this ‘issue’ drops them off closer to target and after another by clicking them individually. Every pro knows and does this.

**Comment by MTKing4** [comment]
> Why not? How is this unreliable behaviour beneficial to the game? Do you enjoy the difference between a key structure's destruction or survival - and potentially a game's outcome - being simply down to chance?

They will always destroy the building if they were distanced correctly, that's the best way to have tox terrorists worse than demo terrorists by requiring more micro without even changing the game at all.

**Comment by commy2** [comment]
> So removing this, will make it so that you'll need the same amount of terrorists to kill a building as a vgla ones?

Yeah, but we can also just increase the damage of the Tox Terrorist, so things are back to how they work now., except for the killing of other Tox Terrorists.

**Comment by MTKing4** [comment]
Ok i thought i got it right from your posts, and in that case it makes them equal demo terrorists in everyway if increased the damage, if you don't increase it well, they become a boring vanilla terrorists with nothing special design wise, can't speak for balance though, could be bad since their units are more expensive than vgla and stealth

**Comment by commy2** [comment]
> they become a boring vanilla terrorists with nothing special design wise

They still create a poison cloud.

**Comment by MTKing4** [comment]
Yeah but it doesn't really help does it

**Comment by Stubbjax** [comment]
> 
> 
> That video is an example of incorrect micro.
> 
> Someone who’s aware of this ‘issue’ drops them off closer to target and after another by clicking them individually. Every pro knows and does this.


I disagree. The Technical travelled as close to the Laser Defense Turret as it could go, and the evacuation and attack timing was almost spot on - considering the 1.5s network delay. The fact that the terrorists even managed to hit the target at all with the delay + guarding Humvees was quite miraculous.

It is easy to say _"all the pros are aware of this bug and can mitigate it in the perfect conditions"_, but I would argue that this is not an appropriate response, as it can apply to most of the bugs present in the game and almost never results in a more enjoyable experience.

> 
> Because it has pros and cons.
> 
> The obvious con is that TT’s on buildings can fail, this can be prevented though through social distancing lol. Failratio is much lower in pro level games.

Having pros and cons alone is not enough. Everything in the game has pros and cons, but it's not a perfect game. I would be more likely to accept social distancing if the same behaviour applied to all terrorists and was consistent, but it just doesn't make sense that it's only the toxin variants that _sometimes_ blow each other up.

>
> 
> The pro is that moving armies are easier to hit, because if one explodes, then all will instantly. This is often used vs overlord or attack outpost armies in pro level games. This is fun to do aswell.

This is mostly to do with them exploding when run over, as the same behaviour can be observed with vanilla terrorists.

>
> 
> Removing chain reaction makes them exactly the same as the demo one’s which is not the desirable effect. If done so, the damage need to match gla/stealth but this takes away some fun and uniqueness.

I'd argue it _is_ a desirable effect. The Toxin General is meant to be stunted in the explosives department, just as the Demolition General is for toxins, which makes intuitive sense to players. It would be much more logical and interesting to heighten their effectiveness against infantry - e.g. increasing the resulting contamination field's size and / or lifespan (closer to the toxin tractor's spray ability). This way, players could effectively use toxin terrorists to deny an area to infantry for a duration of time, which would have much more interesting effects on gameplay than a building's random destruction or survival.

> 
> 
> @Stubbjax could you maybe put a second video behind the first that show the same attack but without the bug?

I managed to destroy the Laser Defense Turret here, though it looks like the bug still occurred (you can tell by the terrorist death animation). The terrorists just happened to be close enough to apply enough damage to destroy it. It's much harder to pull off in multiplayer games with network delay.

https://user-images.githubusercontent.com/11547761/132936871-4060acc0-298d-4ed9-bac5-5cdf1da8fa7f.mp4

**Comment by xezon** [comment]
I understand the reasoning from pro player perspective. If player is well aware that it behaves quirky, then he can try work around the problem by keeping his terrorists split apart. If the terrorist behavior, in real game situations, was 100% reliable and consistent, then I would agree. But unfortunately the terrorist behavior is unpredictable.

If you take a blob of terrorists and attack a building they can kill together, then by pure chance they will either
* kill the building
* not kill the building

Ideally this behavior would be consistent so they would always kill the building or always not kill the building when doing the same action.

**Comment by ExiLe-ZH** [comment]
@Stubbjax You can disagree but it's a fact, when evacing with V like that you're counting on luck. In that second video you're 
 lucky, because the 2nd terrorist still dropped off pretty far from target.

Why count on luck while you can control it yourself? You should drive straight past the building and drop them off one by one in line formation with the individual exit buttons. Since the turret is a small building you need to make them exit fast, or alternatively drive a U shape around it and drop 1 off at each side.

Also, all terrorists explode when being run over except demo's, that's not why the toxterrorist is used alot for army terrors, it is the chainreaction.

@xezon If terrorist don't freeze then it should be way more consistent, that bug is priority. This can not be counted as bug, just a different design. Which is fine as is imo.

**Comment by Stubbjax** [comment]
> 
> 
> @Stubbjax You can disagree but it's a fact, when evacing with V like that you're counting on luck. In that second video you're
> lucky, because the 2nd terrorist still dropped off pretty far from target.

One's micro ability is hardly an objective fact. It should not have to involve luck. When evacuating terrorists and targeting a building, one should expect them to reach the building and destroy it. The fact that this is not always the case for toxin terrorists is not only inconsistent and unintuitive, but is incredibly frustrating and can have a significant impact on a game's outcome.

> 
> Why count on luck while you can control it yourself? You should drive straight past the building and drop them off one by one in line formation with the individual exit buttons. Since the turret is a small building you need to make them exit fast, or alternatively drive a U shape around it and drop 1 off at each side.

Sure, there are ways around it. That was never the point. The point is that luck shouldn't be a factor here. I'd be much more interested in reasons for why this behaviour should be kept the way it is rather than advice on getting around the faulty behaviour.

> 
> Also all terrorists explode when being run over except demo's, that's not why the toxterrorist is used alot for army terrors, it is the chainreaction.

I actually observe most toxin terrors failing against armies for this exact reason, where they all end up dying without reaching their targets due to the faulty splash damage behaviour.

>
> This can not be counted as bug, just a different design. Which is fine as is imo.

Oh, it is definitely a bug. Do you believe it makes sense that this behaviour stops once you research Anthrax Gamma? Terrorists don't even leave the contamination field on (non-suicidal) death once Anthrax Gamma is researched.

If the game was released with toxin terrorists consistently dealing the same damage as vanilla terrorists without the friendly fire issue, would you be advocating for this behaviour as a new feature?

https://user-images.githubusercontent.com/11547761/132943289-280c3290-81d1-4066-818e-480846820943.mp4

https://user-images.githubusercontent.com/11547761/132943292-6d63c592-2480-43f6-bbc9-b4505c093a80.mp4

**Comment by ImTimK** [comment]
> > @Stubbjax You can disagree but it's a fact, when evacing with V like that you're counting on luck. In that second video you're
> > lucky, because the 2nd terrorist still dropped off pretty far from target.
> 
> One's micro ability is hardly an objective fact. It should not have to involve luck. When evacuating terrorists and targeting a building, one should expect them to reach the building and destroy it. The fact that this is not always the case for toxin terrorists is not only inconsistent and unintuitive, but is incredibly frustrating and can have a significant impact on a game's outcome.
> 
> > Why count on luck while you can control it yourself? You should drive straight past the building and drop them off one by one in line formation with the individual exit buttons. Since the turret is a small building you need to make them exit fast, or alternatively drive a U shape around it and drop 1 off at each side.
> 
> Sure, there are ways around it. That was never the point. The point is that luck shouldn't be a factor here. I'd be much more interested in reasons for why this behaviour should be kept the way it is rather than advice on getting around the faulty behaviour.
> 
> > Also all terrorists explode when being run over except demo's, that's not why the toxterrorist is used alot for army terrors, it is the chainreaction.
> 
> I actually observe most toxin terrors failing against armies for this exact reason, where they all end up dying without reaching their targets due to the faulty splash damage behaviour.
> 
> > This can not be counted as bug, just a different design. Which is fine as is imo.
> 
> Oh, it is definitely a bug. Do you believe it makes sense that this behaviour stops once you research Anthrax Gamma? Terrorists don't even leave the contamination field on (non-suicidal) death once Anthrax Gamma is researched.
> 
> If the game was released with toxin terrorists consistently dealing the same damage as vanilla terrorists without the friendly fire issue, would you be advocating for this behaviour as a new feature?
> TOXIN.1.mp4
> TOXIN.2.mp4

Dunno what else I have to explain that there's no luck involved once you know how to deal with the chainreaction. Should it also be removed from demo traps, bombtrucks etc? 

The damage IS consistent, it always takes to 3 to consistently kill a wf/sup e.g. How are you so stubborn to not understand the issue here?

**Comment by xezon** [comment]
TOXIN.1.mp4 does illustrate the problem nicely. You have this blob of Terrorists, and strangely only 3 Terrorist nearby die with it. And the Technical which is much further away. It is really difficult to reason this behavior.

**Maybe one of the issues here is that the terrorist has no outer damage radius where the damage strength would decay with distance? If there was no hard cut between damage and no damage, maybe this behavior would feel more natural.**

I removed a comment from ImTimK because the language was not appropriate.

**Comment by ExiLe-ZH** [comment]
![Command   Conquer - Generals Screenshot 2021 09 11 - 12 09 03 36](https://user-images.githubusercontent.com/32326277/132944486-34b398da-b90a-43f5-a211-4053ca958cd2.png)
![Command   Conquer - Generals Screenshot 2021 09 11 - 12 09 28 66](https://user-images.githubusercontent.com/32326277/132944488-6167fbbe-0b48-474e-8329-f7739bf73b61.png)
![Command   Conquer - Generals Screenshot 2021 09 11 - 12 09 54 91](https://user-images.githubusercontent.com/32326277/132944489-e607c2aa-de17-4eca-8017-9d277bcba5eb.png)
![Command   Conquer - Generals Screenshot 2021 09 11 - 12 10 05 87](https://user-images.githubusercontent.com/32326277/132944491-f514f5f5-4c63-4ced-930a-bb21ed29c1c3.png)

These illustrations should be sufficient.

**Comment by ExiLe-ZH** [comment]
@Stubbjax 
> One's micro ability is hardly an objective fact. It should not have to involve luck. When evacuating terrorists and targeting a building, one should expect them to reach the building and destroy it. The fact that this is not always the case for toxin terrorists is not only inconsistent and unintuitive, but is incredibly frustrating and can have a significant impact on a game's outcome.
> 

Damage output is consistent, it always takes 3 to kill a wf/sup e.g.

But if you let the chainreaction work against you where 1 or more terrorist explode prematurely (not close enough to target), then that's really your fault.

It's intuitive enough to take advantage of this mechanic.

> Sure, there are ways around it. That was never the point. The point is that luck shouldn't be a factor here. I'd be much more interested in reasons for why this behaviour should be kept the way it is rather than advice on getting around the faulty behaviour.
> 

Again, luck is no factor when you take control.

> I actually observe most toxin terrors failing against armies for this exact reason, where they all end up dying without reaching their targets due to the faulty splash damage behaviour.
> 

Who do you observe, because it works very consistently for me. Also watch Boycah's replays.

> Oh, it is definitely a bug. Do you believe it makes sense that this behaviour stops once you research Anthrax Gamma? Terrorists don't even leave the contamination field on (non-suicidal) death once Anthrax Gamma is researched.
> 

Sounds to me that the Gamma upgrade is bugged.

> If the game was released with toxin terrorists consistently dealing the same damage as vanilla terrorists without the friendly fire issue, would you be advocating for this behaviour as a new feature?
> TOXIN.1.mp4
> TOXIN.2.mp4

It's kinda weird some closer standing terrorists don't explode I would agree there.

**Comment by xezon** [comment]
> Oh, it is definitely a bug. Do you believe it makes sense that this behaviour stops once you research Anthrax Gamma? Terrorists don't even leave the contamination field on (non-suicidal) death once Anthrax Gamma is researched.

Oh, so behavior changes after Gamma Upgrade? That sounds indeed broken. Also the damage changes after Gamma Upgrade. You then need 4 terrorist to kill Warfactory instead of 3.

**Comment by MTKing4** [comment]
As much as I'd like disagree due to how big of a change this is, but stubbjax is right, it is inconsistent and unintuitive, remember that we're not appeasing pros only here, sure the pros know how to handle it, but that's not the right approach to get more people into the game and make it easier for them

That being said I'm against changing it entirely but i'll meet you at the middle and suggest we do this:

+ Fix the terrorist bug
+ Add the damage required to equalize it with vzh
+ Make terrorists damage friendly units all the time
+ Add a description for that in the tooltip

**Comment by xezon** [comment]
It's one of these cases where we have broken behavior but after 15 years of getting used to it we eventually no longer see it as such. It would be great to find a solution to this. Personally I have nothing against chain reacting Toxin Terrorists, but the way it is implemented is just not satisfying. Hopefully we can get some Expert Player opinions on this.

Toxin GLA Terrorist Quirks Summary:
* Has friendly fire kill damage before Gamma Upgrade only
* Friendly fire damage does not decay over distance, it either kills nearby friendly units or not
* Friendly fire damage radius is vastly different for different unit types
* Friendly fire damage can feel 'random' when grouping them together to attack a target
* (Suicide damage is greater before Gamma Upgrade only)

**Comment by xezon** [comment]
How about trying the following:
* Add an outer radius with damage decay to Terrorist friendly damage for better readability
* Make friendly damage radius consistent for all units
* Make friendly damage consistent regardless of upgrades

This would keep original behaviour but may make it a lot less frustrating for user because results become predictable.
