### ISSUE TITLE
Killing Elite China Battlemaster grants a lot of XP

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#395]
Killing Elite China Battlemaster grants a lot of XP. It is very common that any faction vs China Tank will progress much quicker with XP. Check if something needs to be done about this.

### Proposal 1
Reduce XP reward for China (Tank) Battlemasters by around 20%

**Comment by commy2** [comment]
This issue is more general about all tanks (Crusader, Paladin, Marauder, vChina Battle Master).

Almost all basic vehicles grant 50 XP when killed. This value doubles once vet 2 and doubles again once vet 3 (4 times from base).

Tanks however do grant 100 XP, meaning that relying on them will likely lead to your opponent winning the genpoint race. It will also vet up their units: keep in mind that 100 XP for a single kill is enough to promote almost all units to vet 1.

A tank at vet 2 grants four times the amount of experience as almost all vet 0 / vet 1 vehicles do.

Fun fact: After Advanced Training, a vet 0 King Raptor will promote instantly to vet 3 (!) when killing a single vet 2 Battle Master (it's a one shot too).

One exception is the Scorpion tank which grants 60 XP at base.

**Comment by Madrageeeeee** [comment]
I would say that bringing the xp down to 80 or 85 would already help and not influence the game too much

Even though it is fun in tank
Mirrors that you get to spam promotions so quick it is kinda insane how quick you vet up from killing tank battlemasters. 

Would say it is most impactful for gla vs tank and nuke vs tank. Will give tank more of a fighting chance

**Comment by Jundiyy** [comment]
80 seems reasonable, that's 20% extra kills to get the your units promoted vs Tank and also getting GPs.

**Comment by commy2** [comment]
25% extra ^^

**Comment by EnigmaZift** [comment]
This should not be changed unless you are changing this globally. Almost all tanks have a veterancy set that looks like

`  ExperienceValue = 100 100 200 400    ;Experience point value at each level
  ExperienceRequired = 0 200 300 600 ;Experience points needed to gain each level`

This is intentional design. For some reason. Has nothing to do with the Elite BM though

**Comment by ReLaX82** [comment]
75 or something will not hurt. It makes no sense in comparison with other Tanks.

**Comment by DoMiNaToRuk2** [comment]
Do what rage said

**Comment by xezon** [comment]
I will take care of it.
