### ISSUE TITLE
USA Spy Drone is selectable by Q (Select All Units)

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#40]
USA Spy Drone is selectable by Q (Select All Units)

Add `IGNORES_SELECT_ALL` to `KindOf`

**Comment by commy2** [comment]
Also see: https://github.com/commy2/zerohour/issues/68
Solution: https://github.com/commy2/zerohour/commit/ee0f0a71684b14ed279ce719102daf1bd6103d95

This also sort of affects the Black Lotus. I got feedback from multiple people in the past that said that they actually kill of their Lotus intentionally or on accident because it interfers with the Q key. Note that the Hacker is not selected by the Q key.

See: https://github.com/commy2/zerohour/issues/190
Solution: https://github.com/commy2/zerohour/commit/60482599db607205145c65a1b4b5aff971c862b5

**Comment by RisingZH** [comment]
Why would you want to select your spy drone (as in the gen promotion?)? 

This would mean if I had missile defenders under a spy drone I wouldn't be able to press Q then laserlock?

**Comment by commy2** [comment]
> This would mean if I had missile defenders under a spy drone I wouldn't be able to press Q then laserlock?

No.

**Comment by xezon** [comment]
The issue title was confusingly worded. I changed it. Anyway, the change is already committed, so there is nothing to be done here anymore.
