### ISSUE TITLE
GLA Fake Buildings do not build twice as fast with Power

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#458]
GLA Fake Buildings do not build twice as fast with Power. Reported by Dominator.

**Comment by Jundiyy** [comment]
That's because of the upgrades, you can't upgrade faster with power.

**Comment by commy2** [comment]
To clarify, upgrades do not get a speed penalty for being low / without power.

**Comment by xezon** [comment]
Player does not know about upgrades. Player only sees scaffolds.

**Comment by commy2** [comment]
The upgrade we refer to is the one where you switch from a fake to a real building. I am pretty sure that is what Dominator meant too. The Fake building itself should build twice as fast with power in 1.04 already.

**Comment by xezon** [comment]
I think he meant the build time of Fake building scaffolds.

**Comment by commy2** [comment]
I'll try to reproduce.

**Comment by commy2** [comment]
- vanilla GLA (Fake) Command Center:

|  | no power | with power |
| ------------------------ | ---------- | ------------- |
| real from scaffold       | 90 | 45 |
| fake from scaffold       | 60 | 30 |
| real from fake (upgrade) | 30 | 30 |

,

- vanilla GLA (Fake) Barracks:

|  | no power | with power |
| ------------------------ | ---------- | ------------- |
| real from scaffold       | 20 | 10 |
| fake from scaffold       | 10 | 5 |
| real from fake (upgrade) | 10 | 10 |

All in seconds. These are actual build-times measured in game. They exactly match with what is expected.

The problem seems to be that the power state does not influence the build-time for upgrades. This is true for every upgrade. I see no work-around just using INI file editing.

Can't be arsed to test the other fake buildings.

**Comment by xezon** [comment]
Thank you for checking. Looks all correct.
