### ISSUE TITLE
Review factory door times

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#464]
Streamline all factory door opening times. To compensate changed build times, unit build times can be offset to door time changes accordingly.

**Comment by Jundiyy** [comment]
Not sure about streamline, even if we set the unit build times to match the times they are now, it would mean a slower build time for units on low power as the door animation is set to a certain amount.
China perhaps could have a buff alone with the door, allowing units out a bit faster without changing the unit time.

**Comment by Jundiyy** [comment]
Thinking over if a bit more. I think it's best to leave each army with their own times. All GLAs follow one rule, Chinas their own and USAs theirs.

Firstly there is the problem of low power, explain it more below. And secondly tied to this is we would need to do a lot more balance testing to see how much of a difference this actually makes, taking us back to square one of how much balance we have already achieved through changing unit times alone, as that has had a lot of testing done already, many fun games, clan wars and tournaments. 

By increasing door time for GLA, it only makes them more powerful with power, as units will be spammed out faster, and possibly too fast that the door doesn't even close, so that means even faster units that the time given.

For Chinas and USAs, attacking their power is not uncommon, so on low power they would suffer a lot more, which I don't think is a good idea.
The only faction I see which seems a reason to do is China, but without changing the original times of the common units.
This means, units on low power still come out a bit faster than in 1.04 and the less common units will take a bit longer.

**Comment by xezon** [comment]
According to commy2 these are the door times:

| Object            | Door time (s) |
|-------------------|--------------:|
| USA CC            |          2.00 |
| China CC          |          3.00 |
| Airfields (both)  |          2.00 |
| Arms Dealer       |          2.00 |
| USA War Factory   |          3.25 |
| China War Factory |          4.00 |

Maybe bring down China CC to 2.00, USA War Factory to 3.00 and China War Factory to 3.00? It would already be more consistent then. It helps player to understand how long it will take unit from Unit Queue Icon completion to final production from factory.

Keep in mind we are 1 to 2 years away from any final release. You have enough time to design and test.

**Comment by Jundiyy** [comment]
I don't think this part matters, `It helps player to understand how long it will take unit from Unit Queue Icon completion to final production from factory`, there are only a handful of players that know the times of units and will use them. Everybody else just watched the unit come out of the wf after it has been produced.

I'd prefer keeping USA at 3.25, so China could also have 3.25. Stays consistent and less balancing problems to think over, test and worry about as USA isn't being touched.

The CC could be made the same as USA, with or without the Dozer change, although if we keep the original Dozer time, it does have a knock on effect, Faster Dozer, faster power, faster truck rush and faster wf/af rush, (truck rush can be quite powerful many times), this should be easy to test as it's mainly the first min only.
I will test this change when I next do test games.

**Comment by commy2** [comment]
> By increasing door time for GLA, it only makes them [...] possibly too fast that the door doesn't even close, so that means even faster units that the time given.

This is a separate issue: when GLA has power, Technicals and non-Demo Combat Bikes can be chain produced without the door closing. Door opening and closing are entirely separate values though. I intend to fix the Arms Dealer door closing issue regardless of this.

**Comment by ExiLe-ZH** [comment]
Barely anybody knows about this, like even normal build times isn't general knowledge. Balance is the only relevance here, so any change made serves balance. If consistency is achieved through this, that's great for the coders (who care about consistent code), but otherwise there's no reason to change anything.

Talking about balance, if I understand correctly now, if we want to decrease GLA's build time with power, we have to decrease door time?

**Comment by xezon** [comment]
> Talking about balance, if I understand correctly now, if we want to decrease GLA's build time with power, we have to decrease door time?

Increase door time.

**Comment by ExiLe-ZH** [comment]
> 
> 
> > Talking about balance, if I understand correctly now, if we want to decrease GLA's build time with power, we have to decrease door time?
> 
> Increase door time.

That's what i thought until I read Jundiyy's comment.

> By increasing door time for GLA, it only makes them more powerful with power, as units will be spammed out faster, and possibly too fast that the door doesn't even close, so that means even faster units that the time given.

I initially thought it's just a simple sum like this, but it isn't?

```
no power:
unit 10s
door 4s
total 14s

with power:
unit 5s
door 4s
total 9s

vs.

no power:
unit 6s
door 8s
total 14s

with power:
unit 3s
door 8s
total 11s
```

**Comment by commy2** [comment]
Jundiyy's comment is backwards. You're correct in how it works. However, using the door to balance powered GLA is out of question imo. ~~When a factory transitions the visual damage states, the door animation resets, meaning the unit will take even longer to come out.~~

~~That's also why the China War Factory door sucks so much. Taking 4 seconds for the unit to pop out means that there is a 4 seconds window for an animation reset as well as a up to 4 seconds penalty.~~

Striked out part is misinfo. Door animation resets, but not the build time delay caused by it.

**Comment by xezon** [comment]
Would have been easier if game developers made it consistent to begin with.

**Comment by Jundiyy** [comment]
Which part didn't you guys understand? Looking at Exile's table, that is what I said?

Edit: right I understand what's happened. I was replying from the actual codes in the game, which show GLA with power first. Whereas in the game of course, it's the opposite way round.
This is why I have this.

```
Unit with power
BT 10s
Door 2s
Total 12s

No Power
BT 20s
Door 2s
Total 22s

New door

Unit with power
BT 8s
Door 4s
Total 12s

No Power
BT 16s
Door 4s
Total 20s
```

And that's why I said the doors might not even close at times if the units come out faster.

But yea anyway, agree with what Exile said about balance.

**Comment by xezon** [comment]
Door opening time considerations:
* Longer door time will require player to wait longer for unit to spawn after it completed building in the queue
* Door time does not halve with Power
* ~~Door time is reset when building goes into damaged state (attacked)~~
* ~~Door time is reset when building goes into intact state (repaired)~~
* Door time can exceed actual animation of door

**Comment by ExiLe-ZH** [comment]
Is it possible to make doortime 0 seconds so it's nothing but an animation? Time should be added to BT then. 

If possible, any downsides?

**Comment by xezon** [comment]
If Doortime is 0, then I expect units will leave the Production Facility while the doors are closed.

**Comment by ExiLe-ZH** [comment]
It's too bad that power is a general multiplier, would be good if values could be tweaked per unit/building.

**Comment by ExiLe-ZH** [comment]
> If Doortime is 0, then I expect units will leave to Production Facility while the doors are closed.

Probably yes, possible to start animation sooner?

**Comment by xezon** [comment]
Probably not. I don't think it would be even a good idea to mess with this core mechanic of game other than tweaking values, as you could open a can of worms if you try to play tricks.

Enlima29:
> No, the model conditions are tied to the door time

**Comment by RisingZH** [comment]
I don’t see the benefit to changing this - no reason why all factions have to be the same.

**Comment by commy2** [comment]
GLA can chain produce Technicals and Combat Bikes with power, because the door doesn't close in time. Shaves off additional 2 seconds build-time. (meaning 12 seconds w/o power, 5 seconds w/ power)

https://user-images.githubusercontent.com/6576312/136651389-591b53c0-811a-4ecd-963f-5fa416a640c3.mp4

**Comment by commy2** [comment]
Building 2 or more China Dozers after the Power Plant is build has the same issue:


https://user-images.githubusercontent.com/6576312/136651463-50703a2a-0ab1-4553-a803-f9bd7ceb92ab.mp4

However, the USA Command Center door works as expected.


https://user-images.githubusercontent.com/6576312/136651475-8bb39fc6-c07a-41df-8d5d-7b2842a24da9.mp4

**Comment by commy2** [comment]
Please stay objective and don't insult the contributors. Thanks.

**Comment by xezon** [comment]
I will test with China CC to 2.00 and China War Factory to 3.25. These look like safe changes on paper. It will make China have slightly faster builds, where a Tank would theoretically be out 1.75 seconds quicker or a Helix 1.00 second quicker.

Overall build time speed will accumulate with each Tank producing 0.75 seconds quicker. That means 10 Tanks come 7.5 seconds quicker. This can help China to put early pressure on GLA and USA quicker. As of Original 1.04, it is USA and GLA that put the quick pressure on China more often.

Whether or not this is good change in practice, we will have to check when playing. But I think it makes sense to submit this early and then just see what happens with it.

**Comment by ExiLe-ZH** [comment]
> I will test with China CC to 2.00 and China War Factory to 3.25. These look like safe changes on paper. It will make China have slightly faster builds, where a Tank would theoretically be out 1.75 seconds quicker or a Helix 1.00 second quicker.
> 
> Overall build time speed will accumulate with each Tank producing 0.75 seconds quicker. That means 10 Tanks come 7.5 seconds quicker. This can help China to put early pressure on GLA and USA quicker. As of Original 1.04, it is USA and GLA that put the quick pressure on China more often.
> 
> Whether or not this is good change in practice, we will have to check when playing. But I think it makes sense to submit this early and then just see what happens with it.

worth trying, might even restore a lot of balance indeed

**Comment by Jundiyy** [comment]
I think it could work now that everything else has been reverted.
And it would be best to do this change sooner than later since any other price or build time change we may want to do will depend on this.

Some changes, not saying it's bad, just to note. 
Faster Supply Truck rush, faster Helix rush, especially double Helix. Faster first units, Nuke BM. Faster Dozer rush as well. Also means faster Rax + Cap+Bunker.
This also means, low power will make less impact to China.

**Comment by xezon** [comment]
Door times are unaffected by Power levels. But yes, everything early game will be theoretically 1 second faster due the second Dozer leaving the door quicker. 1 second is marginal time, but may help China a bit, so it is ok.

**Comment by Jundiyy** [comment]
I wasn't too clear, that is what I mean, no power would help (in comparison to changing unit times), because the door time does not change when there is no power, whereas unit times do.

So if a unit usually takes 10s with power, 20s without power, + 4s door time. That's 24s with no power.
But now it will be 0.75s less.

Whereas when we change unit times, they still slow down with low power.

**Comment by xezon** [comment]
This is now fixed.

USA CC & China CC have same door timings (1500 ms)
USA WF & China WF have same door timings (3300 ms)
USA Air & China Air have same door timings (2000 ms)
GLA Armsdealer has individual door timing (2000 ms)

Streamlining these times benefited China only (CC -1500 ms & WF -700 ms)

**Comment by ExiLe-ZH** [comment]
> GLA can chain produce Technicals and Combat Bikes with power, because the door doesn't close in time. Shaves off additional 2 seconds build-time. (meaning 12 seconds w/o power, 5 seconds w/ power)
> door.mp4

Should we look into this?

**Comment by Jundiyy** [comment]
I think the door closing time has already been tweaked.

**Comment by xezon** [comment]
commy2 fixed that already

**Comment by commy2** [comment]
See: https://github.com/TheSuperHackers/GeneralsGamePatch/pull/538

**Comment by ExiLe-ZH** [comment]
Why is GLA Arms Dealer 2000ms? What if we make that 3300ms aswell? 

If we subtract the difference of 1300ms from the individual units again, then Power-Spam would be nerfed by 650ms per unit, while keeping the normal production speed the same.

https://github.com/TheSuperHackers/GeneralsGamePatch/issues/1278

**Comment by xezon** [comment]
It is 2000 because EA Games made it that way.

**Comment by ExiLe-ZH** [comment]
China War Factory was 4000 because EA Games made it that way.

**Comment by Jundiyy** [comment]
If you slow down the doors, it will slow down every unit before power and after power. Making China units build faster (by having faster opening door times) is a needed buff and quite safe to do.

**Comment by ExiLe-ZH** [comment]
Yes good reasons to the streamline China's WF indeed.

I'll demonstrate why it could be good for GLA aswell:

| Unit | Power | Build TIme | Door Time | Total Time |
| - | - | - | - | - |
| Quad | no | 12 | 2 | 14 |
| Quad Patched | no | 10.7 | 3.3 | 14 |
| Quad | yes | 6 | 2 | 8 |
| Quad Patched | yes | 5.35 | 3.3 | 8.65 |

Don't underestimate how much 650ms is, remember how TH spam became noticeably faster by shortening production by 500ms (5 to 4.5s) in the 1.04+ beta?

**Comment by xezon** [comment]
In principle it would be possible to that, but we would get quite awkward build times by increasing door time by 1300 milliseconds and re-adjusting unit build times. Increasing door time by 1000 or 1500 milliseconds would make it a bit more gracious.

**Comment by ExiLe-ZH** [comment]
I agree it's less awkward to have rounded unit production values and move the odd numbers to the doortime, in practice and for balance it doesn't matter all that much though.

**Comment by ImTimK** [comment]
Experimenting a bit with Door Times and Power Production:

![Door Times   Power Production](https://user-images.githubusercontent.com/32326277/192145684-35380e33-8e4a-4f24-b736-cdb7048219da.png)

**Comment by ExiLe-ZH** [comment]
This one is fairly clean

![image](https://user-images.githubusercontent.com/32326277/192792023-46e43860-b05b-4e23-959c-3ac495233342.png)

**Comment by ExiLe-ZH** [comment]
Or 4 seconds

![image](https://user-images.githubusercontent.com/32326277/192793039-1dfa54af-c372-4809-a935-cffe28315988.png)

**Comment by ExiLe-ZH** [comment]
Btw, is the bug fixable where the door animation resets when the building takes damage, thus slowing down the unit that comes out?

**Comment by commy2** [comment]
^ The animation resets, but the unit pops out at the same time regardless.
