### ISSUE TITLE
Demo GLA Terrorist applies no damage to other friendly units

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#504]
Demo GLA Terrorist applies no damage to other friendly units. All other GLA Terrorists do.

Related Terrorist issues:
* TheSuperHackers/GeneralsGamePatch#26
* TheSuperHackers/GeneralsGamePatch#31
* TheSuperHackers/GeneralsGamePatch#30
* TheSuperHackers/GeneralsGameCode#37
* TheSuperHackers/GeneralsGamePatch#502
* TheSuperHackers/GeneralsGamePatch#503
* TheSuperHackers/GeneralsGamePatch#504

## Proposal 1
Terrorists and Demo Bikes and all other suicide units apply friendly damage always.

## Proposal 2
Terrorists and Demo Bikes apply friendly damage before Demo Upgrade only.

**Comment by Madrageeeeee** [comment]
Always figured that the demo terrorist didnt apply damage to their own units when killed because of their superior demolition pack. They only let it explode when they want to and never without reason or when they get shot 😁

although you would like it to apply damage to enemy units ofcourse when it gets run over. Although, as discussed in another topic this is a kinda fun game dynamic because it allows for more ‘skill’.

**Comment by xezon** [comment]
2 Proposals added to opening post. Making suicide units for Demo Terrorist apply suicide damage will change the way it plays more, because after Demo Upgrade it is all about the suicide ability. Proposal 2 would irritate more I think because of a new in-faction inconsistency.

I would say leave as is.

**Comment by Jundiyy** [comment]
Leave as is.
