### ISSUE TITLE
GLA cash bounty activated with just a CC scaffold

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#590]
Pretty positive this is not intended. 

GLA is already very strong economically, think it would be fair having to spent 2k and wait for the CC to finish before bounty is activated (maybe even having it alive for it to work like other genpowers?).

**Comment by commy2** [comment]
Not just that, it stays activated once you delete the scaffold.

**Comment by EnigmaZift** [comment]
The Cash Bounty is always active once it has been activated. I agree, it's very easy to change it such that the CC needs to be alive for the effect to activate.

**Comment by commy2** [comment]
> it's very easy to change it such that the CC needs to be alive for the effect to activate.

Can you show how?

**Comment by xezon** [comment]
CC scaffold for activation is indeed nonsense. Logical fix is either:

a) Cash Bounty is always active as it was picked (fix)
b) Cash Bounty is only active when Command Center is alive (design change)
c) Cash Bounty becomes active when Command Center was built once after research

**Comment by RisingZH** [comment]
Just placing a cc scaffold shouldn’t active cash bounty, either it should activate as soon as you click the gen power or when you actually build a cc, placing and cancelling a scaffold is silly. Can see it both ways, personally would say you should have to complete the cc.

**Comment by Madrageeeeee** [comment]
Agree with activating it only after cc completes

**Comment by alanblack166** [comment]
Just make the CC spawn an object once it's complete, and that object will grant the bounties. Simple as that.

**Comment by xezon** [comment]
> Just make the CC spawn an object once it's complete, and that object will grant the bounties. Simple as that.

This object also needs to be there after a Command Center is constructed, because there is also the case where player selects Generals Power and already has a Command Center built.

**Comment by commy2** [comment]
And the object should delete itself when the Command Center is sold or destroyed, but stick around as long as the Command Center just stays there (since you can pick Bounty while already having a Command Center). It should also handle transfering buildings by surrendering and capturing. This is not trivial to implement.

**Comment by EnigmaZift** [comment]
Guys - it does not matter if the object is transferred, destroyed or whatever. Once the Bounty is activated, it stays activated regardless of what happens.

If it's transferred, nothing happens - if you are a GLA when it is transferred, then it can activate your bounty - if you have the science. [This aspect can even be used to allow Bounty-cross-teching with different GLA generals; or you can keep them separate if you wish, either way is possible]

If the parent, the GLA Command Center dies, then this object dies (Slaved), which means purchasing new levels of Bounty will not upgrade your initial level until you build or capture or get transferred a new GLA Command Center.

So for all intents and purposes it's immune to exploits.

**Comment by commy2** [comment]
> If the parent, the GLA Command Center dies, then this object dies (Slaved), which means purchasing new levels of Bounty will not upgrade your initial level until you build or capture or get transferred a new GLA Command Center.

This sounds like you have a specific implemenation in mind already. Can you provide it, so it can be thoroughly tested for edge-cases etc?

**Comment by commy2** [comment]
Method 1: No Command Center is needed at all to enable Cash Bounty. Not even a scaffold.
Method 2: A completed and not shut down Command Center is needed. A scaffold will have to be completed first. A disabled Command Center (e.g. EMP Bomb, Microwave tank) will also not work until the Command Center is re-enabled.

**Comment by ExiLe-ZH** [comment]
> 
> 
> Method 1: No Command Center is needed at all to enable Cash Bounty. Not even a scaffold. Method 2: A completed and not shut down Command Center is needed. A scaffold will have to be completed first. A disabled Command Center (e.g. EMP Bomb, Microwave tank) will also not work until the Command Center is re-enabled.

Method 2 is the way to go IMO.

**Comment by xezon** [comment]
Method 2 is ok, but we need to note this new behavior in the Cash Bounty Tooltip.

**Comment by xezon** [comment]
JP? Japanese? We can use Google Translate for most things. It does yield good enough results for starters. We could mark auto translated changes with a special character, so we can have it re-reviewed later.

**Comment by commy2** [comment]
> We can use Google Translate for most things. It does yield good enough results for starters.

Haha.

**Comment by EnigmaZift** [comment]
> > If the parent, the GLA Command Center dies, then this object dies (Slaved), which means purchasing new levels of Bounty will not upgrade your initial level until you build or capture or get transferred a new GLA Command Center.
> 
> This sounds like you have a specific implemenation in mind already. Can you provide it, so it can be thoroughly tested for edge-cases etc?

Just asking, how do you want me to provide it? 

Here's how it works though, from a technical POV;
We use GrantUpgradeCreate with a ExemptStatus for UNDER_CONSTRUCTION and UpgradeToGrant with a dummy upgrade (OBJECT and not PLAYER). 
Then we have ObjectCreationUpgrade with an OCL for a dummy object (let's call it GLABountyGrantObject). 
For all intents and purposes this dummy object has the same code as an American Battle Drone, just with CashBountyPower and no model (since it's basically invisible) and being invincible, among some other changes which basically inert (it should do literally nothing except be a vessel for this).
Our CashBountyPower is copied directly from the host Command Center.
Additionally, it's important that the object is SlavedUpdate (the parameters don't matter so much, since the object is inert.)

Explanation;
The Command Center gives itself an upgrade when built. This upgrade is only granted once it's fully built (Hence the exception). The upgrade produces an invisible invincible "battle drone" which carries all the Bounty stuff. 
If the Command Center is destroyed, so is the GLABountyGrantObject, which disables you from getting new Bounties until you rebuild the Command Center.
Since the upgrade is OBJECT and not PLAYER, the upgrade is granted once again, only once a Command Center is fully built, and the upgrade is sort of granted FOR that Command Center.
If transferred, this object is also transferred and serves the same purpose - for non-GLA players it does nothing. For GLA players, it allows them to gain bounty, even if they did not build that Command Center.

Hopefully that makes sense, if you need help implementing it, you can ask me on Discord

**Comment by commy2** [comment]
Enginma, does this work when the player surrenders in a team game, and when the Command Center is captured by the enemy, i.e. is ownership of the dummy transferred over to the new owner of the Command Center?

**Comment by EnigmaZift** [comment]
> Enginma, does this work when the player surrenders in a team game, and when the Command Center is captured by the enemy, i.e. is ownership of the dummy transferred over to the new owner of the Command Center?

Yes. See:
`If transferred, this object is also transferred and serves the same purpose - for non-GLA players it does nothing. For GLA players, it allows them to gain bounty, even if they did not build that Command Center.`

This means transferred by any means - capturing, surrendering, the dummy is always the same allegiance as the parent (afaik)

**Comment by EnigmaZift** [comment]
However, note, the Bounty with this system will bypass: 
`A disabled Command Center (e.g. EMP Bomb, Microwave tank) will also not work until the Command Center is re-enabled.`

I don't think that should be too much of an issue personally.

**Comment by commy2** [comment]
What's the benefit compared to the implementation [here](https://github.com/xezon/GeneralsGamePatch/pull/595/files) where we more or less know for certain it will behave correctly in edge-case multiplayer scnearios?

**Comment by EnigmaZift** [comment]
Same deal, the only difference is that your implementation can be disabled by statuses that also disable weapons, which can be prone to weird buggy behaviour.

For example EMP or Microwave might be able to stop players from getting bounties. As another example, anything that uses NO_ATTACK status (which might be nothing in the base game but mods sometimes use it)

This implementation would ignore that, you would be able to get Bounties even if the Command Center is disabled or under NO_ATTACK status.

FWU can be buggy in general, which is why modders tend to avoid it. But both work in all (important) edge-cases.

**Comment by commy2** [comment]
So with a generic ObjectCreationUpgrade (OCU) implementation, Cash Bounty access would be granted even when the Command Center is disabled while the science was unlocked?

> This means transferred by any means - capturing, surrendering, the dummy is always the same allegiance as the parent (afaik)

The "afaik" sounds to me that there is limited confidence in this. We'd have to actually do more testing to figure out the behaviour. It should also be considered if world builder scripts that delete or transfer ownership between players / ais correctly sync CC and subordinate dummy object ownership correctly.

---

What does "buggy in general" regarding the FWU implemenation mean exactly? When would this actually behave unexpectedly?

**Comment by EnigmaZift** [comment]
> The "afaik" sounds to me that there is limited confidence in this. We'd have to actually do more testing to figure out the behaviour. It should also be considered if world builder scripts that delete or transfer ownership between players / ais correctly sync CC and subordinate dummy object ownership correctly.

Slaved objects are always the same allegiance as their parent. Sorry if I sounded unsure, just had to double check since writing it at the time.

> So with a generic ObjectCreationUpgrade (OCU) implementation, Cash Bounty access would be granted even when the Command Center is disabled while the science was unlocked?

Yes. Since the slave is independent from statuses of the host (eg. disabled etc.)

> What does "buggy in general" regarding the FWU implemenation mean exactly? When would this actually behave unexpectedly?

In regards to this specific implementation, I don't forsee any issues - but FWU tends to behave unexpectedly when there are objects that have other weapons, or objects that use firing condition-states (like defences or units), where it has weird effects like messing with visuals.

I will note one last thing about FWU implementation, it's just not very tidy. During 250ms (4 engine frames / 8 logic frames) of the Command Center being destroyed and potential brief period where the player can still obtain the benefits of Bounty while not having a CC. 
In contrast, OCU implementation - or rather Slaved - is the more important aspect here (you can tie FWU and Slaved together and that might actually work even better) - works instantly, and there's no "deadzone" so to speak.

**Comment by commy2** [comment]
I tried implementing the OCU Method: https://github.com/xezon/GeneralsGamePatch/pull/602/files
I was unable to make the dummy disappear when the Command Center is sold.
What ingredient am I missing?

**Comment by EnigmaZift** [comment]
The dummy needs to have a locomotor, a physics behaviour (dies on hitting the ground). When structure is sold, the object should fall to the ground, killing itself. Plus, not sure if Highlander works here.
