### ISSUE TITLE
Should Frenzy reveal the map?

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#591]
Frenzy reveals map under fog for a certain duration (longer than satellite scan even I think), should this be the case?

**Comment by xezon** [comment]
Please add a description.

**Comment by commy2** [comment]
The Frenzy special power - like most, but not all special powers - temporarily reveals the map where it was used. It does not detect stealthed units.

Infantry General has Frenzy 1 at rank 1 available, so immediately from the start. For the other Chinas Frenzy 1 is rank 3. This means that Infantry General can reveal the enemy faction and scout the build order by picking and using Frenzy 1.

When using Frenzy, a unqiue FX and sound is played at the location it was used. At least the sound can be heard by the opposing player (not sure about the FX) if the camera was over the area where Frenzy was used, when it was used.

If Frenzy is used right at the start of the battle and the opponent pays attention, they will know that the enemy is Infantry General - if they are aware of this bug.

Emergency Repair, which is also available at rank 1 for certain factions (AFG, Tank, Nuke, Stealth) does not reveal the map, probably because it's not meant to be used inside the fog and no attack is incoming for the player to watch.

The only other special power that reveals the map and can be picked at rank 1 is the AFG Carpet Bomber, but 1) that requires a Strategy Center to be used and 2) USA has Satellite Scan anyway, so it becomes less impactful.

**Comment by commy2** [comment]
Satellite Scan reveals an area of 300 dst radius for 13 seconds. There is some growth of the radius at the very beginning, so you will not have the full view immediately and for all 13 seconds. It also detects stealthed units.

Frenzy reveals an area of 250 dst radius for 30 seconds. The area is revealed immediatly. While the duration of the damage boost for Frenzy depends on the Frenzy rank (10 secs, 20 secs, 30 secs), the map reveal effect will always be those 30 seconds. Frenzy does not detect stealthed units.

**Comment by RisingZH** [comment]
At the competitive level frenzy isn't used to reveal your opponents army at the start as random balanced is used. Where you will see it used is in inf vs other china matchups, particularly inf vs tank or inf vs nuke. As tank and nuke are at a significant disadvantage (and I think always will be due to inherent faction design) the tank/nuke player is incentivised to go for some sort of risky build order (flank/forward wf, wf+af etc) to stand a chance of winning. These builds can work if they catch the inf player off guard or the inf player reacts badly, however the use of frenzy as a scan can and does when used completely remove this element of surprise.

Essentially this is only used by inf in circumstances where they already have a big advantage and so certainly dont need another one. It's a clear remove from me.

**Comment by Madrageeeeee** [comment]
Agree with Rising: mostly used in inf vs china/nuke/tank. Because vet minigunner is vital against usa it isnt really used there (cuz flamers dont work well versus md’s but are great against tank hunters). As it is an advantage for
An already stronger china and not even the intended effect of the ability I would say removing it is only logical.

**Comment by xezon** [comment]
If we disable the inherent scanning ability, does it fix any actual gameplay problems?

**Comment by ExiLe-ZH** [comment]
> If we disable the inherent scanning ability, does it fix any actual gameplay problems?

Yes, mainly improving the mu’s Rising mentioned.

When this ability is used in gameranger (team) games, the enemy also knows your army. It can still spot specific builds though just like Rising’s example, which might affect certain mu’s in either a positive or negative way.

**Comment by xezon** [comment]
USA also has a way to scan on match start, and there it is no problem, or is it?

**Comment by ExiLe-ZH** [comment]
> USA also has a way to scan on match start, and there it is no problem, or is it?

Yes, but it’s very matchup based, whether it’s fair or not.

**Comment by EnigmaZift** [comment]
The Frenzy's purpose is not to reveal an area of the map. I think it's quite cheesy that you can use it like that, and would probably be fixed in a real patch or remaster. 
Isn't China's lack of early scouting made up by the Internet Center?

**Comment by commy2** [comment]
> Isn't China's lack of early scouting made up by the Internet Center?

You will not be able to afford the $2500 + $1000 (+$2500) in 1.04 for an Internet Center in the early game.

**Comment by EnigmaZift** [comment]
Yes but isn't that like a design weakness... they're bad at the early game, good at the late game. I mean lack of early scouting made up by their good late scouting, which literally reveals everything?

**Comment by commy2** [comment]
Ok, so we agree that the Internet Center cannot make up for a lack of scouting **in the early game**.

**Comment by ExiLe-ZH** [comment]
> Yes but isn't that like a design weakness... they're bad at the early game, good at the late game. I mean lack of early scouting made up by their good late scouting, which literally reveals everything?

Bad design. 

Sure the internet center can be built straight after the WF, so same tech tree as USA Strat Center, but it’s a seperate useless/expensive investment, which requires 2 additional investments before you can see the whole map. Satellite I only reveals enemy CC. Activation isn’t even player controlled either.

**Comment by EnigmaZift** [comment]
Then perhaps make the upgrades cheaper. That would be a solution, rather than making the player abuse a GP for a function that is unintentional.

**Comment by Pekaman** [comment]
> When using Frenzy, a unqiue FX and sound is played at the location it was used. At least the sound can be heard by the opposing player (not sure about the FX) if the camera was over the area where Frenzy was used, when it was used.

From what i have experienced in game the fx are visable if you are hovering over your base at the time of use.

Also removing the scan ability without looking beyond the 1v1 curtain,the ability is less problematic its use in 3v3 2v2 allows a team who have no USA to scout, furthermore in ffas its a double edged sword you use up a gp point on it to scout the map to potentially rush someone also notifying the one being attacked that he has been scanned by a inf.

**Comment by ReLaX82** [comment]
Looking at the purpose only its a bug.
Furthermore as Rising mentioned it just buffs the already strong faction.

So, get rid of this bug.
