### ISSUE TITLE
Should trucks and dozers leave scraps?

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#592]
(Controversial) balance solution to make Techs a little less dangerous when chasing dozers or trucks. Imo it makes no sense either a Tech can upgrade it's gun from units that are not even armed.

This thing alone will probably improve the winrate of China quite a bit since one Super Tech can beat a China single-handedly.

**Comment by EnigmaZift** [comment]
I agree, but a change like this is maybe too drastic?

**Comment by xezon** [comment]
Such change would have direct effect on how GLA vs China is played early and I am not sure if that is for the better.

**Comment by RisingZH** [comment]
They should definitely leave scraps, scraps are a super fun and interesting game mechanic.

The answer is just to reduce the damage of a double scrapped vetted tech. Single scrapped techs are fine and even double scrapped non vetted techs are fine.

I haven't been following the Discord chat really and only checking GitHub; is the idea still to only change unit costs and build times? I would say this is another example of where that won't work.

**Comment by Madrageeeeee** [comment]
I think this has a major effect on gameplay and i wouldnt change it.

this will turn this patch into a similar game experience as 1.06. What happened there is that because very powerful units like vees were nerfed and supertechs were very hard to come by due to no scraps elft behind by trucks was that the gameplay became quite ‘sluggish’ and defense based.

the reason why zero hour can be so quick and turn easily is because of this units. If gla has no chance to do significant damage with supertechs / techs in general then you will get a very defensive game because gla units get shredded out in the open.

seeing the bufs that china has gotten i think this will make china too powerful against gla and it will affect gameplay negatively. 

I think we should at really prevent the game from becoming too static / defensive

Even reducing the damage output of supertechs isnt a good idea imo. With mines / cheaper units and better driving dozers it will already be difficult enough for gla’s especially on large open maps. Also with cheaper units for china the cc keep strat is already more viable

**Comment by RisingZH** [comment]
Interesting post rage. 

I think part of this discussion needs to be should denying scraps with scaffolds still be possible. I'm pretty strongly against scrap deny being allowed even on 1.04 and I believe I'm correct in saying you Rage made it become a thing. 

The only real argument for scrap deny on 1.04 I can get behind is that super techs do just wreck china and they are pretty easy to come by without scrap deny so it does balance the matchup.

I would be interested to hear, do you think the game would still be better with super strong techs and the ability to scrap deny, or more balanced super techs and no scrap deny?


As a side point - units don't leave scraps when killed by tunnels (and I also assume stingers?). This I would definitely call a bug and should be fixed.

**Comment by commy2** [comment]
> As a side point - units don't leave scraps when killed by tunnels (and I also assume stingers?)

GLA buildings will not create scrap. So no scrap from Demo Traps, Tunnels or Scud Storms. Stinger Sites when suicided as Demo General will not create scraps either. **However the Stinger Troopers inside a Stinger Site will actually create scrap when they kill vehicles with their missiles**. See this rejected proposal: https://github.com/xezon/GeneralsGamePatch/pull/89

**Comment by xezon** [comment]
I prefer the Super Technical to remain as super as it has always been. I do believe it is better to not weaken GLA in favor of China, and instead focus on China stuff to make it better!

**Comment by ExiLe-ZH** [comment]
> I think this has a major effect on gameplay and i wouldnt change it.
> 
> this will turn this patch into a similar game experience as 1.06. What happened there is that because very powerful units like vees were nerfed and supertechs were very hard to come by due to no scraps elft behind by trucks was that the gameplay became quite ‘sluggish’ and defense based.
> 
> the reason why zero hour can be so quick and turn easily is because of this units. If gla has no chance to do significant damage with supertechs / techs in general then you will get a very defensive game because gla units get shredded out in the open.
> 
> seeing the bufs that china has gotten i think this will make china too powerful against gla and it will affect gameplay negatively.
> 
> I think we should at really prevent the game from becoming too static / defensive
> 
> Even reducing the damage output of supertechs isnt a good idea imo. With mines / cheaper units and better driving dozers it will already be difficult enough for gla’s especially on large open maps. Also with cheaper units for china the cc keep strat is already more viable

This is indeed one very important concern, but I think there’s different perspective to this aswell.

1. It allows China to play more aggressive or deny map control with truck rushes. I don’t think the game becomes more static, but I think it does guarantee longer games. Don’t we all love longer China vs GLA games where you see nice unit composition's or mass Lix domination?
2. Eco harassment  is just as useful as before, trucks don’t become disposable. Maybe even more important so since China is now more capable of spamming when the eco is rolling.
3. A full Tech RPG without scraps is still no joke, especially when it gets vet 2/3 and heals itself. Sure it can’t kill an infinite amount of units and it may have to retreat, but is it fair in the first place for a single unit to be that strong vs almost anything China can make?

Alternatively, maybe the rate at which a Tech vets up needs to be looked at.

**Comment by ExiLe-ZH** [comment]
> I think this has a major effect on gameplay and i wouldnt change it.
> 
> this will turn this patch into a similar game experience as 1.06. What happened there is that because very powerful units like vees were nerfed and supertechs were very hard to come by due to no scraps elft behind by trucks was that the gameplay became quite ‘sluggish’ and defense based.
> 
> the reason why zero hour can be so quick and turn easily is because of this units. If gla has no chance to do significant damage with supertechs / techs in general then you will get a very defensive game because gla units get shredded out in the open.
> 
> seeing the bufs that china has gotten i think this will make china too powerful against gla and it will affect gameplay negatively.
> 
> I think we should at really prevent the game from becoming too static / defensive
> 
> Even reducing the damage output of supertechs isnt a good idea imo. With mines / cheaper units and better driving dozers it will already be difficult enough for gla’s especially on large open maps. Also with cheaper units for china the cc keep strat is already more viable

Anyways, I guess Super Tech comebacks are less likely to happen when you fail to a China rush and receive alot of damage (have a slow start). So in that sense, yes some games might become more static.

**Comment by RisingZH** [comment]
> > As a side point - units don't leave scraps when killed by tunnels (and I also assume stingers?)
> 
> GLA buildings will not create scrap. So no scrap from Demo Traps, Tunnels or Scud Storms. Stinger Sites when suicided as Demo General will not create scraps either. **However the Stinger Troopers inside a Stinger Site will actually create scrap when they kill vehicles with their missiles**. See this rejected proposal: #89

Ah must have missed that proposal. I can't say I agree with the logic, the scrap is the remains of the vehicle which the gla salvage to upgrade their own vehicles. Why would it make any difference whether a human unit killed the vehicle versus a building/gen power/demo trap?

I also think it is confusing for newer players, if you don't know that when your tunnel gets the last hit a scrap won't be created it just seems like whether a scrap appears is random.

**Comment by commy2** [comment]
I agree, Rising, which is why I wanted to change it^^

Just because it's closed for now doesn't mean it can't be brought up again at a later point.

**Comment by Jundiyy** [comment]
I wouldn't remove the scraps or change the Super Techs. It's quite a big of a change and the unit itself changes games as mentioned above. I prefer buffing weaker armies over changing something else, there could be one 'small' nerf which would keep the Super Tech similar but again I would prefer not to change it at all.
We could add 20% delay between shots from the original, this would mean it takes longer to kill any unit. It would still keep it powerful but would mean it can't take out everything as quick as before.

**Comment by Madrageeeeee** [comment]
@RisingZH yes i introduced scrap denying and it has significantly boosted china’s chances against GLA eversince people started using it i think. 

I just think we might be overdoing it with the china buffs against gla. I dont think china is as bad as people think against gla, especially on bigger maps with multiple oils. 

Yes supertechs can have a large impact but if you can scrap deny it isnt that crazy imba anymore i feel. 

I think with the current buffs china will already stand a good chance so we might risk over-correcting the game.

also its kinda cool in zero hour that with a well microed unit you can still do heaps of damage if you use it well. This makes the game exciting and unpredictable. 

If you dont have quick powerful units in the game anymore it will become a game of chess and positioning armies etc, more like a TF air/gla/stealth game. The finesse with single units is what differentiates 1v1 from team games. 

I understand your point with the scrapdeny, it shouldnt really work that way and is messing with a core game mechanic formgla. Although changing it will also throw off other things. Maurauder strats will become insane (especially in gla vs china/tank) if you dont nerf them as well. 

We all know the joy of getting your triple scrapped maurauder and seeing it shred entire armies or bases. Or the fun of having a supertech kill tons of units on its own because you micro it well. Or your single triple vet humvee that owns infinite amounts of nuke battlemasters. Dont think you want to remove that from the game completely, you just want to make sure it is a rare occurance and can be countered with adequate micro / strats.

**Comment by ExiLe-ZH** [comment]
> @RisingZH yes i introduced scrap denying and it has significantly boosted china’s chances against GLA eversince people started using it i think.
> 
> I just think we might be overdoing it with the china buffs against gla. I dont think china is as bad as people think against gla, especially on bigger maps with multiple oils.
> 
> Yes supertechs can have a large impact but if you can scrap deny it isnt that crazy imba anymore i feel.
> 
> I think with the current buffs china will already stand a good chance so we might risk over-correcting the game.
> 
> also its kinda cool in zero hour that with a well microed unit you can still do heaps of damage if you use it well. This makes the game exciting and unpredictable.
> 
> If you dont have quick powerful units in the game anymore it will become a game of chess and positioning armies etc, more like a TF air/gla/stealth game. The finesse with single units is what differentiates 1v1 from team games.
> 
> I understand your point with the scrapdeny, it shouldnt really work that way and is messing with a core game mechanic formgla. Although changing it will also throw off other things. Maurauder strats will become insane (especially in gla vs china/tank) if you dont nerf them as well.
> 
> We all know the joy of getting your triple scrapped maurauder and seeing it shred entire armies or bases. Or the fun of having a supertech kill tons of units on its own because you micro it well. Or your single triple vet humvee that owns infinite amounts of nuke battlemasters. Dont think you want to remove that from the game completely, you just want to make sure it is a rare occurance and can be countered with adequate micro / strats.

Well if the result is that scraps become too rare, then I agree it takes away some fun dynamics. 

Maybe it could be balanced out again by also removing the scrap deny “ability”, then Techs get a bigger chance of scrapping up when killing a battle unit. Basically go back to old times again where scrap deny wasn’t even a thing.

Though scrap denying on it’s own is also fun. Albeit frustrating when you can’t do because of terrain, no money etc.

**Comment by MTKing4** [comment]
I like the idea of removing scrap from trucks/dozers and removing Scrap deny along with it, the latter which makes no sense at all that a player needs to scafold abuse to Ballance the game while taking away the reward from the player who won the battle 

In the end if not decided, we could just implement this change on a separate branch and add it to the next experimental tournament patch and see how it does practically rather than theorize about it here

**Comment by ExiLe-ZH** [comment]
> 
> 
> I like the idea of removing scrap from trucks/dozers and removing Scrap deny along with it, the latter which makes no sense at all that a player needs to scafold abuse to Ballance the game while taking away the reward from the player who won the battle
> 
> In the end if not decided, we could just implement this change on a separate branch and add it to the next experimental tournament patch and see how it does practically rather than theorize about it here

Would be very good to have a test version of this.

**Comment by commy2** [comment]
^ Test version has arrived.

**Comment by MTKing4** [comment]
Nice! Now we only need some pro games on it :D

**Comment by xezon** [comment]
This is very interesting change indeed.

**Comment by Madrageeeeee** [comment]
Did you think about the impact of removing scrap deny possibilty? 

For example boxed warfactory gets killed by TT, then the tech dies over de spot where the warfactory was, warfactory cannot be rebuild in the same spot to recreate the box untill the scrap dissapears

**Comment by xezon** [comment]
Building can be placed on scrap and it will not vanish. Scrap will disappear after regular timeout.

**Comment by ExiLe-ZH** [comment]
> 
> 
> ^ Test version has arrived.

So with this change, shouldn't units always leave scraps no matter what kills them? To make them more common now that trucks/dozers don't anymore.

**Comment by xezon** [comment]
See also:
* #641

**Comment by ReLaX82** [comment]
After a final decision IF scrap deny is allowed or not we can decide on trucks and dozer leasing scrap.

I would they should, but we can make it harder to get it and limit the damage boost if needed.

**Comment by xezon** [comment]
Vast Majority of posts indicate that this should not be changed. Closing.
