### ISSUE TITLE
Should demobikes / terrorists have a self suicide button?

### ISSUE THREAD

**Issue by Madrageeeeee** [TheSuperHackers/GeneralsGamePatch#614]
It is kinda weird that a unit wearing a suicide vest cannot actually suicide itself at will but has to force fire in order to detonate.

I think this might be a controversial one though as it will make TTing armies all the more easy.

one think that does baffle me though is that the demo general can suicide any unit after the demo upgrade but the units that are actually trained to suicide (demo bikes and terrorists) cannot suicide.

**Comment by xezon** [comment]
On current main branch the Suicide button for Demo Bike has actually already been activated. It was greyed out in the original game. You can now press Shortcut to suicide it. Not so for on-foot Terrorist however.

**Comment by ExiLe-ZH** [comment]
Well, DB's already hit and kill reliably and they are multiple ways to do it:
1. Click and forget. Downside is you might have to retarget or retreat if main target dies, they will have to accelerate again after getting to a stop. Very reliable vs singular units.
2. Guard mode, with this they automatically chase the next unit nearby when the first target dies. They also retaliate and chase the unit they get shot by. Very reliable click and forget method vs groups of units.
3. Chasing units manually till they get taken down and explode. Very reliable with correct micro, just takes more time and focus.

This last one will get easier, where you don't have to keep chasing, you just press the button. It isn't a huge deal for DB's but isn't it all easy enough already and do we need this?

**Now for normal terrorists it is a huge deal.
Just imagine how much easier it will be to TT armies. Right now it's "hard and an art" to hit big moving armies which Boycah has mastered and is known for. Now when this becomes as easy as pressing a hotkey I predict this will become very meta vs massed armies in high level games.**

I'm not a fan at all and I think this obvious feature is left out for a reason.

**Comment by Jundiyy** [comment]
Terrorists = no, instant TT on anything, you have to have some nice lag or be real slow not to be able to select and press 'i'.

Demo Bikes, I don't think they should, even though the original Demo Bike does have a greyed out button, I think sometimes there are 'bugs' which should be considered as part of the game, mainly due to helping with balance, we should edit the code to make it look like it should be this way. Such as in this case, Demo Bikes might have the button but are very powerful, so to fix the button would make them even more powerful and possibly throw balance. In such a case, we should just remove the button entirely rather than fix and the code should show this was done on purpose so it doesn't look like a bug.

**Comment by Madrageeeeee** [comment]
agree with the above comments.

figured i'd bring it up, but definitely controversial

**Comment by xezon** [comment]
Suicide button on demobike has been disabled again.
* #680 
We can close this report, as there is no urgent need to make Terrorist and Bikes stronger, even if it is logical.
