### ISSUE TITLE
Microwave Tanks Bugging Out On Stinger Sites

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#637]
The vGLA Stinger Troopers are damaged individually by Microwave tanks. After they have been killed, there is a strange damage effect on the Stinger Site.

The non vGLA Stinger Troopers are collectively damaged instead. The strange damage effect exists already before the troopers have been killed.

# vGLA
https://user-images.githubusercontent.com/6576312/184554205-87c7e88b-077a-4477-804d-8c682560f387.mp4

# Tox (same for Demo and Stealth)
https://user-images.githubusercontent.com/6576312/184554199-96957291-8f6d-4a8f-b4bd-bfac354cc5f8.mp4

Note: For the records I tricked the AI to not shoot on me, otherwise there would've been too much distraction going on.

**Comment by ZekeDlyoung** [comment]
Rather than Microwave tanks bugging out, this seems more like incorrect damage FX for Stinger Sites when hit by MICROWAVE damage.

It seems only the VGLA Stinger Site properly passes the damage to the Stinger Soldiers, while the other faction Stinger Sites take the damage themselves (soldiers still die because it's an AoE weapon)

**Comment by commy2** [comment]
I know how to fix this, but I just ran out of time yesterday.
