### ISSUE TITLE
Should GLA Marauder no longer require a General Promotion?

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#646]
Should GLA Marauder no longer require a General Promotion? It is not used much.

### Proposal 1
Reduce build time of Marauder to make it more attractive.

**Comment by ReLaX82** [comment]
GLA Marauder in current state can mutate to enormous strength (firepower) if scrapped up as we all now, unstoppable early game sometimes.

As I don't think scrap deny will be forbidden, I would like to see no gen point and reduce % if scrapped up.

**Comment by ExiLe-ZH** [comment]
It should cost a promotion, otherwise it's a 100% no-brainer of going for the Technical Veterancy.

It's not that you never see Marauders either, they are used, especially vs Tank as it's easier to hold with them vs the first dragons because you don't need to wait for the Scorp Rocket Upgrade.

You also see them used when the enemy player is hunted, because they then can't scrap deny anymore.

If we want to see Marauders used more it would be better to make the production time a bit shorter, because this is the main reason why you still see Scorp Spam more often, even if the Marauder was used as first unit.

**Comment by Stubbjax** [comment]
> It should cost a promotion, otherwise it's a 100% no-brainer of going for the Technical Veterancy.

That's precisely part of the problem - Technical Training is already a no-brainer because Marauders aren't worth the GP. The idea is to make them more viable, and an effective way of doing that without making them even more powerful is to remove the GP prerequisite.
> It's not that you never see Marauders either, they are used, especially vs Tank as it's easier to hold with them vs the first dragons because you don't need to wait for the Scorp Rocket Upgrade.
> 
> You also see them used when the enemy player is hunted, because they then can't scrap deny anymore.

The extra 6 seconds of production time for a Marauder pretty much negates that though. I'd be interested to see some high-level games where they are used effectively. In my own experience, I've seen them used in maybe less than 1% of high-level 1v1 matches and even less in team games.
> 
> If we want to see Marauders used more it would be better to make the production time a bit shorter, because this is the main reason why you still see Scorp Spam more often, even if the Marauder was used as first unit.

Reducing the production time would definitely help with the situation you mentioned, because a rocket-less Scorpion is actually the better choice for destroying a Dragon due to those 6 extra seconds (in addition to other benefits such as faster scouting). But even with a shorter build time, spending a GP in order to kill an initial Dragon or two slightly faster is a very niche purpose that would still see Marauders more or less unused in comparison to Scorpions, which are much more versatile and cost-effective units beyond the rocket upgrade.

**Comment by MTKing4** [comment]
No

**Comment by ExiLe-ZH** [comment]
> > It should cost a promotion, otherwise it's a 100% no-brainer of going for the Technical Veterancy.
> 
> That's precisely part of the problem - Technical Training is already a no-brainer because Marauders aren't worth the GP. The idea is to make them more viable, and an effective way of doing that without making them even more powerful is to remove the GP prerequisite.
> 
> > It's not that you never see Marauders either, they are used, especially vs Tank as it's easier to hold with them vs the first dragons because you don't need to wait for the Scorp Rocket Upgrade.
> > You also see them used when the enemy player is hunted, because they then can't scrap deny anymore.
> 
> The extra 6 seconds of production time for a Marauder pretty much negates that though. I'd be interested to see some high-level games where they are used effectively. In my own experience, I've seen them used in maybe less than 1% of high-level 1v1 matches and even less in team games.
> 
> > If we want to see Marauders used more it would be better to make the production time a bit shorter, because this is the main reason why you still see Scorp Spam more often, even if the Marauder was used as first unit.
> 
> Reducing the production time would definitely help with the situation you mentioned, because a rocket-less Scorpion is actually the better choice for destroying a Dragon due to those 6 extra seconds (in addition to other benefits such as faster scouting). But even with a shorter build time, spending a GP in order to kill an initial Dragon or two slightly faster is a very niche purpose that would still see Marauders more or less unused in comparison to Scorpions, which are much more versatile and cost-effective units beyond the rocket upgrade.

I already don't like how you have 1 option with Stealth because the alternative is useless aswell and even still so with the cooldown buff. You're not gonna skip Tech Vet either to save the promotion point for a level 3 ability.

Making them more viable is something I'm all for, but having them always available just doesn't feel right. 

Like I said already, there ARE situations where they are viable and a good replacement (early game) for Scorps. Like on bigger maps where it takes longer for Tank to reach your tunnels/base. Scuba is a player for instance who actually spams them from to time to time.

Also again, it would make hunting even more effective since Marauders are absolutely fantastic units to make after hunting your opponent.

**Comment by Jundiyy** [comment]
I don't think this should be changed, Marauders are powerful units but need help to get there, just like a Technical to Super Tech. They aren't used in all situations and that's for 2 reasons, firstly the micro part of it, as you have to work your way to upgrading each one, it's just much easier to use a group of Scorpions with Rockets and A move them. And secondly the build time, we did decrease this in a previous version of the patch but then reverted it. We could always try that again.

**Comment by DoMiNaToRuk2** [comment]
GLA is pretty strong all round as it is. If anything reduce marauder build time by 1 second only

**Comment by xezon** [comment]
Added 1 proposal.

**Comment by DoMiNaToRuk2** [comment]
Should try 0.5 or 1.0 sec reduction. Marauders are already useful in current game so any reduction could tip the balance too much and make it too OP. Like making nuke battlemasters useless early game

**Comment by xezon** [comment]
Scraps can no longer be removed by scaffolds, which in turn also helps the Marauder: #1676

**Comment by xezon** [comment]
Nothing to do here for now.
