### ISSUE TITLE
Range bug - tow vees/quads/gats

### ISSUE THREAD

**Issue by Madrageeeeee** [TheSuperHackers/GeneralsGamePatch#671]
Probably already reported. But there is a range bug with anti air units when they are targeting chinooks/lixes and straight afterwards ground units. Range is considerably larger then.

**Comment by ECBVovin** [comment]
This can be fixed by changing the AIUpdateInterface module's AutoAcquireEnemiesWhenIdle line. To fix, the line should read:
AutoAcquireEnemiesWhenIdle = NotWhileAttacking Yes Stealthed

Order is important. This will prevent the unit from targeting ground units when moving to engage an air unit you told it to attack. I'm not sure if this fixes all instances, but it helps a great deal.

**Comment by xezon** [comment]
This bug has been fixed already with
* #285
