### ISSUE TITLE
GLA Rocket Buggy has large discrepancy between EXP given and required

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#719]
GLA Rocket Buggy has unusual large discrepancy between EXP given (150) and required (800). Does this need tweaking?

Perhaps scraps level ups play into this.

```
Demo_GLAVehicleRocketBuggy
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800    ;Experience points needed to gain each level

Demo_GLAVehicleScudLauncher
  ExperienceValue    = 50 50 100 150  ;Experience point value at each level
  ExperienceRequired = 0 100 200 400  ;Experience points needed to gain each level

ChinaVehicleInfernoCannon
  ExperienceValue    = 50 50 100 150  ;Experience point value at each level
  ExperienceRequired = 0 100 200 400  ;Experience points needed to gain each level

ChinaTankBattleMaster
  ExperienceValue    = 100 100 200 400 ;Experience point value at each level
  ExperienceRequired = 0 200 300 600   ;Experience points needed to gain each level

GLATankMarauder
  ExperienceValue    = 100 100 200 300 ;Experience point value at each level
  ExperienceRequired = 0 200 300 600   ;Experience points needed to gain each level

AmericaTankPaladin
  ExperienceValue        = 100 100 200 400 ;Experience point value at each level
  ExperienceRequired     = 0 200 300 600 ;Experience points needed to gain each level

AmericaVehicleTomahawk
  ExperienceValue    = 50 50 100 150  ;Experience point value at each level
  ExperienceRequired = 0 200 400 800  ;Experience points needed to gain each level

ChinaVehicleNukeCannon
  ExperienceValue    = 50 100 200 400  ;Experience point value at each level
  ExperienceRequired = 0 400 600 1000  ;Experience points needed to gain each level

ChinaTankOverlord
  ExperienceValue    = 200 200 400 600 ;Experience point value at each level
  ExperienceRequired = 0 400 600 1200  ;Experience points needed to gain each level
```

**Comment by xezon** [comment]
To me it looks as if GLA Rocket Buggy could be reduced a bit and GLA Scud Launcher increased a bit.

**Comment by commy2** [comment]
My gut feeling is that Buggies work fine as they are. We would have to check how veterancy affects the counters to buggies. E.g. how much easier is it for a flock of  vetted vs unvetted Buggies to survive a Mig strike.

**Comment by Jundiyy** [comment]
I think it's fine, Rocket Buggies always chew off units from a distance. Scud Launchers also do but they can't hit and run, they do pop from Tunnels, but Rocket Buggies can go across the map safely.

**Comment by ExiLe-ZH** [comment]
As mentioned in the tomahawk topic, I don't think buggies need any improvement.

Guess you could balance it out by copying the Marauder values, since Buggies can be hard to catch (deserving greater award for killing them), but at the same time it's also easy to overstep and lose Buggies.

Talking about Marauders, why is vet3 only 300 points? While at that point they're very likely to be scrapped up and super hard to kill without Air units.

**Comment by xezon** [comment]
Looks safe to me to adjust that one value for Marauder. Can be identical to Paladin.

**Comment by xezon** [comment]
How about

## Before
```
Demo_GLAVehicleRocketBuggy
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 200 400 800    ;Experience points needed to gain each level

Demo_GLAVehicleScudLauncher
  ExperienceValue    = 50 50 100 150  ;Experience point value at each level
  ExperienceRequired = 0 100 200 400  ;Experience points needed to gain each level
```

## After
```
Demo_GLAVehicleRocketBuggy
  ExperienceValue       = 50 50 100 150    ;Experience point value at each level
  ExperienceRequired    = 0 150 300 600    ;Experience points needed to gain each level

Demo_GLAVehicleScudLauncher
  ExperienceValue    = 50 50 100 150  ;Experience point value at each level
  ExperienceRequired = 0 150 300 600  ;Experience points needed to gain each level
```

This would also make more sense to me in relation to Infernal Cannon and Nuke Cannon.
The total sum of Experience Required across both units is identical to the original distribution.

**Comment by ExiLe-ZH** [comment]
I personally don't think any sort of buff is needed for Buggies.

Neither a nerf for Scuds, I think they're fine as is. Or is the vetting speed really a problem? Never experienced that in my games, but I don't play FFA/2v2v2.

**Comment by xezon** [comment]
You generally don't see many 3 star buggies. But 3 star SCUD Launcher are relatively common in Bunker games with Tunnel poppings. Consolidating their values would even the distibution I think.

In the given suggestion above the total sum of Experience Required across both units is identical to before.

**Comment by ExiLe-ZH** [comment]
> You generally don't see many 3 star buggies. But 3 star SCUD Launcher are relatively common in Bunker games

That is true, but should think about consequences of the changes when you do see more vet3 buggies on the field. 

For Scuds (mainly demo ones) I could imagine them getting too strong too fast vs Tank for example when it's a bunker game, so this one might be a fair case.

**Comment by Jundiyy** [comment]
You generally see a lot more Buggies on the battlefield, having them vet up faster would be more problematic.
You do see Scuds at times but they are not spammed. So even at vet they aren't as much as a problem compared to Buggies.
Really don't think Buggies need touching. Having lots of vet 3 Buggies running around would he chaotic.

**Comment by commy2** [comment]
> For Scuds (mainly demo ones)

vGLA and Demo Scud Launchers have the same stats, just different visuals.

**Comment by ExiLe-ZH** [comment]
> > For Scuds (mainly demo ones)
> 
> vGLA and Demo Scud Launchers have the same stats, just different visuals.

wow big noob <

**Comment by ExiLe-ZH** [comment]
![Command   Conquer - Generals Screenshot 2022 08 16 - 22 44 10 94](https://user-images.githubusercontent.com/32326277/184993907-02433da2-1eee-4d28-9033-01078ca76711.png)

In this random GLA mirror today I was quite a bit faster at getting Buggies than my opponent, this gave me the opportunity to pick off a couple of his tunnels and a supply, that made me get vet 1 & 2 Buggies pretty fast. 400 XP doesn't seem all that unobtainable when you start chipping off buildings.

He tried building up his own Buggy army but there really was no fighting back against my vetted Buggies, they picked off his Buggies too fast.

If he didn't quit, I'm sure I would've gotten vet 3 Buggies pretty easy if the requirement was 600 XP, I would've gotten more vet 2 Buggies aswell with the requirement of 300 XP and that makes it easier to snowball to vet 3 aswell.

So yea my personal conclusion: I think the only thing this change will do, is giving the opportunity to snowball (>win) faster.

*Another thing about the snowball effect, the more this effect is present, the greater skill gaps will be, because the better player will be rewarded more or faster for his micromanagement or whatever skills they are.

**Comment by Stubbjax** [comment]
It is important to note that your opponent played terribly and the outcome was pretty clear before buggies even came into the picture. The results shown in your match appear to be typical of any eco boom + steamroll. If you had done the same thing with other units such as Humvees, you would have witnessed the same (and a likely faster) outcome.

I think you should carefully rewatch the replay and consider how ~quickly~ slowly your buggies ranked up in relation to what they destroyed, especially in comparison to other units. It's also important to note _how_ your buggies ranked up, as most of their initial ranks were achieved via collecting salvage crates. It also made no difference whether your buggies were vetted in the buggy fights - the player with the better micro and/or numbers will almost always win in these types of engagements. (Don't forget that the opponent also acquires opportunities to get more xp by killing ranked units.) Your personal conclusion seems to imply that unit ranking in general is a bad mechanic that would be better off removed, because its entire function is exactly as you describe. You are correct that it amplifies the difference between skill levels or, more explicitly, the impact of good vs poor play. But why is that a bad thing? Why should that distinction be nullified when it comes to Rocket Buggies?

Anyway, your example does not demonstrate any meaningful impact as a result of vetted buggies, and I don't see how a slight reduction in the ranking requirements would realistically change this. I think any perceived negative impacts of such a change are vastly exaggerated. It just feels wrong that a single buggy has to destroy 8 tunnels (ultra rare) to reach heroic status, and slightly less wrong that it would take 6 (still ultra rare). Rocket Buggies are one of the tougher units to use and it would be nice if the bar was set a little lower so that players were better rewarded for doing so. There are far more egregious / realistic examples of unit ranking affecting the outcomes of matches, such as quads and technicals.

**Comment by xezon** [comment]
A group of 6 buggies with 2x Vet0, 2x Vet1 and 2x Vet2 does not look like conclusive evidence for OP veterancy to me. Over how many scraps did they drive?

**Comment by MTKing4** [comment]
I also think buggies don't need a buff, we shouldn't be messing with balance here and there and call it a slight change, it will add up, and it will give us a headache later on when we affect certain matchups later on unnecessarily when they were just fine

 Consistency argument isn't really that strong here, yes buggy is a ranged unit, but it's fast and agile, it'd more likely compare it to a mig than an artillery unit, because they compensate the lack of air superiority for GLAs, they have similar use cases, but are much better at their job and easier to preserve

**Comment by commy2** [comment]
A Mig vets up at 100, 200 and 400 xp, so twice as fast as a 1.04 Buggy.
One "benefit" of the Buggy is that it is one of the two GLA vehicles that don't scrap up. Meaning you have a 25% chance to vet up when driving over a scrap pile.

**Comment by ExiLe-ZH** [comment]
> A Mig vets up at 100, 200 and 400 xp, so twice as fast as a 1.04 Buggy. One "benefit" of the Buggy is that it is one of the two GLA vehicles that don't scrap up. Meaning you have a 25% chance to vet up when driving over a scrap pile.

Another benefit of the Buggy is that it can be used much more frequently. Migs have a lot of down time.

**Comment by MTKing4** [comment]
Mig has high reload time though, buggy can do it all night long, with more Rockets as well

**Comment by xezon** [comment]
We would need proof that the change is detrimental. By the raw numbers presented from unit, the XP adjustment is reasonable.

**Comment by ExiLe-ZH** [comment]
> We would need proof that the change is detrimental. By the raw numbers presented from unit, the XP adjustment is reasonable.

Buggy is an unique unit, so comparing raw numbers with other units doesn't say all that much. Please bring evidence that Buggies in the field suffer from low veterancy potential and that it hurts their performance.

**Comment by xezon** [comment]
1 Buggy needs to kill 16 Humvees to reach Vet3.

**Comment by ExiLe-ZH** [comment]
I'm very well aware of that statistic by now, why do you guys keep ignoring the fact that they vet up in other ways aswell? Or keep insisting that this is irrelevant in real matches?

Like a Buggy could collect 2 scraps, kill 1 firebase, then how many Vee kills are left required?

Plus regarding Vees, we should first look into the whole passenger EXP thing, because I agree killing a full Vee is not rewarded nearly enough.

**Comment by Stubbjax** [comment]
>
> Buggy is an unique unit, so comparing raw numbers with other units doesn't say all that much. Please bring evidence that Buggies in the field suffer from low veterancy potential and that it hurts their performance.

It is absolutely reasonable to compare the numbers with units of similar calibre based on destruction potential / damage output. That's a fundamental rule of the ranking mechanic.

Generally, as a unit's damage output or survivability increases, so does the xp that unit requires or provides. (This is also explicitly reflected by the fact that units acquire value as they rank up.) Both a Quad Cannon and Scorpion can kill a tunnel faster than a Rocket Buggy (with the +100% ammo upgrade), and a buggy will lose to most vehicles in a one on one fight if left alone. So in terms of damage output, it seems fair to say that buggies aren't winning any awards. As damage output is almost always the driving factor in determining how fast a unit ranks up, and buggy damage output is no better (and often worse) than many other vehicles, there is a strong case for the original values not making sense.

Survivability, on the other hand, is a bit trickier to assess. Rocket Buggies are incredibly fragile and are easily killed by almost every unit in the game. However, they are also quite agile, have a large attack range and are often not far from a tunnel to which they can quickly escape. Whether this makes them high or low survivability units is debatable. Nevertheless, with this consideration in mind, it seems reasonable to deduce that Rocket Buggies do have significantly higher survivability in relation to Tomahawks and Inferno Cannons, so it might make sense to increase their xp value in addition to the lowered requirements. Such a change could help reduce or eliminate any perceived negativity by counterbalancing the reduced xp requirements with increased xp values, and reduce the potential for the change to come across as a direct buff.

>
> I'm very well aware of that statistic by now, why do you guys keep ignoring the fact that they vet up in other ways aswell? Or keep insisting that this is irrelevant in real matches?

I'm fairly sure I've mentioned that they can also rank up via salvage crates several times. Or do you mean the Humvee-specific example? Because I only used that to demonstrate how extreme the requirements are (and because Humvees are the Rocket Buggy's primary source of protein). I think your example of the GLA mirror perfectly demonstrated how ~ir~relevant buggy ranking is in real matches.

> 
> Like a Buggy could collect 2 scraps, kill 1 firebase, then how many Vee kills are left required?

If the scraps only provide money, then 1 Firebase + 12 Humvees (1 Firebase is equivalent to 4 Humvees). If both scraps give ranks to elite status, then 1 Firebase + 4 Humvees. And don't forget, this is for _one buggy_, which makes little difference in their typical numbers. For comparison, a Quad Cannon achieves elite status from destroying 1 Firebase and then heroic status from an additional Humvee.

>
> Plus regarding Vees, we should first look into the whole passenger EXP thing, because I agree killing a full Vee is not rewarded nearly enough.

While I certainly agree and it would be nice, such a change would have _far_ greater implications on balance. Though I do find the tradeoff decision between evacuating the vehicle and getting some more damage in vs denying the opponent the passenger xp to add quite an interesting dynamic. I don't believe this is possible without engine changes.

**Comment by commy2** [comment]
>Like a Buggy could collect 2 scraps, kill 1 firebase, then how many Vee kills are left required?

On average 10, most likely 10 (56% of worlds), median 8, minimum 4 (6%), maximum 12 (37%). ^^

**Comment by xezon** [comment]
Also keep in mind we helped USA, China, GLA by lowering XP kill rewards of Tanks (Crusader, Paladin, Microwave, Battlemaster, Marauder). Perhaps USA Avenger needs another look, as that still grants the super hefty 100 100 200 400 which I find quite astonishing.

**Comment by ExiLe-ZH** [comment]
> Generally, as a unit's damage output or survivability increases, so does the xp that unit requires or provides. (This is also explicitly reflected by the fact that units acquire value as they rank up.) Both a Quad Cannon and Scorpion can kill a tunnel faster than a Rocket Buggy (with the +100% ammo upgrade), and a buggy will lose to most vehicles in a one on one fight if left alone. So in terms of damage output, it seems fair to say that buggies aren't winning any awards. As damage output is almost always the driving factor in determining how fast a unit ranks up, and buggy damage output is no better (and often worse) than many other vehicles, there is a strong case for the original values not making sense.
> 

On it's own a Buggy definitely doesn't win any awards, however like you mentioned yourself before it's an unit of a pack, so when you have a few, the concentrated power is very strong. Damage output is undeniably one of their main strengths.

It depends on the matchup aswell, vs China Buggies are not that useful since ECM's effectively makes the damage output insignificant. Versus USA the damage output is very strong though, as the majority of units have very little armor vs Rockets.
In GLA mirrors they can pick off any vehicle very quickly awell, including highly armored Busses. Damage output certainly shouldn't be underestimated.

> Survivability, on the other hand, is a bit trickier to assess. Rocket Buggies are incredibly fragile and are easily killed by almost every unit in the game. However, they are also quite agile, have a large attack range and are often not far from a tunnel to which they can quickly escape. Whether this makes them high or low survivability units is debatable. Nevertheless, with this consideration in mind, it seems reasonable to deduce that Rocket Buggies do have significantly higher survivability in relation to Tomahawks and Inferno Cannons, so it might make sense to increase their xp value in addition to the lowered requirements. Such a change could help reduce or eliminate any perceived negativity by counterbalancing the reduced xp requirements with increased xp values, and reduce the potential for the change to come across as a direct buff.
> 

You're right about the survivability, it also depends on the matchup again though. USA doesn't have that many counters vs Buggies, Burton is one of the few, but he usually can only pick off a few. Other than that, the survivability is very good if the player doesn't overextend during engagements. Tomahawks are also a good counter (to scare Buggies away, especially combined with Avengers), however it hurts USA's mobility alot, Buggies can be used everywhere around the map to cause damage. This makes it hard for USA to be strong offensively and defensively at the same time.

In GLA mirrors Buggy survival is alot more volatile, when both players take alot of risk of engaging each other with equal numbers, vetted and non vetted Buggies will die alike (HP bonus doesn’t increase survival much in such fights). The outcome of Buggy engagements are mostly about quantities + micro (who switches targets most efficiently). I wouldn't say veterancy is completely irrelevant though (like you claimed in the other argument), because when one player already has the upperhand quantity wise, then you often see this snowball effect where he becomes unstoppable, the increased damage output of vetted Buggies definitely adds to this effect. It makes up for better engagements as the increased damage output allows for faster pick offs, which indirectly saves Buggy lives again.

> If the scraps only provide money, then 1 Firebase + 12 Humvees (1 Firebase is equivalent to 4 Humvees). If both scraps give ranks to elite status, then 1 Firebase + 4 Humvees. And don't forget, this is for _one buggy_, which makes little difference in their typical numbers. For comparison, a Quad Cannon achieves elite status from destroying 1 Firebase and then heroic status from an additional Humvee.
> 

Don’t forget picking off Vetted units also makes it gain XP faster, this is a reason why getting USA’s Field Training upgrade isn’t always a great idea, it could potentially be XP donation.

I think Quad Cannon vetting up so fast is actually one of the big balance problems in ZH, I hope and I’m pretty sure the new damage model will balance it out better.

**Overall, with this change I worry most about GLA vs USA balance, the late game is just very tricky for USA. Survival + damage output for Buggies are both very good in this matchup. In GLA mirrors the impact is less significant for sure indeed.**

**Comment by xezon** [comment]
What you describe sounds more like a problem with USA counters then though, and not a problem with Rocket Buggy XP. Why cripple Rocket Buggy if the better logical step is to make USA planes, the natural counter of Buggys, suck less. Namely expensive Raptor and expensive Comanche.

**Comment by ExiLe-ZH** [comment]
> What you describe sounds more like a problem with USA counters then though, and not a problem with Rocket Buggy XP. Why cripple Rocket Buggy if the better logical step is to make USA planes, the natural counter of Buggys, suck less. Namely expensive Raptor and expensive Comanche.

Yes and I prefer to look into this first. That should be the logical order of things right?

XP change still indirectly makes the Buggy stronger because that's all that veterancy does, simple as that. And you make this happen 25% faster.

Btw, I just had an insight that the increased snowball effect might actually also positively influence some GLA mirrors, since alot of them become very slow late game when both players are huge.
