### ISSUE TITLE
China Mig has relatively long reload time when parked on Airfield

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#747]
China Mig has relatively long reload time when parked on Airfield. Is this ok?

Aircraft reload time comparison:
```
Raptor             : 8 seconds
Mig                : 8 seconds
Mig + Black Napalm : 2 seconds
Mig + Nuke Missile : 2 seconds
King Raptor        : 2 seconds
Stealth Fighter    : 8 seconds (no change with Bunker Buster)
Aurora             : 5 seconds (including Aurora Alpha)
```

**Comment by Jundiyy** [comment]
I don't have a problem with keeping the same or reducing a bit. But my fear is, if we change other bugs which make China better then this one shouldn't be touched till we test to see the results. Just in case it stacks up too much.

Otherwise can reduce it to 6 secs.

**Comment by commy2** [comment]
Added more info to OP.

**Comment by xezon** [comment]
Looks to me a slight buff from 8 to 6 or 5 seconds looks totally reasonable. It is nothing that will turn the tides. Just makes it a bit more convenient.

**Comment by RisingZH** [comment]
I think even going to 4 seconds would be reasonable, so that it gets halved by black napalm and is half that of a normal raptor (on the basis it only has 2 missiles compared to 4).

Would be an interesting one to test, at the moment wf/af isn't very good vs usa or gla as the migs aren't good enough to stop techs/vees pre-bn and researching bn ties up your wf for too long. If this is enough to allow you to get a couple more gats/flamers out before researching bn, could make for some interesting strategies and improve china's options.

**Comment by ExiLe-ZH** [comment]
> I think even going to 4 seconds would be reasonable, so that it gets halved by black napalm and is half that of a normal raptor (on the basis it only has 2 missiles compared to 4).
> 
> 
> 
> Would be an interesting one to test, at the moment wf/af isn't very good vs usa or gla as the migs aren't good enough to stop techs/vees pre-bn and researching bn ties up your wf for too long. If this is enough to allow you to get a couple more gats/flamers out before researching bn, could make for some interesting strategies and improve china's options.

Would also improve chinas vs inf alot, because they're actually good counter vs dual wf outpost and flamer spam, but it's often hard or even impossible to stop the quantities due to reload time. When Inf reaches the airfield it's instantly gameover.

2 secs would be too effective though since black napalm isn't much needed like it is vs Vees.

**Comment by MTKing4** [comment]
4s seem reasonable, and if proven too strong make it 6
