### ISSUE TITLE
China Hacker is vulnerable and provides insufficient income

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#754]
China Hacker is vulnerable. Toxins, Snipers, Bullets and crushes take them out in no time. There can only be one Internet Center to protect 8 of them. On top of that China Hacker appears to not give sufficient income in late game. China seems to struggle making ends meet, especially for China Tank General.

## Some Information on USA, China, GLA economy
https://www.gamereplays.org/cnczerohour/portals.php?show=page&name=tip-of-the-week-105-secondary-economy

## Related issues
* #223
* #689
* #753

## Stats
```
- Hackers cost $625, build-time 20 sec (Black Market: $2500, 60 sec; SDZ: $2500 45 sec, 4 power)
- Tank Hackers cost $780 instead of $625 (25% more expensive)
- Inf Hackers are stealthed and spawn at vet 1, have 40% armor vs poison and radiation

- No XP awarded for: hacking vehicles, hacking buildings
- XP awarded for every cash hack: 1 point
- cash hack XP does NOT count towards the player XP
- XP required for vet1/vet2/vet3: 100 300 500
- cash per cash hack vet0/vet1/vet2/vet3: $5, $6, $8, $10
- time between cash hacks: 2 seconds
- 1.8 seconds while in Internet Center (10% faster)
- 1.6 seconds while in Internet Center for Super Hackers (20% faster)
- this means time required for:
        Hacker          Super Hacker    Hacker in IC    Super Hacker in IC
vet1:   3 min 20 sec    0 min           3 min           0 min
vet2:   10 min          6 min 40 sec    9 min           5 min 20 sec
vet3:   16 min 40 sec   13 min 20 sec   15 min          10 min 40 sec
```

### Proposal 1
Decrease Hacker build cost.

### Proposal 2
Decrease China Tank Hacker cost only, for example from $780 to $625.

### Proposal 3
Decrease China Hacker build time, for example from 20s to 15s.

### Proposal 4
Add stealth for China Hackers while hacking.

### Proposal 5
Add stealth for China Hackers while hacking, beginning at Vet 1.

### Proposal 6
Add stealth for China Hackers always.

### Proposal 7
Add stealth for China Hackers always, beginning at Vet 1.

### Proposal 8
Increase Hacker cash rewards.

### Proposal 9
Increase Hacker robustness against attacks.

### Proposal 10
Increase Hacker movement speed.

### Proposal 11
Reduce Hacker noise.

### Proposal 12
All China Hackers start hacking automatically when idle to cut the time they do nothing. Perhaps gated by a toggle ability.

### Proposal 13
All China Hackers hack cash all the time, even when walking around.

### Proposal 14
Remove the starting veteran rank from Super Hacker.

### Proposal 15
Change Hacker experience requirements, for example from [100 300 500] to [100 200 300]

### Proposal 16
Boost the hack rate bonus from the Internet Centre, for example from 1800ms per hack to 1600ms per hack.

### Proposal 17
Add Satellite Hack III upgrade in Internet Center to grant stealth ability to Hackers.

### Proposal 18
Reduce the Laptop pack and unpack duration of Hacker.

### Proposal 19
Super Hacker reaches Vet 2 at the same or closer total time as regular Hacker does.

### Proposal 20
Hackers can hack cash inside Bunkers and civilian structures.

**Comment by xezon** [comment]
An economy comparison with numbers between USA, China and GLA would be good. Money invested VS income generated.

**Comment by Jundiyy** [comment]
I have it written in this video if it helps.
https://youtu.be/SGbry3QNssw

**Comment by MTKing4** [comment]
I think to start off, all hacker costs should be the same, i propose $500، or the default price which is $625

**Comment by ExiLe-ZH** [comment]
Another proposal:

Instead of 'hack now' ability, replace this with a 'hack when idle' ability. The hacker automatically starts to hack after like 10 seconds. When pressing stop (or when pressing the hotkey/controlbar icon) the ability will be deactivated so you can move the hacker at any time without needing to wait for any animations.

Ability should be activated automatically when coming out of the barracks, since dropzones and markets can be left unattended aswell.

**Comment by ExiLe-ZH** [comment]
> I think to start off, all hacker costs should be the same, i propose $500، or the default price which is $625

I agree, 500 also sounds reasonable since they are so much more vurnerable than markets, while generating about as much (in group of 4). Being able to make 5 hackers for the same investment sounds fair. (Should also remember GLA has Cash Bounty, Cash Hack doesn't balance this out even remotely).

**Comment by MTKing4** [comment]
I think a better one would be hacker hacking all the time, even while moving 😄 

and when left idle he'll open up his laptop, consider it that he started the hack in the barracks and put the computer on idle.

Hacker created a phishing website and a bot is sharing the link everywhere 😄 

I'm serious, i know it looks stupid but i think that's the only way he'd be an equal to BMs and SDZs

**Comment by Jundiyy** [comment]
We already tested Hacker prices and build times, $500 would be way too cheap, especially if you are also giving the IC boost. And mixing in cheaper units which will most likely be needed. $550 was the last test we did with a build time reduction from 20s to 15s. This felt really good for all Chinas, more money with cheaper units. Inf Hackers were $600/17.5s as far as I remember.

Anyone can watch the last 1.04+ tournament/random games or download it and test to see how it went.

**Comment by MTKing4** [comment]
> We already tested Hacker prices and build times, $500 would be way too cheap, especially if you are also giving the IC boost. And mixing in cheaper units which will most likely be needed. $550 was the last test we did with a build time reduction from 20s to 15s. This felt really good for all Chinas, more money with cheaper units. Inf Hackers were $600/17.5s as far as I remember.
> 
> Anyone can watch the last 1.04+ tournament/random games or download it and test to see how it went.

We haven't agreed on reducing bt and cost for china units yet and we might not need that after all the other buffs we will give.

so i think it is fine if they were this cheap, also i understand why inf hackers are more expensive but they shouldn't be built slower i feel

**Comment by ZekeDlyoung** [comment]
> I think a better one would be hacker hacking all the time, even while moving 😄
> 
> and when left idle he'll open up his laptop, consider it that he started the hack in the barracks and put the computer on idle.
> 
> Hacker created a phishing website and a bot is sharing the link everywhere 😄
> 
> I'm serious, i know it looks stupid but i think that's the only way he'd be an equal to BMs and SDZs

Neah, while on the move he switches to his phone 🙃 

I vote for this as well, the Operation Firestorm mod did this and it does significantly improve China economy. This change does mean that Hackers won't be able to gain veterancy and gain more money while hacking anymore, because the way they work will have to be changed, but the money they gain inside the internet center could be increased to compensate, also the money gained from not needing to constantly micro Hackers is significant.

**Comment by xezon** [comment]
> I think a better one would be hacker hacking all the time, even while moving 😄

It is very clever to consider the idle time the Hacker has when moving and not microing. He requires a fair amount of labor to setup, contrary to GLA and USA money. It looks reasonable to me to have an ability that could make him auto hack as soon as he reaches his destination. That means you could set the Hacker hacking and move to his target destination in one go as soon as he leaves the barracks and forget about it.

I would imagine the hack start/stop button would then become 2 buttons for 2 modes like the Rifle + Flashbang buttons for the USA Ranger.

### Proposal 12
All China Hackers start hacking automatically when idle to cut the time they do nothing. Perhaps gated by a toggle ability.

### Proposal 13
All China Hackers hack cash all the time, even when walking around.

**Comment by Stubbjax** [comment]
## Fix the Tank Hacker prices

The first thing that would absolutely help is to standardise the price of Tank Hackers from $780 to $625. This should be done regardless of any other change. The standardised prices of Hackers would also ideally not be touched as four Hackers directly translates to $2500, which is their intended equivalency with the secondary economy structures of USA and GLA.

While reducing the price of Tank Hackers is a relatively visible change, there are several factors that offset this:

1. The unit is uncommon
2. It would match the price of other Hacker variants
3. It is a reduction rather than an increase
4. It would give Tank a much-needed boost in the late-game, where it is significantly disadvantaged

## Super Hacker considerations

The infantry-specific Super Hackers should not be more expensive or build slower than the other variants, as it would go against the intended faction-specialisation paradigm and break typical design patterns (otherwise King Raptors, Emperors, Aurora Alpha, etc. should be more expensive than their non-specialised counterparts). It would be quite bizarre to have logic that essentially says "Your Hackers get an advantage by starting as veterans, but they also cost more / build slower to negate that advantage."

The cleanest way to balance Super Hackers with their non-infantry equivalents - if necessary - would be to remove their inherent veteran rank so that their income is standardised across the board. This way, early vs late-game proficiency would have a stronger reliance on player decision-making than game mechanics, which would help regulate faction balance.

## Secondary incomes

The income of other factions should also be considered:

| Secondary eco | Raw income | Per minute |
| ------------- | ------------- | ------------- |
| Black Market | $20 / 2s | $600 |
| Supply Drop Zone | $1500 / 120s  | $750 |
| Hacker @ Rank 0 | $5 / 2s  | $150 |
| Hacker @ Rank 1 | $6 / 2s  | $180 |
| Hacker @ Rank 2 | $8 / 2s  | $240 |
| Hacker @ Rank 3 | $10 / 2s  | $300 |

It is important to note that Hackers have the potential to out-earn the secondary income of USA and GLA if enough time passes (e.g. 2 Rank 3 Hackers = 1 Black Market, at $1250 vs $2500). This factor is primarily offset by their vulnerability, with their relatively slower construction and travel time also playing a (lesser) part.

## The issues

The two major issues that China faces regarding its secondary economy are:

1. Low survivability - Hackers that are out in the open are easily killed
2. It takes time for Hackers to ramp up to maximum income

Losing Hackers comes at a heavy cost because not only the monetary investment is lost, but the ramp up time is lost as well. These costs are in addition to the fairly lengthy construction and travel time, as well as the extremely high experience the enemy earns, which only compound the issue. As there are very limited options to address the low survivability directly, it makes sense to address its impact instead.

## Some solutions

Roughly in order of importance, I'd suggest the following composite adjustments:
```
1. Reduce the price of Tank Hackers from $780 to $625
2. Change Hacker experience requirements from [100 300 500] to [100 200 300]
3. Reduce the build time of all Hackers from 20s to 15s
4. Change Hacker experience values from [50 100 150 400] to [50 75 100 150]
5. Remove the starting veteran rank from Super Hackers
6. Boost the hack rate bonus from the Internet Centre from 1800ms per hack to 1600ms per hack
```
I especially like the experience requirement change because players would likely never notice it. Here are some nice graphs to illustrate the impact:

![image](https://user-images.githubusercontent.com/11547761/180705270-fabcca37-cc0f-4b59-a973-de4f0d990248.png)

![image](https://user-images.githubusercontent.com/11547761/180705257-5d387a3c-5efc-4f86-a52d-687da149d503.png)

The change in experience requirements effectively gives a Hacker an extra $600 between 400s and 1000s, or an additional $1 per second after 06:40 for 10 minutes.

The build time change would also play a big part, as it can essentially stack for every produced Hacker (5s saved for 1 Hacker, 10s saved for 2 Hackers, 100s saved for 20 Hackers, etc.), though a 5s change would be more likely to be noticed by players. I doubt many would consider it to be a negative change due to the increased monetary prospects.

Slightly boosting the movement speed and deployment / pack speed should also be considered. Hackers pack up extremely slowly, which significantly limits options when it comes to avoiding things like bombings or super weapon launches. It should be fine to adjust the pack time animation duration of 5133ms, despite it perfectly matching the animation, due to the `PackUnpackVariationFactor` of 0.5 already significantly scaling the animation speed anyway.

The solutions listed here ultimately reduce the impact of losing Hackers, which is an indirect approach to their low survivability. The combination of these changes are relatively minimal in their impact on the gameplay, have relatively low visibility to players, and would help give China a much-needed boost when it comes to the later stages of a game.

## Another solution
And if that wasn't enough, here's a fun-filled solution that would surely upset the community! Another way to approach this issue would be to apply stealth to Hackers via an upgrade, similarly to the Rebel's Camouflage upgrade, where it's researched by default for GLA Stealth General but can be researched by vanilla GLA. This would require the introduction of a new upgrade for all non-Infantry China factions, (e.g. "Advanced Algorithms", "Incognito Mode", "Satellite Hack III") that applies stealth to their hackers, with Infantry General having it researched by default. There is even an unused line "Hacking algorithms ready" that could be used for the upgrade's completion audio! This solution would score high in the theme consistency department.

A stealth upgrade would directly address the low survivability issue. This would benefit the game in several ways:

1. A late-game upgrade could be potentially less obtrusive in that behaviour is identical to 1.04 without it being researched
2. Players now have an additional strategic decision to make - purchase the stealth upgrade or purchase more Hackers
3. China's economy would become much more viable and further balance the scale between short-term and long-term strategy
5. China Infantry General maintains its 'Super Hacker' advantage (inherent stealth + Vehicle Hack)

However, there are some important drawbacks to consider:

1. Has relatively high visibility and would likely be considered a "big change" and aggravate purists
2. China Infantry General becomes slightly less unique

That's all for now!

**Comment by xezon** [comment]
All new proposals listed in OP.

**Comment by commy2** [comment]
Awesome post, Stubbjax. I agree with everything you wrote. I would like to add that Super Hacker vet 1 can be preserved, but the EXP requirements of vet 2 / vet 3 can be changed such that the Super Hacker reaches vet 2 at the same time a normal Hacker would reach vet 2. That way, the Super Hacker income does not scale as harsh compared to normal Hackers.

**Comment by xezon** [comment]
Awesome post indeed. So much info. Perfect.

> 1. Reduce the price of Tank Hackers from $780 to $625
> 2. Change Hacker experience requirements from [100 300 500] to [100 200 300]
> 3. Reduce the build time of all Hackers from 20s to 15s
> 4. Change Hacker experience values from [50 100 150 400] to [50 75 100 150]
> 5. Remove the starting veteran rank from Super Hackers
> 6. Boost the hack rate bonus from the Internet Centre from 1800ms per hack to 1600ms per hack

1. Agree 100%
2. I am not yet sold on the numbers. Do we have numbers for how long in seconds to vet up each level?
3. It seems quite large reduction with 25% less. Why that much?
4. Agree. Can we get the values for SDZ and Market once more to compare against to determine most reasonable values?
5. I am not fan of. All China Inf people start ranked. Changing that will break this promise and consistency. Casual player may think Super Hacker became worse.
6. It makes Internet Center more valuable. But Hacker income looks really ok by that income table above, so I am not convinced this is necessary.

**Comment by Stubbjax** [comment]
Likewise, some good points! Let me address them:

2. Hackers earn 1xp per hack, at 2s per hack. So a 100xp requirement to level up equates to 200 seconds or 03:20.

3. I should have expanded upon this. I looked at the numbers for the Black Market - which takes 60s to build (30s with power) - and the Supply Drop Zone - which takes 45s to build. Seeing as four Hackers equate to a Black Market or Supply Drop Zone, I figured 4x20s is not only much slower than the others, but if you include the time required for each Hacker to travel to its destination and begin hacking, this duration is blown out even further. A value of 4x15s brings the build time closer in line with the other structures, though it is still technically the slowest if you include travel and unpacking (and potentially standing there for ages while the player is focused elsewhere). But I do agree that it is a substantial change and could potentially be fine-tuned further.

5. Yeah, it does break consistency somewhat. But the same can be said in reverse, in that Infantry General breaks income consistency with the other factions. But you correctly point out that this would also be a fairly visible change, and so I'd probably avoid it on that principle as well. I do like commy's suggestion, which addresses both issues fairly subtly.

6. Considering the fact that it is almost a necessity in the current game, I thought it would make sense to offset the incurred $2500 cost by letting the Hackers level up a bit faster. Though it might already be fine in combination with other changes. It also depends on the other changes that are made to the Internet Centre, such as health adjustments, etc.

**Comment by xezon** [comment]
2. Ok so if I am not mistaken it translates to following. It looks like big economy boost.

| Hacker          | vet 1 | vet 2 | vet 3 |
|-----------------|-------|-------|-------|
| Original Hacker | 3:20  | 10:00 | 16:40 |
| Patched Hacker  | 3:20  |  6:40 | 10:00 |

3. Ok. Reasonable values indeed. Agree.

| Object of same value      | Build Time    |
|---------------------------|---------------|
| Original 1x USA Drop Zone | 00:45         |
| Original 1x GLA Market    | 01:00 (00:30) |
| Original 4x Hacker        | 01:20         |
| Patched 4x Hacker         | 01:00         |

**Comment by commy2** [comment]
Fun fact: In CCG, the build time for the Black Market is 90 seconds (45). It had also 500 health instead of 1000 health and obviously no option for Fortified Structures on top of that. All these changes are why GLA is so good in lategame in ZH compared to CCG.

**Comment by xezon** [comment]
Jundiyy:

![Screenshot_20220725_084637_com google android youtube](https://user-images.githubusercontent.com/4720891/180788565-29e83701-faca-4b74-ab64-d3c92c001edd.jpg)

![Screenshot_20220725_084645_com google android youtube](https://user-images.githubusercontent.com/4720891/180788582-d96d6751-20da-45eb-bcdf-388fcb780bd5.jpg)

**Comment by commy2** [comment]
```
- cost $625, build-time 20 sec (Black Market: $2500, 60 sec; SDZ: $2500 45 sec, 4 power)
- Tank Hackers cost $780 instead of $625 (25% more expensive)
- Inf Hackers are stealthed and spawn at vet 1, have 40% armor vs poison and radiation

- No XP awarded for: hacking vehicles, hacking buildings
- XP awarded for every cash hack: 1 point
- cash hack XP does NOT count towards the player XP
- XP required for vet1/vet2/vet3: 100 300 500
- cash per cash hack vet0/vet1/vet2/vet3: $5, $6, $8, $10
- time between cash hacks: 2 seconds
- 1.8 seconds while in Internet Center (10% faster)
- 1.6 seconds while in Internet Center for Super Hackers (20% faster)
- this means time required for:
        Hacker          Super Hacker    Hacker in IC    Super Hacker in IC
vet1:   3 min 20 sec    0 min           3 min           0 min
vet2:   10 min          6 min 40 sec    9 min           5 min 20 sec
vet3:   16 min 40 sec   13 min 20 sec   15 min          10 min 40 sec
```

**Comment by commy2** [comment]
Above reveals the following information not yet mentioned in the thread (or I missed it, in which case, sorry!)

- Super Hackers hack 20% faster in any IC, while normal Hackers only hack 10% faster in an IC.
- This makes Super Hackers inside an IC vet up even faster
- Cash hack XP does not unlock genpoints
- Super Hackers have 40% more armor vs poison and radiation puddles, although they still die quite fast

**Comment by xezon** [comment]
Ok so looking at all data I estimate following setup is reasonable for starters

1. Reduce the price of Tank Hackers from $780 to $625; all Hackers cost the same, equalling build cost of 4 Hackers with build cost of Black Market and Supply Drop Zone ($2500)
2. Change Hacker experience requirements from [100 300 500] to [100 250 450]. Why just 50? Because Vet hackers already give huge money boost and it looks reasonable to start tweak just small here.
3. Leave Super Hacker experience requirements at [100 300 500] because they start at Vet 1 and have 100 XP advantage
4. Reduce the build time of all Hackers from 20s to 15s, equalling build time of 4 Hackers with build time of Black Market (01:00)
5. Change Hacker granted experience values from [50 100 150 400] to [50 60 80 100]. Why? Because Drop Zone, equal to 4 Hackers, gives 200 XP flat. And Vet 3 Hacker makes twice as much money as he started with, so a doubling of XP is reasonable.
6. Decrease Hacker hack interval in Internet Centre from 1800ms to 1600ms, same as Super Hacker, to give IC more purpose.
7. Reduce PackTime from 5133 ms to 3200 ms to allow for quicker evacuations
8. Leave UnpackTime at 7300 ms
9. Change BasicHumanLocomotor (speed=20) to BasicHumanLocomotorPlus25 (speed=25). Tank Hunter: 20, Red Guard: 25, Lotus: 30, Hacker needs mobility because it is weak

As for reducing noise from Stealth Hackers, I am not sure. Could be OP.

**Comment by Jundiyy** [comment]
Seems reasonable.
Not sure about the pack time, would normal pack animation not look weird?

1 extra point, not exactly on topic, I think even with these changes, we would still need to reduce IC price, since it still leaves us in a similar situation. Hacking is better but early on is still the same thing. The difference is that you get your Hackers out a bit faster and so make a little more money. Around $125 more in total. 

And I could see $600 being okay for Hackers as well. Although above is fine.

**Comment by xezon** [comment]
We can test how it looks. Super hackers already have decreased pack time for vehicle hacks and it is fine.

I will create Pull Requests later accordingly and test.

**Comment by FDPUser443** [comment]
Proposal 20?
Add a new ability: Hacking from any civil building or china bunker (And even Palace or Fire Base)
It will increase hackers protection

**Comment by ExiLe-ZH** [comment]
> Proposal 20? Add a new ability: Hacking from any civil building or china bunker (And even Palace or Fire Base) It will increase hackers protection

Then Internet Center becomes redundant, can just spam cheapo bunkers everywhere. Even guard it with a TH or 2 inside.

**Comment by xezon** [comment]
Can Hackers actually enter Bunkers? The least we could do is allow Hackers to enter China Bunkers. Then they just sit in there doing nothing, because it is dark and cramped and they cannot work. But at least it allows Player to build some emergency Bunkers in the back of his base. So when an attack comes, then Player could pull his hackers into Bunker, until the threat is gone.

Sounds fair to me.

**Comment by ExiLe-ZH** [comment]
> Can Hackers actually enter Bunkers? The least we could do is allow Hackers to enter China Bunkers. Then they just sit in there doing nothing, because it is dark and cramped and they cannot work. But at least it allows Player to build some emergency Bunkers in the back of his base. So when an attack comes, then Player could pull his hackers into Bunker, until the threat is gone.
> 
> Sounds fair to me.

They can already hide in bunkers and garrisons

**Comment by MTKing4** [comment]
> Seems reasonable. Not sure about the pack time, would normal pack animation not look weird?
> 
> 1 extra point, not exactly on topic, I think even with these changes, we would still need to reduce IC price, since it still leaves us in a similar situation. Hacking is better but early on is still the same thing. The difference is that you get your Hackers out a bit faster and so make a little more money. Around $125 more in total.
> 
> And I could see $600 being okay for Hackers as well. Although above is fine.

We can keep it $625 and make the reduction on the IC itself, maybe $1000, or $800, or a number in between.

that way players are more incentivised to build it, it also reduces the costs required to reach essential intelligence upgrades.

Speaking of which, i think sat hack II is a bit too expensive, and the way it works should be different imo, if possible, make it like the USA counterpart.

**Comment by xezon** [comment]
China Hacker is Boss now.

**Comment by ExiLe-ZH** [comment]
The new ExperienceValue distribution makes perfect sense when looking to their income rates ($5 $6 $8 $10), it's the same but 10 fold. However, I would slightly reduce it further because they are MUCH easier to kill than SDZ's or (Fortified) BM's, so the reward should be less aswell.


### Here's my proposal:

Make all values 10xp less:
40 50 70 90

This means that:
4 Regular Hackers = 160xp (20% less than SDZ/BM).
4 Veteran Hackers = 200xp (same).
4 Elite Hackers = 280xp (40% more).
4 Hero Hackers = 360xp. (80% more).

**Comment by xezon** [comment]
This task is closed and completed. I suggest open new one and link to this one for reference.

**Comment by ExiLe-ZH** [comment]
Or open this again, because it gets messy with so many topics and this one is pretty much the master topic.

**Comment by xezon** [comment]
The kill XP reward was already reduced significantly. It is situational whether or not 4 Hackers are easier to kill than 1 Drop Zone. 4 Hackers could be located at the opposite ends of a base, and therefore would be much more difficult to target than a single Drop Zone.

**Comment by ExiLe-ZH** [comment]
> Jundiyy:
> 
> ![Screenshot_20220725_084637_com google android youtube](https://user-images.githubusercontent.com/4720891/180788565-29e83701-faca-4b74-ab64-d3c92c001edd.jpg)
> 
> ![Screenshot_20220725_084645_com google android youtube](https://user-images.githubusercontent.com/4720891/180788582-d96d6751-20da-45eb-bcdf-388fcb780bd5.jpg)

https://youtu.be/SGbry3QNssw?t=1212

**Comment by xezon** [comment]
The first screenshot is really confusing.

**Comment by ExiLe-ZH** [comment]
Just like Lotus, should Hackers be trained to be able to detect enemy stealth units?

**Comment by xezon** [comment]
> Just like Lotus, should Hackers be trained to be able to detect enemy stealth units?

I do not like this. It would be an unexpected ability for the Hacker.

**Comment by ExiLe-ZH** [comment]
> > Just like Lotus, should Hackers be trained to be able to detect enemy stealth units?
> 
> 
> 
> I do not like this. It would be an unexpected ability for the Hacker.

👍

just brainstorming how hackers could better protect themselves from various treats.

**Comment by ExiLe-ZH** [comment]
Alternative buff idea:

Give China's Stealth Hacker upgrade, either available from Prop or IC. 
Should be fairly expensive, like $2500 and perhaps only active while hacking, to keep differentiation from Inf.
It could be compared to vGLA's Camouflage upgrade, which Stealth gets for free.

**Comment by penfriendz** [comment]
Make them invisible while hacking. For free. It won't break the game, I promise :)

**Comment by ExiLe-ZH** [comment]
Yea I know and I would be for it, but I guess it feels too much like a change for some? As an upgrade it feels like less of a change.

**Comment by penfriendz** [comment]
Yeah, I know we're on the same side here both trying to find the balance to fix hackers, lol. In some ways an upgrade can be more visible imo.
