### ISSUE TITLE
All Anthrax Bombs drop Anthrax Beta, regardless of owning the Beta Upgrade

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#756]
All Anthrax Bombs drop Anthrax Beta, regardless of owning the Beta Upgrade. Only Toxin General starts with the correct Anthrax Bomb and can upgrade to Anthrax Gamma for it. Should Anthrax Bomb start with regular green poison, and then upgrade to Anthrax Beta and Anthrax Gamma for all GLA factions? And should the non-Beta Anthrax Bomb deal less damage than the Beta Anthrax Bomb accordingly?

## Regular Anthrax Bomb
![shot_20220725_154755_1](https://user-images.githubusercontent.com/4720891/180795108-5c38b4ac-0bf9-4aa1-8cf1-8644b9217653.jpg)

## Regular Anthrax Bomb in NProject:
![gla_toxin_bomb1](https://user-images.githubusercontent.com/4720891/180795471-5056c7aa-6bde-4ca1-b26c-45452cabb25d.jpg)

### Proposal 1
All Anthrax bombs start with regular green Anthrax and upgrade to Anthrax Beta with the Palace upgrade.

### Proposal 2
Anthrax Bomb before Beta Upgrade deals less damage.

**Comment by MTKing4** [comment]
I think it should have the correct color for consistency sake, so I go with proposal 1, also it looks really sick with green and something new and cool to add to the game that might attract more people :>

**Comment by commy2** [comment]
> Only Toxin General starts with the correct Anthrax Bomb and can upgrade to Anthrax Gamma for it.

It's been a while, but I am pretty sure Tox always spawns a gamma bomb, even before he upgrades to Anthrax Gamma. The super power is just always pink when called from a Tox Command Center and blue otherwise.

---

Blue and pink Anthrax Bombs do exactly the same amount of damage:

[See initial explosion weapon](https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Weapon.ini#L3472-L3504) and [poison cloud damage over time weapon](https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Weapon.ini#L1906-L1936)

There is no statistical difference between the two.  They only have a different color.

---

I always figured that Anthrax Bomb just always is supposed to use the upgraded toxin color, even before the upgrade ... because.  The only thing that is weird to me is, how Demo General gets a blue bomb, even though he cannot research Anthrax Beta.  This is why I gave him a green bomb in my mod: https://github.com/commy2/zerohour/commit/970d2e8b10a00338e3244dfd36a87966475ba93c

I did not change any stats either, so green, blue and pink are just visually different.

**Comment by ExiLe-ZH** [comment]
Different colors would be nice, the green in that pic looks pretty sick.

But not sure if damage levels should differ (too much). It's what the upgrades suggest though, so things like different durations or harder to clean up wouldn't be intuitive?

**Comment by xezon** [comment]
> It's been a while, but I am pretty sure Tox always spawns a gamma bomb, even before he upgrades to Anthrax Gamma. The super power is just always pink when called from a Tox Command Center and blue otherwise.

I tested this before I wrote the bug report. It is Blue before the Upgrade, and Purple after Gamma Upgrade.

**Comment by commy2** [comment]
I double checked. It's slightly different from what I remembered, but still different from what you wrote.

What map have you tested this?

If you order the Anthrax Bomb from a vGLA/Demo GLA or Stealth GLA Command Center, the payload will be AnthraxBomb. AnthraxBomb will change color depending on upgrade:

https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/WeaponObjects.ini#L1586-L1595

It will be blue without Anthrax Gamma, and pink with Anthrax Gamma.

However, if you order the Anthrax from a Tox GLA Command Center, the payload will be AnthraxBombGamma. AnthraxBombGamma will always be pink:

https://github.com/TheSuperHackers/GeneralsGamePatch/blob/main/Patch104pZH/GameFilesOriginalZH/Data/INI/Object/WeaponObjects.ini#L1671-L1674

If you order any special ability from the shortcut bar, it will use whatever Command Center was first placed on the map.

If you want to test what the Anthrax Bomb looks like from a Tox Command Center, either sell all non-Tox Command Centers, or select the Tox Command Center and use the command button from there.

If you do either of that, the bomb should be pink even without the Anthrax Gamma upgrade.

**Comment by xezon** [comment]
I tested on this map:
https://github.com/TheSuperHackers/GeneralsGamePatch/tree/main/Maps/SkirmishOnly/!SkirmishTestPromotionsTOX

**Comment by commy2** [comment]
Hmm, sadly I don't have ZH set up on this machine (I am not at home during the week). Another potential issue is that there're two different Tox Command Centers in the game. The one from the last USA campaign mission behaves like other non Tox ones: it will spawn a blue bomb without Anthrax Gamma, pink with Anthrax Gamma.

If all else fails, I guess you have to try in a normal skirmish on a vanilla map as Tox.

If you can't get the pink one to drop from a Tox Command Center without Anthrax Gamma, then I'll have to reproduce that Saturday. That seems strange from all I know about this game.

**Comment by USA-Bruce** [comment]
First off, you guys need to read the change logs 
Thrax getting anthrax Gama without the upgrade was a change from 1.03 I think?
The whole reason why these planes drop stronger than intended anthrax is due to balancing reasons and patched that way.
Now should the anthrax upgrade increase its damage? Yeah sure why not
Would color changes do it better? That's up to you guys
So good luck

**Comment by commy2** [comment]
> The whole reason why these planes drop stronger than intended anthrax is due to balancing reasons and patched that way.

There is no statistical difference between blue Anthrax Bomb and pink Anthrax Bomb in 1.04. Neither does the initial explosion, nor does the poison field itself deal different amounts of damage. The difference between the two is entirely cosmetic.

**Comment by commy2** [comment]
> First off, you guys need to read the change logs

The changelogs by EALA are really bad. Really really bad. They do not reflect the actual changes in the game config. One third of all changes are attributed to the wrong version number, another third was never implemented at all. Lots of changes are entirely undocumented in any changelog.

**Comment by xezon** [comment]
Re-opening this.

Exile:
> Shouldn't all be green except Tox? And upgradable to Beta-Blue except Demo?
> And shouldn't Tox start with Beta-Blue which can be upgraded to Purple-Gamma?

Stubbjax:
> The colour should really match the severity / damage output of the toxin field. Otherwise the colour is misleading and ultimately meaningless.

xezon:
> Imo it would be fine to make the toxins pre upgrade a bit weaker. The anthrax bomb lasts so long... and it would also help nerf it a bit when we fix the Toxins force fire exploit for Anthrax Bomb.

**Comment by commy2** [comment]
xezon:

```
Tox      Beta > Gamma
Stealth  Alpha > Beta
vGLA     Alpha > Beta
Demo     Alpha
```
This would make sense on first glance, however, there is precedence of other cross faction upgrades.
E.g. Camouflage works on Toxin Rebels. Anthrax Gamma works on vGLA Scorpions and Marauders with Toxin Shells. Patiotism works on Tank Red Guards, Composite Armor works on Airforce Microwaves etc.

So I propose:
```
Tox      Beta > Gamma
Stealth  Alpha > Beta > Gamma
vGLA     Alpha > Beta > Gamma
Demo     Alpha > Beta > Gamma
```
