### ISSUE TITLE
USA Supply Drop Zone Cargo Planes are attackable

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#79]
Supply Drop Zone Cargo Planes are attackable. This is annoying in late game where many cargo planes fly to enemy base and trigger radar warnings and sound messages. NProject addresses this by making planes not attackable. This has implications on gameplay however, because plane can no longer be shot down and also units no longer become occupied with these practice targets which weakens USA.

A more sensible approach would be to simply disable attack warnings for these planes, if possible.

**Comment by commy2** [comment]
Another argument in favour of this change is late game performance in spammy games like 6 player FFAs. Making these planes not attackables drastically reduces the number of particles created: No flares, no stray stingers and their trail particles, no exploding cargo planes, no Quad and Gat tracers, no impact particles on the plane.

Basically, this is a potential performance boost in games that tend to be laggy.

**Comment by xezon** [comment]
That is a really good point. Would it be possible to remove particle effects from hits on these Cargo Planes? Or are hit effects solely bound to the attacking projectile/weapon?

**Comment by commy2** [comment]
They come from the object. The biggest impact is probably from flares, missiles and AA gunfire though.

**Comment by xezon** [comment]
Would it be possible to make planes manually attackable, but not auto attackable? Then they could still be shot down at least. But still it would weaken USA in late game to not have this extra cannon fodder unit. On the other hand, USA is very strong in late game with mass cash. USA is very likely to win in mass army spam games. Maybe it does not hurt USA overall.

**Comment by ExiLe-ZH** [comment]
There's a few things to consider with this issue though:

- These planes are used tactically to soak up damage to time certain attack moves.
- It would be weird an enemy plane just flies over an enemy base without getting fired at.
- It's already weird the plane flies over the enemy base in the first place. 

Another idea/suggestion:
Make the plane curve off to the side of the map.

**Comment by alanblack166** [comment]
Curving off is possible and has been done in Rise of the Reds. Making planes force attackable only can be handled by a FORCEATTACKABLE KINDOF.

**Comment by Jundiyy** [comment]
Same points as Exile. Could curve it off map but then you can't use it to soak damage which does help a lot.

**Comment by Stubbjax** [comment]
This is actually a serious quality-of-life issue for anyone playing with aircraft in guard mode.

A player's aircraft could be rendered unavailable at a critical moment - having to reload due to a cargo plane strike. Or a player's migs end up creating a firestorm on their own base / units / economy. Not to mention other collateral damage to friendly aircraft from rockets and lasers, bunker helixes downing themselves, EMP missiles striking buildings, etc. Cargo planes actually cause a lot of damage / chaos - with none of it requiring any skill whatsoever from the opposition.

May all the hackers who died as a result of cargo planes rest in peace.

https://user-images.githubusercontent.com/11547761/131528476-e24e15fa-2ea4-4add-a823-13f99afe74f5.mp4

**Comment by xezon** [comment]
I am absolutely in favor to do something about it. Yes USA loses this free cannon fodder unit, but USA is strong enough in late game. It does not need it. Plus USA actually benefits as well when playing against an opponent USA. And USA player can enjoy some Radio silence. It will make the real attack warnings more valuable in USA matches again (press Spacebar to jump to Attack Event). Other factions also don't have such a free cannon fodder feature.

The benefits of getting rid of it:
- Better performance in late game and massive camp games, because units no longer shoot at all these planes
- Better for USA and China to not have their planes landing every now and then after they shot on cargo planes
- Better for China to not have their planes cause Firestorm by Migs in their home base after attacking cargo planes
- No more useless Attack warnings on Radar and Voice

**Comment by Stubbjax** [comment]
And better for players who might have a single scaffold left and get defeated thanks to a cargo plane (it has definitely happened)!

https://user-images.githubusercontent.com/11547761/131532880-29ade31a-4252-4360-81c3-068dd281d0f5.mp4

Maybe there is another bug here, where seemingly air-localised damage can affect the ground.

**Comment by Madrageeeeee** [comment]
Truly very annoying in late game

if you want a low impact solution (on gameplay) i would argue going for reducing the amount of impact it has on game performance. 

on the other hand i think very few people combine their attacks together with cargo planes and it is seriously annoying in spam games.

**Comment by MTKing4** [comment]
Make unattackable, absolutely ridiculous 
Points against it
+ **It can be used as cannon fodder**
Almost no one uses that
+ **it can't be shot down to deny USA money**
Firstly it shouldn't be ok to deny secondary eco in the first place, that's like saying deny a black market from getting the money for the next 5 minutes, or send the hacker nudes to distract him from stealing money for the next 5 minutes, not acceptable, secondly they come from the nearest edge of the map anyway so you'll hardly get a chance to take it down unless you have AA units OFF the map behind US base
+ **It's weird no one fires at it**
Technically it's a UN plane, Netrual plane so it's fine, and even if it wasn't, ZH never made sense anyway so why would that be a big deal? Gameplay matters more

**Comment by xezon** [comment]
I would suggest to implement the FORCEATTACKABLE approach. Consequences:

* Planes will fly the same route, so enemy player will know USA has a Drop Zone where it comes from
* Planes can be attacked manually to prevent the money drop
* Planes are no longer attacked automatically, which effectively gets rid of attack notifications, performance implications and useless auto attacks

**Comment by MTKing4** [comment]
That should do

**Comment by ExiLe-ZH** [comment]
> I would suggest to implement the FORCEATTACKABLE approach. Consequences:
> 
>     * Planes will fly the same route, so enemy player will know USA has a Drop Zone where it comes from
> 
>     * Planes can be attacked manually to prevent the money drop
> 
>     * Planes are no longer attacked automatically, which effectively gets rid of attack notifications, performance implications and useless auto attacks

I don't like this idea, what would be the point to shoot it then? (to stop ultra dangerous potential ranger drop?) Well and to deny drop off like you said, but chances are so small.

It's just weird enemy planes go straight over enemy bases without getting shot.

If this is the approach, then I would keep it minimalistic and fix Air Guard vs planes only. Which is the thing that's most annoying and impacts gameplay the most.

**Comment by xezon** [comment]
I removed the Controversial tag. This problem will be fixed.

**Comment by ExiLe-ZH** [comment]
> I removed the Controversial tag. This problem will be fixed.

It is controversial though, Jundiyy also agrees with me here.

**Comment by MTKing4** [comment]
What about reinforcement pad planes, are those auto acquired as well?

If so they should be dealt with the same imo, for all factions

**Comment by ZekeDlyoung** [comment]
> It's just weird enemy planes go straight over enemy bases without getting shot.

Edit the plane to have a UN logo instead of a US one, problem solved 🙃 

> Make the plane curve off to the side of the map

The SDZ planes in ROTR actually fly upward and leave the map after it makes its drop, could reference the code for that

> What about reinforcement pad planes, are those auto acquired as well?
>
> If so they should be dealt with the same imo, for all factions

Reinforcement pads are not built in the same quantities as SDZs so they're not as annoying, and the planes seldom fly in the direction of your base, so they can be left alone imo

**Comment by MTKing4** [comment]
> Reinforcement pads are not built in the same quantities as SDZs so they're not as annoying, and the planes seldom fly in the direction of your base, so they can be left alone imo

They can still be confusing sometimes, thinking the enemy just launched an anthrax bomb or EMP/Mines/drops

**Comment by xezon** [comment]
Re-adding Controversial label. Albeit these planes are AI controlled and the owning player is unable to do anything with them, they do affect how units automatically interact with each other.

**Comment by xezon** [comment]
It is reasonable to treat the planes of other drop pads identically for consistency.

**Comment by ExiLe-ZH** [comment]
> The SDZ planes in ROTR actually fly upward and leave the map after it makes its drop, could reference the code for that

That is very nice too, why not combine this with the non-auto attack fix? 

I see no reason why not to do this, the plane having to fly all the way over the enemy base just for purpose of hinting where the dropzone is, is nonsense. 

A few hunderd meters for this purpose is good I understand, maybe like 30-40% of the average map size? Then the enemy just needs a little more vision.

**Comment by xezon** [comment]
Could someone please post the relevant code here to achieve this? Then I can create a pull request for it and we can look at it.

**Comment by ExiLe-ZH** [comment]
I wanted to leave a final (hopefully unbiased) case summary here:

1) Why the Dropzone design for USA? 
Because it's a realistic, thematic and cool visual representation of USA as a faction, same how Black Markets thematically represents GLA as a guerrilla style of faction e.g.

2) Intended gameplay dynamics, the advantages:
-SDZ gains more money than Black Markets/Hackers.

3) Intended gameplay dynamics, the disadvantages:
-Planes are interceptable before the money drop-off.
-Planes give away intel of the positions and amount of DropZones (mostly likely intended).

4) Gameplay side effects:
USA players learned that Cargo Planes offer more advantages after the money drop-off, for example distracting Units or Base Defenses so that USA can combine attacks or genpowers more successfully. Also does it make Air Guard mode less useful because aircraft auto-attack the plane.
It's very unlikely though that these advantages were intended gameplay dynamics, does USA need these advantages in the first place? 
Some players prefer how these dynamics add more skill and tactical opportunities, while others feel it only adds random frustrating moments. Would be good to have data of how many people like/don't like these side effects.

4) Performance:
It's not exactly clear how much performance is saved with a fix, it would be good to have quantifiable data.

5) Final decision:
It's not a case of bugs or exploits, so I think it's fair to base the final decision on how much performance is saved and how many people would (not) prefer a redesign.

**Comment by MavroGada2** [comment]
I tried to make something new, useful and cool. 

Useful part: Planes will be attackable like vanilla but only when they have payload. When they drop their payloads they will be unattackable. So they can't trigger any units with "Guard" command.

If we want to prevent to give intel to enemy about how many drop zones the USA has, I added new "exit animation".





https://github.com/user-attachments/assets/d678dabc-bbb6-4f48-9498-27d4cef3af9f


### Exit "animation" and preventing the give intel:



https://github.com/user-attachments/assets/93344aca-5d75-4b24-9e8b-e4c32998f760

**Comment by xezon** [comment]
Nice. I suggest you comment the required INI changes for it for reference.
