### ISSUE TITLE
GLA Bomb Truck Bio Bomb upgrade does not grant any practical benefit

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#800]
> commy2: 
> It does make the Bomb Truck spawn a medium sized poison cloud which does 2.0 damage over time or 2.5 damage over time with Anthrax Beta upgrade. Anthrax Gamma does nothing.
> 
> What doesn't change is the initial explosion damage. That is always 1000, with or without Bio Bomb and without or without any Anthrax upgrade.

### Proposal 1
Remove upgrade all together, give tox by default.

### Proposal 2
Remove upgrade and reintegrate into Beta/Gamma, purchasing this will upgrade the Bombtrucks instead.

### Proposal 3
Buff damage output (that justifies $500)

### Proposal 4
Nerf HE and buff Biobomb, rebalance prices accordingly so that cost/performance is same as before.

### Proposal 5
Make Biobomb cheap.

**Comment by commy2** [comment]
It does make the Bomb Truck spawn a medium sized poison cloud which does 2.0 damage over time or 2.5 damage over time with Anthrax Beta upgrade. Anthrax Gamma does nothing.

What doesn't change is the initial explosion damage. That is always 1000, with or without Bio Bomb and without or without any Anthrax upgrade.

**Comment by commy2** [comment]
I wouldn't change this. 
Proposal 4 with like $100 could work too. But then we have to ask ourselves: What is the point here? Every change is mental overhead for somebody trying to work out what this patch does. It feels like this would be a change just for the sake of making changes. Like: "Uh what have we done about the Bomb Truck? Right, make that upgrade cheaper so we can check off the Bomb Truck".
Don't fix what ain't broken. The Bomb Truck is one of the very few things that works as it should (aside from some obscure engine side bugs like camouflaging as Scout Drone or Battle Ship).

**Comment by xezon** [comment]
How much extra damage does High Explosive do and how much does it cost?

I do not believe we need to touch core upgrade setup. We can tweak bomb damage and/or price to be consistent with the value given by High Explosive upgrade, so that a choice between the 2 is reasonable. And the Anthrax Gamma field should do damage like the Anthrax Beta field of course.

**Comment by commy2** [comment]
>How much extra damage does High Explosive do?

Doubles damage, increases area of effect by 56 to 70%.

Both upgrades cost $500 and take 5 seconds to research.

**Comment by xezon** [comment]
Ok. Wow. The High Explosives upgrade looks like really good value then. I would not have been surprised if it costs 1000. This looks easy to solve then.

| Upgrade                 | Price | Damage Bonus | Range Bonus | Perks             |
|-------------------------|-------|--------------|-------------|-------------------|
| Original High Explosive | 500   | 100%         | 70%         |                   |
| Original Bio Bomb       | 500   | 0%           | 0%          | Toxin Puddle      |
| Patched Bio Bomb        | 250   | 50%          | 35%         | Toxin Puddle      |

Bio Bomb will be half price of High Explosive, but also deal half its bonus damage. It retains its Toxin Puddle perk, but only get's half the range bonus, wheras High Explosive gets the full range bonus of 70%. This looks fair on paper, and a decision between both upgrades becomes a reasonable choice.

**Comment by Jundiyy** [comment]
So if I understood properly. The High Explosive Bomb is the same but the Bio Bomb now does damage? Seems fine. I'm fine with $250 but perhaps $300 might be more reasonable since you also get the Toxins with it.

**Comment by ExiLe-ZH** [comment]
> Ok. Wow. The High Explosives upgrade looks like really good value then. I would not have been surprised if it costs 1000. This looks easy to solve then.
> Upgrade 	Price 	Damage Bonus 	Range Bonus 	Perks
> Original High Explosive 	500 	100% 	70% 	
> Original Bio Bomb 	500 	0% 	0% 	Toxin Puddle
> Patched Bio Bomb 	250 	50% 	35% 	Toxin Puddle
> 
> Bio Bomb will be half price of High Explosive, but also deal half its bonus damage. It retains its Toxin Puddle perk, but only get's half the range bonus, wheras High Explosive gets the full range bonus of 70%. This looks fair on paper, and a decision between both upgrades becomes a reasonable choice.

So basically a combination of proposal 3 & 5 then?

**Comment by xezon** [comment]
> So basically a combination of proposal 3 & 5 then?

Yes

**Comment by xezon** [comment]
> So if I understood properly. The High Explosive Bomb is the same but the Bio Bomb now does damage? Seems fine. I'm fine with $250 but perhaps $300 might be more reasonable since you also get the Toxins with it.

If there was no Toxin puddle, then a fair halved bonus would look like so:

| Upgrade                 | Price | Damage Bonus | Range Bonus | Perks             |
|-------------------------|-------|--------------|-------------|-------------------|
| Original High Explosive | 500   | 100%         | 70%         |                   |
| Original Bio Bomb       | 500   | 0%           | 0%          |                   |
| Patched Bio Bomb        | 250   | 50%          | 70%         |                   |

Therefore I believe the 250 price is ok with Toxin Puddle and 35% range bonus.

**Comment by Jundiyy** [comment]
Ah okay, yes, I didn't think of that distribution.  👍

**Comment by Jundiyy** [comment]
I think I feel like changing my thoughts on this. Keep it nearly original.

Original HE Bomb can stay the same (this might just need a small reduction in price to $400, just maybe).
Bio Bomb should be reduced to $50/$100, since it doesn't do anything other than spill a pool of toxins, which should not be so expensive.

**Comment by xezon** [comment]
We cannot make decision based on feeling. It requires rationale.

**Comment by Jundiyy** [comment]
I already gave my rationale...you seem to always misunderstand if I use the word 'feel'. You need to feel the feeling.

THE RATIONALE:
I BELIEVE there is no need to change the HE Bomb since the Bomb Truck works fine the way it is in regards to HE. Price being a bit lower would make it more sweet, make it more appealing, but it is not a must for it.

The RATIONALE behind the Bio Bomb is very simple, it does no damage itself but just drops a pool of toxins (which do damage), so the price should drop down a LOT.
Adding damage to it changes how it already works and the tooltip also doesn't suggest it would do damage, so the most reasonable thing would be to keep it the same unit, but simply reduce the price so it's appealing.
