### ISSUE TITLE
China Nuclear Missile has small effective damage radius

### ISSUE THREAD

**Issue by xezon** [TheSuperHackers/GeneralsGamePatch#846]
China Nuclear Missile has small effective damage radius.

WIP: Create comparison  with GLA SCUD Storm and USA Particle Cannon.

**Comment by xezon** [comment]
# Superweapon Area Damage Test

Here is area damage test of vanilla Superweapons. Tested on 8 x 8 GLA Blackmarkets. Note that China Nuke Missile has the multi blast fix applied to kill the GLA holes properly.

## USA Particle Cannon

https://user-images.githubusercontent.com/4720891/184168342-2c77cd64-b012-4c1f-a13b-c971045d7c17.mp4

## China Nuke Missile

https://user-images.githubusercontent.com/4720891/184168373-9f7280da-4921-48f5-a019-3a4c2f870ef7.mp4

## GLA Scud Storm

https://user-images.githubusercontent.com/4720891/184168400-85f66039-78e9-47d1-86d6-869a5f1acc98.mp4

## Result

| Object                       | Num Destroyed | Num Damaged | Num Undamaged |
|------------------------------|---------------|-------------|---------------|
| Original USA Particle Cannon | 14            | 2           | 48            |
| Patched China Nuke Missile   | 14            | 9           | 41            |
| Original GLA SCUD Storm      | 27            | 29          | 8             |

## Conclusion

Area damage of USA Particle and China Missile are comparable. 1 GLA SCUD Storm can kill twice as much as 1 China Nuke Missile and can further damage 3 times as much as 1 China Nuke Missile. The GLA SCUD Storm is without a doubt the most powerful Superweapon when it comes to area damage.

**Comment by xezon** [comment]
# Superweapon Point Damage Test

Here is point damage test of vanilla Superweapons. Tested on 5 x 5 GLA SCUD Storm. Note that China Nuke Missile has the multi blast fix applied to kill the GLA holes properly.

## USA Particle Cannon

https://user-images.githubusercontent.com/4720891/184176511-d3dfb6d5-f32d-4330-917c-b592d63e97cc.mp4

## China Nuke Missile

https://user-images.githubusercontent.com/4720891/184176473-1f045afb-6e10-4fce-a4d8-ff0fee55f060.mp4

## GLA Scud Storm

https://user-images.githubusercontent.com/4720891/184176536-3c3914bb-f49f-474a-9602-5d4338d2c212.mp4

## Result

With health bar status on center target structure we can measure the applied damage.

| Object                       | Damage Applied |
|------------------------------|----------------|
| Original USA Particle Cannon | 85 %           |
| Patched China Nuke Missile   | 70 %           |
| Original GLA SCUD Storm      | 90 %           |

## Conclusion

SCUD Storm achieves best point damage. Particle Cannon is close, but cannot achieve area damage when focusing on one point. China Nuke Missile applies the least damage by far.

**Comment by xezon** [comment]
I think something needs to be done here. This is not fair at all.

**Comment by commy2** [comment]
- Gamma SCUD (+10% damage) and Demo Scud (+20% damage) would make this comparison look even worse.
- SWG Particle is pink, but as far as I can tell, is identical stats wise.
- Nuke General Nuke Silo comes at 10% discount ($4500).
- One drawback of SCUD Storm is that it has 120s build time (compared to 60s for PC and Nuke), because GLA has no power, so time from investment to first shot is identical to the Nuke.
- It also took 5 seconds for the Nuke to arrive at the target compared to 10 seconds of the SCUD Storm. This is important when using the super weapon against mobile armies. The time of flight also depends on how far from target the super weapon is placed. However, SCUD will generally take longer, because the missiles have to raise first.

**Comment by ExiLe-ZH** [comment]
Another question is how much damage the Nuke does with Fortified Structures

**Comment by xezon** [comment]
This was enough testing from my side. The data is conclusive enough.

**Comment by commy2** [comment]
> Another question is how much damage the Nuke does with Fortified Structures

- SCUD Storm and Nuke Silo both deal EXPLOSION damage
- Fortified Structures does reduce the damage taken from EXPLOSION type weapons by 25%.
- Fortified Structures does reduce the damage taken from PARTICLE_BEAM type weapons by 25%, except for the Command Center, where it is 28% instead.

**Comment by MTKing4** [comment]
> # Superweapon Point Damage Test

I don't think This test was done properly, Nuke and Scud Distributes the damage on crowded buildings, should have done it on a single Building with nothing around it. 

Also particle Cannon does more damage if moved around, so I've heard, not certain.

**Comment by xezon** [comment]
Please proof this.

**Comment by MTKing4** [comment]
Will get a test of it soon

**Comment by ExiLe-ZH** [comment]
Fortified Structures NEEDS to be tested though, because it's a very meta upgrade that's cheap and effective.

The first test vs Markets will look totally different, because the Particle can still destroy the same amount of buildings (maybe two less), whereas the Nuke will suffer alot more I predict.

Btw sorry, I would like to test this myself, but have no time currently in learning how to build maps, unless very easy?

**Comment by xezon** [comment]
USA and China have no Fortified Upgrade. No idea why you guys focus so much on that... meaning you can test a thousand combinations of different structures, and angles, and buffs... the result will always be the same that SCUD Storm is OP.

**Comment by Jundiyy** [comment]
Scud Storm is the more powerful super weapon. Any change we do, should be a buff to the other super weapons, not a nerf to the Scud Storm.

Although I would like to add, China and USA get General Powers that destroy buildings, whereas GLA doesn't (apart from Demo).

So perhaps that's why they do less, as you can combine with GPs.  

Also, they differ, PC is instant, and can move from unit to unit. Is good vs buildings but just not as many as Scud Storm. 

Nuke is also very fast and does good damage vs armies, not so good vs buildings (of course with the GLA hole damage change we did, it will be better). 

Scud Storm is very good vs buildings, but not the best for tracking down moving units (can still work).

**Comment by ExiLe-ZH** [comment]
> USA and China have no Fortified Upgrade. No idea why you guys focus so much on that...

We need to know how it (will) performs vs GLA, it's a practicality test since (Fortified) Markets are one of the priority targets for China.

Currently China needs to use Genpowers in combination to destroy Fortified Markets, whereas USA does not. 

Therefore my buff suggestion would be increasing the damage just enough to make it perform exactly like the test above vs Markets, but then with Fortified Structures. *If this wouldn't make the concentrated power too much vs other highly armored structures.

Btw, Scud-Storm also deserves to be the strongest since GLA has no other Destructive Genpowers (except Demo Rebel Ambush).

**Comment by commy2** [comment]
> Although I would like to add, China and USA get General Powers that destroy buildings, whereas GLA doesn't 

This is an important point.

> My buff suggestion would be increasing the damage just enough to make it perform exactly like the test above vs Markets, but then with Fortified Structures.

That'd mean +33.333333% damage to Nuke Silo. I am only in favour of that if it does not one shot super weapons and Command Centers due to that.

**Comment by ExiLe-ZH** [comment]
> That'd mean +33.333333% damage to Nuke Silo. I am only in favour of that if it does not one shot super weapons and Command Centers due to that.

I agree, that wouldn't be fair, hence I added the note * if that would be the case.

**Comment by xezon** [comment]
> Although I would like to add, China and USA get General Powers that destroy buildings, whereas GLA doesn't (apart from Demo).

It is an argument, but not a strong one. General Powers are limited in numbers. Superweapons typically can be build in unlimited quantities. Therefore a SCUD Storm being twice as good as Nuke Missile makes no sense.

**Comment by ExiLe-ZH** [comment]
> > Although I would like to add, China and USA get General Powers that destroy buildings, whereas GLA doesn't (apart from Demo).
> 
> It is an argument, but not a strong one. General Powers are limited in numbers. Superweapons typically can be build in unlimited quantities. Therefore a SCUD Storm being twice as good as Nuke Missile makes no sense.

It is a strong argument. If we would make Nuke similar to Scud, then it would be totally OP in combination with Genpowers in typical 1v1, 2v2 and 3v3 matches. 

In your scenario example the quantity of SW's would make impact of Genpowers insignificant, to the extent where we could give GLA the same Genpowers and it wouldn't make a difference.

**Comment by xezon** [comment]
If GLA builds 5 SCUD Storms, then it essentially has 10 Nuke Missiles worth of firepower.

Meanwhile China with 5 Nuke Missiles, would have 6 Nuke Missiles worth of Firepower with its Artillery and Bomber.

How does this balance exactly?

**Comment by ExiLe-ZH** [comment]
> If GLA builds 5 SCUD Storms, then it essentially has 10 Nuke Missiles worth of firepower.
> 
> Meanwhile China with 5 Nuke Missiles, would have 6 Nuke Missiles worth of Firepower with its Artillery and Bomber.
> 
> How does this balance exactly?

If 5 Nukes are worth 5 Particles of firepower that would good enough of an improvement. We don't need to give China Scudstorms.

**Comment by xezon** [comment]
https://user-images.githubusercontent.com/4720891/184233776-2d8bb51d-fd18-4057-8b2c-8a781627a079.mp4

**Comment by ExiLe-ZH** [comment]
> chinapowers.mp4

To destroy 2 enemy Scudstorms, China needs 2 Nukes and his Genpowers (if Carpet Bomber can reach target).

GLA needs 4 Scudstorms (Demo needs 2).

**Comment by ZekeDlyoung** [comment]
This happens when you use multiple blasts for the nuclear missile but give it a growing damage radius, for some reason that part of the code doesn't work very well (or at least I haven't been able to make it work correctly)

A simple fix for this would be to make all the blast waves have the same radius (and perhaps the same damage as well if you you want absolute uniformity)

**Comment by commy2** [comment]
The aftermath would be identical with the 1.04 Nuke, except from the holes surviving. The multi blast PR was designed that way. The mechanics of the nuke are well understood at this point.

**Comment by ZekeDlyoung** [comment]
I don't think making it act like the 1.04 nuke is a bad thing, the only problem it had was leaving holes, most players don't know about the growing radius, and I doubt they would want it more than a consistent area deleter

**Comment by commy2** [comment]
The 1.04 nuke does not deal constant damage. Damage depends on distance from center.

**Comment by ZekeDlyoung** [comment]
Yeah, but it's not as random as with a growing radius iirc

**Comment by commy2** [comment]
They are identical aside from floating point rounding. There is nothing random about it either, it is fully deterministic.

**Comment by ZekeDlyoung** [comment]
It still causes the nuke to act differently to VZH, and not for the better, all for a "visual treat" that most players won't even notice most of the time

**Comment by commy2** [comment]
?????
It's for making it destroy holes while keeping the damage fall of exactly the same for static objects, and only ever increase for objects moving towards the center of blast (a broken setup is conceivable that would cause units moving towards the center to receive less damage than they should).

**Comment by ZekeDlyoung** [comment]
> a broken setup is conceivable that would cause units moving towards the center to receive less damage than they should

This is what I mean. Yes this can be fixed with more tweaks, but do we even want this damage falloff feature in the first place?

If the only objective is to destroy holes, wouldn't 2-3 blasts of equal damage and radius be enough?

**Comment by commy2** [comment]
> do we even want this damage falloff feature in the first place

I do not know. The objective previously was destroying holes on overkill in a minimally invasive way, which means preserving the exact amount of damage any building receives before and after the patch.

Possibly we want to change the damage profile to make the Nuke Silo more versatile. Damage falling off is not unprecedented in the game though. You know this, but Scud Missiles for example have a smaller primary damage radius and a larger secondary damage radius. The Nuke gives more fine grained control over this. I don't think damage falling off over range is that unintuitive. I certainly feel like the Nuke would be overpowered if it did full damage over the entire currently affected area.

> If the only objective is to destroy holes, wouldn't 2-3 blasts of equal damage and radius be enough?

The more steps are involved, the more likely it becomes that a building's hole is destroyed:
40% damage -> 80% damage -> 120% damage (destroyed to hole with 20% wasted on overkill)
vs.
20% damage -> 40% -> 60% -> 80% -> 100% (destroyed to hole) -> hole takes rest

**Comment by ZekeDlyoung** [comment]
> I certainly feel like the Nuke would be overpowered if it did full damage over the entire currently affected area.

But isn't this what it did in the base game?

To clarify, I don't mean making the inner and outer radius the same for each blast. I meant making the inner and outer blast radius the same across each of the 6 blasts.

So every blast has 60 inner radius and 210 outer radius

**Comment by commy2** [comment]
> But isn't this what it did in the base game?

No. See:
![68747470733a2f2f692e696d6775722e636f6d2f44305062415a462e706e67](https://user-images.githubusercontent.com/6576312/184283560-3727731f-f96e-4c41-9ac1-b462127edf12.png)

At center of blast, damage is constant. Outside the center, it falls off to a minimum value.

**Comment by ZekeDlyoung** [comment]
> To clarify, I don't mean making the inner and outer radius the same for each blast. I meant making the inner and outer blast radius the same across each of the 6 blasts.
>
>So every blast has 60 inner radius and 210 outer radius

Basically instead of this: https://camo.githubusercontent.com/30e65d2c0f696e5f15be2432f020450031a7b5ce9ba48c114de6dcab51c21835/68747470733a2f2f692e696d6775722e636f6d2f6d6648676971542e706e67

It would be this 6 times:
https://camo.githubusercontent.com/4caf81ee565de2a371b4d40d5745b502e48192a4f30811fe6918d3839550c209/68747470733a2f2f692e696d6775722e636f6d2f44305062415a462e706e67
EDIT: Well not exactly, but you get what I mean right?

**Comment by commy2** [comment]
Yes.
I fail to see what your objective is though. A different profile could mean that certain holes may or may not be overkilled as buildings instead of destroyed. When I look at xezons video though, all holes are destroyed as one would expect. I am still stuck on your comment that:
> This happens when you use multiple blasts for the nuclear missile but give it a growing damage radius

I fail to see how. If the problem you're raising is different from the title issue, then it probably should get its own ticket.

**Comment by ZekeDlyoung** [comment]
Well perhaps I am misunderstanding something as well

It's just when I read the title: "China Nuclear Missile has small effective damage radius", it reminded me of my own experience when I enabled multiple blasts for the nuke as well, where for some reason the Nuke sometimes looked liked like it wasn't damaging structures like it should when compared to VZH. Equalizing the blast radius of each blast seemed to make it more consistent for me, but if I'm not making sense to you then just ignore me I guess

**Comment by commy2** [comment]
I do not want to ignore you. Any help on this particular issue and on the project in general is always appreciated. 
To evaluate why you may have experienced this, I would have to see the numbers you entered.

Your posts seemed to imply that the insufficient performance of the Nuke was related to changes I made. I disagree with that. If that is not what you meant, then I apologize.

**Comment by ZekeDlyoung** [comment]
> I do not want to ignore you. Any help on this particular issue and on the project in general is always appreciated. To evaluate why you may have experienced this, I would have to see the numbers you entered.
> 
> Your posts seemed to imply that the insufficient performance of the Nuke was related to changes I made. I disagree with that. If that is not what you meant, then I apologize.

Yeah thinking about it some more, it could be the problem I faced before doesn't apply to this issue, so I'm not saying "ignore me" out of spite, more of, I may have spoken too soon without actually checking the situation first 🙃

**Comment by ZekeDlyoung** [comment]
That said, can someone test this anyway to see if there's a difference 🙃

https://i.imgur.com/SsOntuO.jpg

**Comment by commy2** [comment]
I think we agree that in order to avoid overkill before holes, damage has to be dealt in steps. Your approach seems to be to make each of these steps identical (hopefully I got it now). 

My approach is to maximize the constant damage area for each step in such a way that I keep the total damage at each position identical to 1.04. 

The graphic you posted displays tallies. A better visualization may be this:

![Figure_1](https://user-images.githubusercontent.com/6576312/184288973-1397ad2b-8dc7-4ef4-bffc-3cc2a69da869.png)

As you can see, I minimize the area affected by the falling off slope on all steps. The advantage of constant damage is that overkill scenarios become predictable. 

I concede that the time intervals were just taken by what EALA entered. I found nothing wrong with them.

It would probably be better to have the blasts in reverse: first damage outer most area, then decrease radius until the smallest blast area. That way the "slope" would be transferred completely to any hole or bunkered Battle Bus. But that would either look very wrong or require all blasts to happen at basically same time (1 frame difference probably).

**Comment by xezon** [comment]
I did review the math commy2 applied to patched Nuke Missile back then and it checked out, meaning it should apply exact same damage as original.

**Comment by commy2** [comment]
^ This. While also going for maximum Hole ownage.

**Comment by MTKing4** [comment]
> > # Superweapon Point Damage Test
> 
> I don't think This test was done properly, Nuke and Scud Distributes the damage on crowded buildings, should have done it on a single Building with nothing around it.
> 
> Also particle Cannon does more damage if moved around, so I've heard, not certain.

Ok, Test Result is here

Moving Particle Cannon for More Damage=BS
-
![Particle](https://user-images.githubusercontent.com/83613147/184506730-57b589f0-8e12-4488-a81d-6acc3c2f8c83.png)

Nuclear Missile On isolated Building=More Damage
-
![Nuke](https://user-images.githubusercontent.com/83613147/184506788-a42e5f01-51ff-45c2-9982-268c68d0d4c7.png)


SCUD Missile On isolated Building=More Damage
-
![Scud](https://user-images.githubusercontent.com/83613147/184506830-fa77e4e2-8f41-42e6-9a60-c71a8d012137.png)

it's a little harder to spot on The Scud But it looks like more damage to me, also i think it's a bit more random and it depends on where do the Missiles fall

**NOTE**: Test Was Made on Main Branch

**Comment by commy2** [comment]
> Moving Particle Cannon for More Damage=BS

Good to know that others fail to reproduce this as well.

> a bit more random and it depends on where do the Missiles fall

Just for the record, the missiles will deterministically hit the same positions every time.

**Comment by MTKing4** [comment]
> Just for the record, the missiles will deterministically hit the same positions every time

I could've swore I've seen them fall differently sometimes, like the time of landing, sometimes they fall at the same moment sometimes a bit different, but i guess this changes depending on the orientation of the building and the angle of the launch relative to the SCUD which would make some fall before others Vice versa.

**Comment by commy2** [comment]
Moment may change depending on the orientation of the Scud Storm and direction of target and probably the terrain, but positions are fixed.

**Comment by xezon** [comment]
I can't replicate the claim about more damage applied to isolated structure. Here is my test result. Shot with SCUD Storm. Damage amount looks same. Please test again and provide side by side comparison.

Edit: Also tested with Nuke Missile. Also same damages.

![shot_20220813_215704_1](https://user-images.githubusercontent.com/4720891/184508973-73211f95-f38f-44e6-9140-96aeaee3d5d1.jpg)

![shot_20220813_215742_2](https://user-images.githubusercontent.com/4720891/184508976-7914b926-1c0e-4269-be8c-b732c8f1595a.jpg)

**Comment by MTKing4** [comment]
I wasn't very sure about the SCUD Either, but i Compared the Nuke with the Video above

Here's a SS of that

![Screenshot_20220813-231809_Chrome](https://user-images.githubusercontent.com/83613147/184509536-a22a035d-c438-4a68-876e-5539ea3f6e1c.jpg)

Compared to mine 

![Nuke](https://user-images.githubusercontent.com/83613147/184506788-a42e5f01-51ff-45c2-9982-268c68d0d4c7.png)

I'll do more testing later as I'm off now.

**Comment by ExiLe-ZH** [comment]
Just tested it, damage radius seems to match the Targeting Cursor and it does kill Fortified Markets just like Scuds and Particles do.

**Comment by ExiLe-ZH** [comment]
Ok, so right now the Scud and Nuke are pretty much similar, generally I like the improvement but shouldn't they have some more diversified pros and cons? That would make it more interesting imo since the weapons our quite different in their nature.

What about increasing the Nuke's center damage, but making the radius slightly smaller. It would make sense since the Scud Missiles spread out over a large area right? 

Example model:
- Nuke can 1 Shot a Scud to the hole, same like the Demo Scud.
- Outer radius will only kill Fortified Markets to the hole.

Example result: 
6 minutes cooldown might now be justified, it won't be a weapon of mass destruction (on it's own vs economy), but China has more potential keeping up with the SW race. Genpowers are needed to finish off holes.

**Comment by xezon** [comment]
I am not entirely comfortable with such buff on Nuke Missile. It would make it much better than Particle and regular SCUD. We would need some evidence that China would still struggle in Superweapon wars with the current adjustments.

**Comment by ExiLe-ZH** [comment]
> I am not entirely comfortable with such buff on Nuke Missile. It would make it much better than Particle and regular SCUD. We would need some evidence that China would still struggle in Superweapon wars with the current adjustments.

Well, why does Demo deserve to have a SW like this, with a good radius aswell?

**Comment by xezon** [comment]
I think not. It gives Demo General big advantage in Superweapon war. We could reduce...

**Comment by Jundiyy** [comment]
I think Nuke is fine at the moment. There isn't a need to make it even better.

Regarding Demo Scud, yes it is stronger. But I don't think we should nerf it, same for Tox. We've buffed 4 Nukes, which I think is a good thing.

**Comment by ExiLe-ZH** [comment]
@xezon 
> I am not entirely comfortable with such buff on Nuke Missile. It would make it much better than Particle and regular SCUD. We would need some evidence that China would still struggle in Superweapon wars with the current adjustments.

@Jundiyy 
> I think Nuke is fine at the moment. There isn't a need to make it even better.
> 
> Regarding Demo Scud, yes it is stronger. But I don't think we should nerf it, same for Tox. We've buffed 4 Nukes, which I think is a good thing.

The idea is not to make the Nuke better than other SW's, it's to diversify it by giving it pros and cons. Both can be tweaked till we reach desired result.

I'm also wary about nerfing Demo Scud btw, only if we can do it by giving it logical pros and cons.

**Comment by Stubbjax** [comment]
I think the Nuke being fast enough to take out large armies is already enough of a differentiator and more interesting.

**Comment by ExiLe-ZH** [comment]
> I think the Nuke being fast enough to take out large armies is already enough of a differentiator and more interesting.

So basically it's better than the Scud right now, same performance but much faster.

**Comment by xezon** [comment]
The SCUD Storm does have better range.

**Comment by ExiLe-ZH** [comment]
> The SCUD Storm does have better range.

Doesn't seem as significant as the Missile speed difference though, the bonus range of the Scud can't finish off extra buildings in the SDZ test, which are relatively low HP. So in practice, not a real difference in range.

Think we haven't taken this factor (missile speed) into account enough tbf.

**Comment by xezon** [comment]
SCUD Storm applies significantly more damage for Toxin and Demo, can be stealthed with Kassad, has no power outages, does have measurable better damage radius, has better countdown of 5:00 minutes.

The better damage radius is measureable as per research shown. In the Black Market test, it damages 2.5 times as many buildings as Nuke Missile does.
* #871

I think it is mistake to ignore the SCUD Storm perks and claim that China Nuke Missile is better.

**Comment by Stubbjax** [comment]
And leaves a hole + has Fortified Structures upgrade.

**Comment by ExiLe-ZH** [comment]
@xezon 
> SCUD Storm applies significantly more damage for Toxin and Demo, can be stealthed with Kassad, has no power outages, does have measurable better damage radius, has better countdown of 5:00 minutes.
> 
> The better damage radius is measureable as per research shown. In the Black Market test, it damages 2.5 times as many buildings as Nuke Missile does.
> 
>     * [Change: Increase China Nuke Missile damage by 20% and blasts radii by 2%, 3.3%, 4%, 4.4%, 4.7%, 20% #871](https://github.com/TheSuperHackers/GeneralsGamePatch/pull/871)
> 
> 
> I think it is mistake to ignore the SCUD Storm perks and claim that China Nuke Missile is better.

@Stubbjax 
> And leaves a hole + has Fortified Structures upgrade.

True, all those factors besides damage radius (or Fortified Structures*) are quite significant and probably outweigh missile speed.

However I feel that damaged buildings in the outer radius don't impact the game that much, unless you have a direct follow up to quickly kill those buildings.

Raw damage output of Demo Scud makes more of a difference. Gamma Scud damages enemy Scud down to like 1HP, Demo down to hole, now this tiny difference is very significant. In the radius example the Demo Scud only kills 1 extra building in SDZ test.

*Btw, don't think Fortified Structures affect Scuds.

**Comment by xezon** [comment]
Outer radius damage stacks if player fires 2 Superweapons.

**Comment by ExiLe-ZH** [comment]
> Outer radius damage stacks if player fires 2 Superweapons.

That's also true.

Still happy about changes overall :)

**Comment by Stubbjax** [comment]
> 
> *Btw, don't think Fortified Structures affect Scuds.

You're right! It uses an entirely separate 'tough' armour, which all super weapons share. There's still more likely to be a worker nearby to repair it though. Also keep in mind that the outer SCUD damage, while maybe not enough to destroy buildings, will still likely destroy units.

**Comment by ExiLe-ZH** [comment]
Radation damage and duration is dissapointing, perhaps swap that with the Scudstorm. With the Scudstorm having 95% of the pros, the Nuclear Missile deserves a little something doesn't it? 

Another redesign would be to swap the decay only, so that Nuclear radiation has the longer decay (realistic), but less damage than Anthrax.

**Comment by xezon** [comment]
### Nuke Missile

```
Object NukeRadiationFieldWeapon
  Behavior = LifetimeUpdate ModuleTag_04
    MinLifetime = 30000
    MaxLifetime = 30000
  End
End

Weapon NukeRadiationFieldWeapon
  PrimaryDamage = 25.0
  PrimaryDamageRadius = 200.0
  DamageType = RADIATION
  DeathType = NORMAL
  WeaponSpeed = 600                     ;  dist/sec
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS NOT_AIRBORNE
  DelayBetweenShots = 750                ; time between shots, msec
End
```

### Scud Missile (multiples)

```
Object PoisonFieldLarge
  Behavior = LifetimeUpdate ModuleTag_04
    MinLifetime = 45000  ; 45 seconds
    MaxLifetime = 45000
  End
End

Weapon LargePoisonFieldWeapon
  PrimaryDamage = 15.0
  PrimaryDamageRadius = 140.0
  DamageType = POISON
  DeathType = POISONED
  WeaponSpeed = 600                     ;  dist/sec
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS NOT_AIRBORNE
  DelayBetweenShots = 500                ; time between shots, msec
End
```
