### ISSUE TITLE
Sentry Drone is rarely used

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#862]
Potential good uses for the unit:
- Extending map vision for several purposes.
- Supporting armies by extending Shroud Reveal and Stealth Detection ranges (to avoid DemoTraps, Tunnels etc.).
- Intercepting (stealth) Workers and Hero's.*
- Protecting oils from being captured.*
- Scouting and killing Hackers.*
- Harassing Worker/Truck collection.*

*MG needed.

Negatives:
- Drone is expensive and fairly useless without the Machine Gun upgrade.
- Shroud Clearing and Stealth Detection range aren't great.
- Machine Upgrade expensive and extremely slow building.
- DPS is fairly weak.
- Deployment time makes it slow reacting, some people may experience this as buggy as there is no visual/audio clues for this behavior.
- Tire-tracks are visible for enemies.
- Damaged smoke reveals it permanently, without ways to field repair other than using Emergency Repair or capturing a Repair Bay.

### Stats
**Price & Build Time:**
| |Price|Build Time|
|-|-----|----------|
|Drone|800/800/850/1000 (usa/las/sw/af)|13.3s|
|MG Upgrade|1000|30s|

**DPS, AttackRange & Armor:**
| |Sentry Drone|Vee|
|-|------------|---|
|DPS|40|50 (60 with Bombardment*)|
|AttackRange|150|150 (180 with Search&Destroy*)|
|Armor|300 (375 with DroneArmorUpgrade**)|240 (252 with HoldTheLine*)|

_*Battleplan from Strategy Center._
_**Drone Armor upgrade from Strategy Center._

**Vision & Stealth Detection Range:**
| |Sentry Drone|Outpost|
|-|------------|-------|
|Vision range|200|250|
|Shroud clearing range|350|500|
|Stealth detection range|225|300|

### Proposals

- **Proposal 1:**
Remove or decrease deployment time.

- **Proposal 2:**
Add visual and/or audio clues for deployment.

- **Proposal 3:**
Reevaluate pricing and/or build time.

- **Proposal 4:**
Reevaluate pricing and/or build time for the MachineGun upgrade.

- **Proposal 5:**
Give MachineGun by default, or reimplement it as unit upgrade (same like a HellFire Drone or Propaganda Tower).

- **Proposal 6:**
Add auto-repair.

- **Proposal 7:**
Enhance shroud clearing range.

- **Proposal 8:**
Enhance stealth detection range.

- **Proposal 9:**
Remove tire tracks, they completely give away the Sentry's position.

- **Proposal 10:**
Remove smoke effects when damaged (Auto-Repair alternative), smoke makes the Sentry visible permanently.

- **Proposal 11:**
Sentry Drone can climb mountains. Helps with sneakily entering and escaping enemy bases, it already has trouble doing that since it's revealed when moving. Many maps are chokepointy aswell.

**Comment by commy2** [comment]
- deals only 80% dps of a Vee (no Tow).
- has 1s deploy time when switching between firing and movement mode.

**Comment by xezon** [comment]
Sentry Drone is a disgrace for Zero Hour.

**Comment by commy2** [comment]
In 1.04, it's so ashamed of itself that it doesn't even play a voice line when leaving the factory.
https://github.com/TheSuperHackers/GeneralsGamePatch/pull/256

**Comment by commy2** [comment]
Detection range is either 200 or 225. Depending on if DetectionRange is implemented correctly in StealthDetectorUpdate or if the VisionRange is always used.

Fog of war revealed is 350 vs 400 of a Missile Defender. That means that the Missile Defender reveals 30% more area. For comparison, a Listening Outposts reveals 500, which is more than twice the area.
However, I do not think that USA would suddenly switch to Sentry Drones for scouting, considering much better options like Scout Drones, Spy Drones, Spy Satellite, Intelligence ... Chinooks exist.

**Comment by commy2** [comment]
Fog of war revealed is 350 vs 400 of a Missile Defender. That means that the Missile Defender reveals 30% more area. For comparison, a Listening Outposts reveals 500, which is more than twice the area.
However, I do not think that USA would suddenly switch to Sentry Drones for scouting, considering much better options like Scout Drones, Spy Drones, Spy Satellite, Intelligence ... exist.

**Comment by ExiLe-ZH** [comment]
> 

upgrading vision to 400 wouldn't hurt then.

what's detection range for outpost or lotus?

**Comment by Jundiyy** [comment]
> Sentry Drone is a disgrace for Zero Hour.

> In 1.04, it's so ashamed of itself that it doesn't even play a voice line when leaving the factory. #256

Daym, that hate is real 😂 show some love.

**Comment by xezon** [comment]
Stubbjax:
![sentrydrone](https://user-images.githubusercontent.com/4720891/184064663-89b83006-5ede-4586-aa71-2f6c6035e266.png)

**Comment by MTKing4** [comment]
I think one idea to improving them is making them stealth all the time except when shooting, instead of stealth only when stationary

**Comment by ExiLe-ZH** [comment]
> I think one idea to improving them is making them stealth all the time except when shooting, instead of stealth only when stationary

Maybe could give machinegun by default and replace it with stealth upgrade for cheap, maybe from strat center so it doesn't delay important production.

**Comment by xezon** [comment]
I would prefer to make it not overcomplicated. It just becomes a maintenance burden for the developers if we add new designs for this crap unit.

**Comment by ReLaX82** [comment]
> I would prefer to make it not overcomplicated. It just becomes a maintenance burden for the developers if we add new designs for this crap unit.

Agree, dont make it too complicated with this unit.

**Comment by ExiLe-ZH** [comment]
Added all mentioned proposals to main post.

So far I think the following proposals are accepted by everyone as **_minimum_** change:

> 
> - **Proposal 1:**
> Remove or decrease deployment time.

Decrease to 25 or 50%.

> - **Proposal 2:**
> Add visual and/or audio clues for deployment.

Add sound.

> 
> - **Proposal 3:**
> Reevaluate pricing and/or build time.

Standardize price to $800 for all factions.

> - **Proposal 4:**
> Reevaluate pricing and/or build time for the MachineGun upgrade.

Reduce to $800, same like TOW.

> - **Proposal 7:**
> Enhance shroud clearing range.

Match MD range of 400.

These changes however don't satisfy the needs of everyone, so #discussion ongoing.

**Comment by xezon** [comment]
As for Proposal 7, what do you mean by Vision Range? Vision range, Shroud clearing range or Stealth detection range? Maybe make all of them individual proposals.

**Comment by ExiLe-ZH** [comment]
Splitted them up.

**Comment by xezon** [comment]
Relevant Stats Dump

```

Object SupW_AmericaVehicleSentryDrone
  BuildCost       = 1000
  BuildTime       = 10.0
  VisionRange     = 200
  ShroudClearingRange = 350

  Body = ActiveBody ModuleTag_02
    MaxHealth       = 300.0
    InitialHealth   = 300.0
  End

  Behavior = DeployStyleAIUpdate ModuleTag_04
    PackTime   = 1000
    UnpackTime = 1000
  End

  Behavior = StealthDetectorUpdate ModuleTag_12
    DetectionRate  = 900
    DetectionRange = 225
  End


Object SupW_AmericaVehicleHumvee
  BuildCost = 850
  BuildTime = 10.0

  Body = ActiveBody ModuleTag_02
    MaxHealth       = 240.0
    InitialHealth   = 240.0
  End

  Behavior = TransportContain  ModuleTag_05
    PassengersAllowedToFire = Yes
    Slots             = 5
    DamagePercentToUnits = 100%
  End


Object Lazr_AmericaVehicleSentryDrone
  BuildCost = 800
  BuildTime = 10.0


Object Lazr_AmericaVehicleHumvee
  BuildCost = 700
  BuildTime = 10.0


Object AmericaVehicleSentryDrone
  BuildCost = 800
  BuildTime = 10.0


Object AmericaVehicleHumvee
  BuildCost = 700
  BuildTime = 10.0


Object AirF_AmericaVehicleSentryDrone
  BuildCost = 850
  BuildTime = 10.0


Object AirF_AmericaVehicleHumvee
  BuildCost = 800
  BuildTime = 10.0


Armor SentryDroneArmor
  Armor = JET_MISSILES        30%
  Armor = STEALTHJET_MISSILES 30%
  Armor = CRUSH               50%
  Armor = SMALL_ARMS          50%
  Armor = GATTLING            50%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN     50%
  Armor = INFANTRY_MISSILE    50%
  Armor = POISON              00%
  Armor = MICROWAVE            0%
  Armor = SNIPER               0%
  Armor = MELEE                0%    ;trucks don't generally take much damage other than paint damage from MELEE weapons
  Armor = LASER                0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP       0%    ;Not harmed by cleaning weapons
  Armor = KILL_PILOT           0%    ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER            0%    ;Capture type weapons are effective only against infantry.
  Armor = FLAME               50%   ;hummers flame resistant so they can deal with MIGs.
  Armor = SUBDUAL_MISSILE      0%
  Armor = SUBDUAL_VEHICLE    100%
  Armor = SUBDUAL_BUILDING     0%
End


Armor HumveeArmor
  Armor = JET_MISSILES        30%
  Armor = STEALTHJET_MISSILES 30%
  Armor = CRUSH               50%
  Armor = SMALL_ARMS          50%
  Armor = GATTLING            50%    ;resistant to gattling tank
  Armor = COMANCHE_VULCAN     50%
  Armor = INFANTRY_MISSILE    50%
  Armor = POISON              50%
  Armor = MICROWAVE            0%
  Armor = SNIPER               0%
  Armor = MELEE                0%    ;trucks don't generally take much damage other than paint damage from MELEE weapons
  Armor = LASER                0%    ;lasers are anti-personel and anti-projectile only (for point defense laser)
  Armor = HAZARD_CLEANUP       0%      ;Not harmed by cleaning weapons
  Armor = KILL_PILOT         100%      ;Jarmen Kell uses against vehicles only.
  Armor = SURRENDER            0%    ;Capture type weapons are effective only against infantry.
  Armor = FLAME               50%   ;hummers flame resistant so they can deal with MIGs.
  Armor = SUBDUAL_MISSILE      0%
  Armor = SUBDUAL_VEHICLE    100%
  Armor = SUBDUAL_BUILDING     0%
End


Upgrade Upgrade_AmericaSentryDroneGun
  DisplayName        = UPGRADE:AmericaSentryDroneGun
  BuildTime          = 30.0
  BuildCost          = 1000
  ButtonImage        = SASentryUpgr
End


Upgrade Upgrade_AmericaTOWMissile
  DisplayName        = UPGRADE:TOWMissile
  BuildTime          = 30.0
  BuildCost          = 800  ; 1200
  ButtonImage        = SSTowMissiles
  ResearchSound      = HumveeVoiceUpgradeTowMissiles
End


Weapon SentryDroneGun
  PrimaryDamage = 8.0
  PrimaryDamageRadius = 0.0
  AttackRange = 150.0
  DamageType = COMANCHE_VULCAN
  DeathType = NORMAL
  WeaponSpeed = 600
  ProjectileObject = NONE
  FireFX = WeaponFX_SentryDroneGunFire
  VeterancyFireFX  = HEROIC WeaponFX_GenericMachineGunFireWithRedTracers
  FireSound = SentryDroneWeapon
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 200
  ClipSize = 0
  ClipReloadTime = 0
End


Weapon HumveeGun
  PrimaryDamage = 10.0  ; 8.0
  PrimaryDamageRadius = 0.0
  AttackRange = 150.0
  DamageType = COMANCHE_VULCAN
  DeathType = NORMAL
  WeaponSpeed = 600
  ProjectileObject = NONE
  FireFX = WeaponFX_TechnicalGunFire
  VeterancyFireFX  = HEROIC WeaponFX_GenericMachineGunFireWithRedTracers
  FireSound = HumveeWeapon
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 200
  ClipSize = 0
  ClipReloadTime = 0
End


Weapon HumveeMissileWeapon
  PrimaryDamage = 30.0
  PrimaryDamageRadius = 5.0
  ScatterRadiusVsInfantry = 10.0
  AttackRange = 150.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 600
  ProjectileDetonationFX = WeaponFX_RocketBuggyMissileDetonation
  ProjectileObject = HumveeMissile
  ProjectileExhaust = TowMissileExhaust
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 1000
  ClipSize = 1
  ClipReloadTime = 2000
  AutoReloadsClip = Yes
  FireSound = HumveeWeaponTOW
  ProjectileDetonationFX = WeaponFX_RocketBuggyMissileDetonation
  AntiAirborneVehicle         = No
  AntiAirborneInfantry        = No
  AntiGround = Yes
  ProjectileCollidesWith = STRUCTURES
End


Weapon HumveeMissileWeaponAir
  PrimaryDamage = 50.0
  PrimaryDamageRadius = 5.0
  ScatterRadiusVsInfantry = 10.0
  AttackRange = 320.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 600
  ProjectileDetonationFX = WeaponFX_RocketBuggyMissileDetonation
  ProjectileObject            = PatriotMissile
  ProjectileExhaust = MissileExhaust
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 1000
  ClipSize = 1
  ClipReloadTime = 2000
  AutoReloadsClip = Yes
  FireSound = HumveeWeaponTOW
  ProjectileDetonationFX = WeaponFX_RocketBuggyMissileDetonation
  AntiAirborneVehicle         = Yes
  AntiAirborneInfantry        = No
  AntiGround = No
  ProjectileCollidesWith = STRUCTURES
End


Locomotor SentryLocomotor
  Surfaces                = GROUND
  Speed                   = 60    ; in dist/sec
  SpeedDamaged            = 50    ; in dist/sec
  TurnRate                = 180   ;120   ; in degrees/sec
  TurnRateDamaged         = 180   ;120   ; in degrees/sec
  Acceleration            = 60    ; in dist/(sec^2)
  AccelerationDamaged     = 60    ; in dist/(sec^2)
  Braking                 = 60    ; in dist/(sec^2)
  MinTurnSpeed            = 20    ; in dist/sec
  TurnPivotOffset         = -0.33 ; where to pivot when turning (-1.0 = rear, 0.0 = center, 1.0 = front)
  ZAxisBehavior           = NO_Z_MOTIVE_FORCE
  Appearance              = TREADS
  StickToGround           = No
End


Locomotor HumveeLocomotor
  Surfaces                = GROUND
  Speed                   = 60    ; in dist/sec
  SpeedDamaged            = 30    ; in dist/sec
  TurnRate                = 180   ;120   ; in degrees/sec
  TurnRateDamaged         = 180   ;120   ; in degrees/sec
  Acceleration            = 1000  ;60    ; in dist/(sec^2)
  AccelerationDamaged     = 1000  ;60    ; in dist/(sec^2)
  Braking                 = 1000  ;60    ; in dist/(sec^2)
  MinTurnSpeed            = 20    ; in dist/sec
  TurnPivotOffset         = -0.33 ; where to pivot when turning (-1.0 = rear, 0.0 = center, 1.0 = front)
  ZAxisBehavior           = NO_Z_MOTIVE_FORCE
  Appearance              = FOUR_WHEELS
  StickToGround           = No
End
```

**Comment by xezon** [comment]
Here is my analysis on Sentry Drone.

## Vehicle costs

There is no way the Sentry Drones are more valuable than Humvee. Yes they have Stealth detection and Stealth capability, but they spawn without gun by default, have no transport slots and cannot buy drones. It looks safe to match price with Humvee. On a side note, I would even consider matching Humvee price of SWG with AFG to 800. SWG is factually worse General than AFG, and it also ranks bottom in casual games (42.67% winrate) and second last in pro games (39.19% winrate) (see GenTool data in our Design Balancing folder). So it should not be more expensive than AFG, maybe not even more expensive than USA. And then Sentry Drone Price can match it. As for AFG, it does not need to be priced any better than 800. AFG has stealth detection on King Raptors. It can be happy with a generous 50 cost reduction as is.

| Object           | Price Regular | Price Laser | Price Air | Price Swg |
|------------------|---------------|-------------|-----------|-----------|
| Original Humvee  | 700           | 700         | 800       | 850       |
| Original Drone   | 800           | 800         | 850       | 1000      |
| Better Humvee    | 700           | 700         | 800       | 800       |
| Better Drone     | 700           | 700         | 800       | 800       |

Alternative to favor SWG more:

| Object           | Price Regular | Price Laser | Price Air | Price Swg |
|------------------|---------------|-------------|-----------|-----------|
| Better Humvee    | 700           | 700         | 800       | 700       |
| Better Drone     | 700           | 700         | 800       | 700       |


## Vehicle build times

All Humvees and Sentry Drones build in 10 seconds (+ door time). It is not clear to me whether or not this needs adjusting. The data does not indicate. I do like the simplicity of consistency.


## Locomotor

Sentry Drone And Humvee have very similar locomotor. Both have same top speed and turn speed. There are 2 differences: Sentry Drone drives faster than Humvee when damaged and has lower acceleration than Humvee.

The faster SpeedDamaged looks reasonable. It is a scout unit, so ability to flee the scene quick is nice perk. However, the slower acceleration is not something it needs. It takes 1.00 seconds to accelerate, as opposed to 0.06 seconds for Humvee.

| Object           | Time until top speed (ms) |
|------------------|---------------------------|
| Original Humvee  | 60                        |
| Original Drone   | 1000                      |
| Better Drone     | 200                       |


## Deployment

Sentry Drone has a depoyment time of 1000 millisecond for both packing and unpacking. That means it requires 1 second to acquire a fresh target, and 2 seconds between engaging two targets if it needs to move to new position. This is a huge time and performance penalty. And not just that: It will also make the unit feel clunky and unresponsive, which is comparable to how units feel unresponsive in laggy matches. And no one likes laggy matches. Therefore, a removal of the deployment is reasonable, or alternatively a significant reduction if it can be accompanied with charge sound or model animation (complex, more work).


## Machine Gun Weapon

Machine Gun strength of Humvee and Sentry Drone is comparable. Sentry Drone deals 20% less damage, but the vehicle tanks 30% more damage, because Sentry Drone has more health. This looks fair. However, Sentry Drone is not trainable, meaning it will not benefit from veterancy buffs like Humvee does.

| Gun                             | VETERAN DPS | ELITE DPS | HERO DPS |
|---------------------------------|-------------|-----------|----------|
| Original SentryDroneGun         |             |           |          |
| Original HumveeGun              | +10%        | +80%      | +95%     |
| Original HumveeMissileWeapon    | +10%        | +20%      | +30%     |
| Original HumveeMissileWeaponAir | +10%        | +20%      | +30%     |

Humvee gun gains an astonishing 80% damage boost on Vet 2 with its Machine gun. This will outperform the Sentry Gun more than twice. Perhaps it is justified to match the Sentry Drone Gun damage with Humvee Gun damage, maybe even surpassing it a bit.

| Gun                             | Damage per Second |
|---------------------------------|-------------------|
| Original HumveeGun              | 50                |
| Original HumveeGun Vet 1        | 55                |
| Original HumveeGun Vet 2        | 90                |
| Original HumveeGun Vet 3        | 97.5              |
| Original SentryDroneGun         | 40                |
| Better SentryDroneGun           | 50                |
| Best SentryDroneGun             | 60                |


## Upgrade

Sentry Drone Gun has some things going against it. Drone starts without gun by default, but Humvee has it always. Humvee can get a second gun for 20% less cost at same build time. And that second gun is really good, because it does not just target ground units, but also air units.

| Gun                             | Damage per Second | Type            |
|---------------------------------|-------------------|-----------------|
| Original SentryDroneGun         | 40                | COMANCHE_VULCAN |
| Original HumveeGun              | 50                | COMANCHE_VULCAN |
| Original HumveeMissileWeapon    | 15                | EXPLOSION       |
| Original HumveeMissileWeaponAir | 25                | EXPLOSION       |

Structures and light vehicles have around 50% COMANCHE_VULCAN and 100% EXPLOSION, and tanks have 25% COMANCHE_VULCAN and 100% EXPLOSION. EXPLOSION is a much better damage type than COMANCHE_VULCAN. We can roughly say that Humvee Damage Output vs all things on ground is effectively doubled.

Since SentryDroneGun is not better than HumveeGun, there is no justification to price it at 1000. 800 to match it with TOW Missile Upgrade is fair. As for build time, it looks fair to halve it from 30 seconds to 15 seconds, because it is nowhere near as good as TOW, since it cannot shoot on Aircraft. Maybe another 5 seconds can be cut to compensate for the 20% lower damage output and/or the Drone requiring an upgrade to begin with to do any sorts of combat.

| Upgrade              | Cost | Time |
|----------------------|------|------|
| Original TOW Missile | 800  | 30   |
| Original Sentry Gun  | 1000 | 30   |
| Better Sentry Gun    | 800  | 15   |
| Best Sentry Gun      | 800  | 10   |


## Healing

When Drone is hurt, it can be repaired by driving back to home base. It drives fast. And it can be repaired with Ambulance. And with Repair Generals Power. It does not need auto healing.


## Handling

~~Sentry Drone is set to AutoAcquireEnemiesWhenIdle = Yes, this means it auto engages targets when it is equipped with gun and idle and stealthed. For a scout unit this appears to defeat its purpose. Disabling the AutoAcquireEnemiesWhenIdle would help to keep use it as scout after Upgrade purchase, which likely is a welcome change for Drone fans.~~


## Stealth Detection Range

| Object                           | Detection Range     | Movement Speed |
|----------------------------------|---------------------|----------------|
| Original USA Sentry Drone        | 225                 | 60             |
| Original USA Scout Drone         | 150 (+75+10 wander) | 60             |
| Original GLA Radar Van           | 250                 | 40             |
| Original China Outpost           | 300                 | 40             |
| Original China Lotus             | 300                 | 30             |
| Original China Overlord Gattling | 200                 | 20-40          |

Stealth Detection range looks okay. It is lower than of other units, but it is cheap and moves fast to compensate for it.


## Shroud Clearing Range

| Object                           | Shroud Clearing Range | Area   | Advantage over Sentry Drone |
|----------------------------------|-----------------------|--------|-----------------------------|
| Original USA Sentry Drone        | 350                   | 384845 |
| Original USA Scout Drone         | 500 (+75+10 wander)   | 785398 | +104%                       |
| Original USA Battle Drone        | 150 (+75+10 wander)   | 70685  | -82%                        |
| Original USA Hellfire Drone      | 500 (+75+10 wander)   | 785398 | +104%                       |
| Original USA Humvee              | 320                   | 321699 | -17%                        |
| Original USA Missile Defender    | 400                   | 502654 | +30%                        |
| Original China Outpost           | 500                   | 785398 | +104%                       |
| Original China Lotus             | 400                   | 502654 | +30%                        |

Sentry Drone has slightly better Shroud Clearing Range than Humvee, but it is completely dwarfed by Scout Drone (100 cost). An increase to 400 or higher is reasonable.


# Conclusion

There are many things that can be adjusted as shown above. We do not need to overcrank. Many small tweaks look very safe.

**Comment by commy2** [comment]
> Sentry Drone is set to AutoAcquireEnemiesWhenIdle = Yes, this means it auto engages targets when it is equipped with gun and idle and stealthed.

No, a unit only auto attacks when stealthed if it has the `AutoAcquireEnemiesWhenIdle = Yes Stealthed`  keys set. Compare Pathfinder (attacks) with AFG Comanche (does not attack).

**Comment by ExiLe-ZH** [comment]
I would still go with all these safe changes, it's certainly an improvement over 1.04.

These are my choices:
- $700 for all factions.
- Better locomotor.

Object | Time until top speed (ms)
-- | --
Original Humvee | 60
Original Drone | 1000
Better Drone | 200

- Removing deployment mechanic OR very fast.
- The "Better" MG performance.
Same MG as Vee (no veterancy to make it better).
- MG upgrade to $800/10s
- Match ShroudClearing range with the $100 ScoutDrone that can be purchased with any ground-vehicle in matter of seconds. 
- Improve Stealth detection range, it isn't very impressive for a specialized unit, that has no other abilities than StealthDetection and ShroudReveal before MG upgrade.

### Is it completely satisfying though? 
Not completely, the setup is still problematic, it's still too expensive without MG and MG Upgrade is still a waste of time/money compared to TOW. My best suggestion would still be to make the MG an Unit Upgrade with the following SAFE costs:
- Base Unit cost $600.
- MG $400.

Building a few is cheaper and faster, spamming will be worse.

![Machine Gun Upgrade](https://user-images.githubusercontent.com/32326277/187025397-62bdf353-d2a2-4ddf-8696-f671e0a13017.png)

If it's too controversial I just forget about it and happily move along with the accepted changes.

### Auto Repair
I would still like to further discuss the Auto-Repair feature though, I think it would be a nice improvement because:
- It's a scout unit, which means it's often far from home, WF repair is no option.
- Can't bring Ambulance with it, defeats it's Stealthy purpose.
- Can't vet up to gain auto-repair, unlike any other unit.
- GLA also has (magic) Junk Repair technology. Drone is high-tech.
- Only ways to repair in the field is capturing a Repair Bay, or using Emergency Repair.
- Auto-repair gives the Drone a change to re-stealth again and get rid of the smoke effects when damaged.

### Balancing  Auto-Repair:
- Only auto-repair when idle/stealth (not possible)
- Takes a little while before kicking in (possible)
- Repair at slower rate than Junk Repair / Repair Bay.

**Comment by MTKing4** [comment]
I go with the following:

## Cost 
I say it should be standardized regardless of faction at 700

## build Time

Leave as is

## Locomotor

Leave as is

## Deployment

Remove

## Machine gun

Leave as is

## Upgrade

$500 @ 10s

## Healing

No.

## Shroud Clearing Range

400

We don't need to buff the unit itself it's fine, it's the upgrade that's the issue, i think with these solutions it will be a solid choice.

## One More important note

It does benefit from Drone armor doesn't it? Well how much? We haven't considered that it seems.

**Comment by MTKing4** [comment]
> > Sentry Drone is set to AutoAcquireEnemiesWhenIdle = Yes, this means it auto engages targets when it is equipped with gun and idle and stealthed.
> 
> No, a unit only auto attacks when stealthed if it has the `AutoAcquireEnemiesWhenIdle = Yes Stealthed` keys set. Compare Pathfinder (attacks) with AFG Comanche (does not attack).

Off Topic: should china outposts also don't have `AutoAcquireEnemiesWhenIdle = Yes Stealthed` ? I think it'd make sense then.

**Comment by commy2** [comment]
> Off Topic: should china outposts also don't have AutoAcquireEnemiesWhenIdle = Yes Stealthed ? I think it'd make sense then.

Outpost has `AutoAcquireEnemiesWhenIdle = No`. It doesn't prevent passengers from attacking though.

**Comment by ExiLe-ZH** [comment]
### Few findings:
![Command   Conquer - Generals Screenshot 2022 08 28 - 11 04 14 60](https://user-images.githubusercontent.com/32326277/187066709-ca9ae1bd-e54b-4144-857d-7528d144c111.png)
![Command   Conquer - Generals Screenshot 2022 08 28 - 11 19 48 10](https://user-images.githubusercontent.com/32326277/187066998-3f71c8f8-7942-4869-bcfa-2fa6d6894914.png)

As can be seen in the pictures above, it's very hard to be stealthy at all. 
- Tracks are visible.
- Smoke makes it permanently revealed, fleeing/moving also reveals it obviously.
- The only ways to repair itself **in the field** is capturing a Repair Bay or using Emergency Repair.


### New proposals:
- **Proposal 9:**
Remove tire tracks, they completely give away the Sentry's position.

- **Proposal 10:**
Remove smoke effects when damaged (Auto-Repair alternative).

- **Proposal 11:**
Sentry Drone can climb mountains. Helps with sneakily entering and escaping enemy bases, it already has trouble doing that since it's revealed when moving. Many maps are chokepointy aswell.

**Comment by commy2** [comment]
> Remove tire tracks, they completely give away the Sentry's position.

Agreed. That's hilarious.

> Smoke makes it permanently revealed

Same is true for every other unit or building in the game. Requires engine changes.

> The only ways to repair itself in the field is capturing a Repair Bay or using Emergency Repair.

Or Ambo.

**Comment by ExiLe-ZH** [comment]
> Same is true for every other unit or building in the game. Requires engine changes.

Can't smoke rendering be removed all together for specific units (no matter whether it can stealth or not)?

> Or Ambo.

Quoting my previous post:

> 
> I would still like to further discuss the Auto-Repair feature though, I think it would be a nice improvement because:
> 
>    - It's a scout unit, which means it's often far from home, WF repair is no option.
>    - **_Can't bring Ambulance with it, defeats it's Stealthy purpose._**
>    - Can't vet up.
>    - GLA also has (magic) Junk Repair technology. Drone is high-tech.
>    - Only ways to repair in the field is capturing a Repair Bay, or using Emergency Repair.

**Comment by commy2** [comment]
> Can't smoke rendering be removed all together for specific units (no matter whether it can stealth or not)?

It can, but then why does the same issue persist on other units? Not saying this shouldn't be fixed, but if so, it should be fixed in Thyme, for all units, thus keeping the smoke as indicator for damage.

**Comment by MTKing4** [comment]
> > Off Topic: should china outposts also don't have AutoAcquireEnemiesWhenIdle = Yes Stealthed ? I think it'd make sense then.
> 
> Outpost has `AutoAcquireEnemiesWhenIdle = No`. It doesn't prevent passengers from attacking though.

Maybe it should prevent them

**Comment by ExiLe-ZH** [comment]
Lets take further discussion here as it's the main topic, no need to open anything new.

> Better at killing scaffolds I mean. Early in game. For example it could kill tech building scaffold.

Wouldn't recommend investing almost 2k and 40 seconds of production time into one single MG drone early game, sounds like a sure loss in any matchup. 

Like rebels are much cheaper, don't delay WF production and can be produced in higher quantities to guard mode multiple locations at once. It sounds like a decent tactic that surely others have thought of aswell, yet never seen anybody do it.

**Comment by ExiLe-ZH** [comment]
Instead of always stealth, another way of doing it, is making it reveal shortly during the deploy and undeploy transitions. 

Then you might think: Ok now you can just waypoint it in circles to keep it unrevealed. Well no, then audio will give away it's presence.

**Comment by xezon** [comment]
> Instead of always stealth, another way of doing it, is making it reveal shortly during the deploy and undeploy transitions.

Not clear to me if this is possible with current scripting capabilities.

I do like the removal of the deployment. It felt like lag.

**Comment by ExiLe-ZH** [comment]
> Not clear to me if this is possible with current scripting capabilities.

Is it possible to reveal it only for a few seconds after giving a move command? That was actually more the intention of the idea.

> I do like the removal of the deployment. It felt like lag.

True, because it's lacking visual or aural clues. The nuke cannon for example has a much longer deploy time, yet it doesn't feel like lag because of the clear animations. 

Edit: I actually got an animation idea, but I'm not sure how hard it is, what about tilting the gun up (like 45 degrees) when it's packed?

Btw, regarding scaffold hunting, perhaps it's possible to remove it's structure targeting capability? Though would that also deny targeting demo traps eg? 

Another cool feature would be the ability to clear mines or disarm traps, again just brainstorming :D

And another thing, I feel the moving sound is way too low pitched, it sounds like a heavy vehicle and doesn't sound very distinctive either.

**Comment by ExiLe-ZH** [comment]
One of the things I love of this game is how you have to mix units with China factions, where every unit has it's own strenght and where these strengths compliment each other. USA is severely lacking this since you can use Vees for everything and part of this are the Scout Drones. I feel Scout Drones are one of the main reasons why Sentry Drones are simply obsolete.

I think it would be really cool if Sentry Drones added actual value to an army composition and clearly does it better than Scout Drones, for example to avoid Demo Traps or Stealth Tunnels. It would be even more awesome if it was the main unit to guard the base against Heroes and other stealthy units. 

So here's the idea, what if we somewhat nerfed Scout Drones and transfer these strengths to the Sentry Drone? A more radical approach would be to even remove stealth detection from Scout Drones all together, this wouldn't only make them Sentry Drones complementary, but actually crucial.

**Comment by xezon** [comment]
It would be quite a big change to alter the function of the Scout Drone. It would be easier looking into decreasing it's detection range to encourage the production of complementary Sentry Drones.
