### ISSUE TITLE
Remove initial cooldown for Helix Napalm/Nuke bomb?

### ISSUE THREAD

**Issue by ExiLe-ZH** [TheSuperHackers/GeneralsGamePatch#991]
There are only a very few situations in which the napalm/nuke bomb is useful.

Usually it's used in some last resort when the helix has to evac and can't be brought home anymore, it could still destroy an unguarded (non captured) oil in the enemy's base e.g.

The problem is that it takes very long to upgrade and use the weapon because the cooldown is triggered after upgrading. 

Any other upgrade like proptowers, bunkers, gatling guns, any kind of drone are instantly functional, should this be the case for the napalm/nuke aswell?

**Comment by xezon** [comment]
There is precedent for this. USA Airforce Comanche Rocket Pod upgrade can be used immediately after purchase. Ranger building capture needs to wait for cooldown after purchase.

I am ok with streamlining Helicopter Upgrade behaviour.

**Comment by ReLaX82** [comment]
I like the idea, makes it a little more useful!

**Comment by commy2** [comment]
It should be reviewed how much damage the Nuke Helix Bomb deals. From memory, it is less than half that of a Helix Bomb, even before Black Napalm. If anything, it should do more.

**Comment by Stubbjax** [comment]
Definitely agree with this. It would be nice to see the bombs used more / at all. Innovative manoeuvres like waiting above a tunnel for a pop and then dropping a bomb - which happens maybe once every five years - would become a bit more viable and surely provide some additional strategic depth as well as excitement for observers / viewers.

It might also make sense to **drop** the price somewhat, perhaps from $800 to $500, due to the significantly heightened risk / vulnerability that accompanies their use. It's a tricky design because the bombs are most effective against large groups, but a large group often has some form of anti-air capability that is likely to turn the whole situation into a suicide mission. This is amplified by the clunky behaviour where the Helix has to stop directly above the target location for the ability to function.

It would be interesting if the bombs could be [dropped earlier before the target by inheriting some momentum](https://user-images.githubusercontent.com/11547761/187082776-5a79c481-771b-4737-b417-1c131e2fcabf.png), similarly to how carpet bomb trajectories appear to function. Such a change would make the behaviour feel more fluid and natural, as well as open up potential for more skilled usage by using the Helix's velocity to modify bomb trajectory.

Otherwise, a simple increase to the bomb's velocity so that it falls through the air faster would be an improvement. In its current form, it's far too easy for the opponent to dodge the bomb and completely avoid any harm, which makes the ability much harder to justify.

**Comment by xezon** [comment]
I summarized all above in new report.

**Comment by MTKing4** [comment]
Agree about the proposed changes, especially stubjax's

**Comment by ReLaX82** [comment]
Agree to Stubbjax.
We shouldn't forget that this bomb is actually of near to no use to vehicles as they are able to move.
